// <auto-generated>

namespace OpenWorker.GameServer.SoulWorker.Network.DataTypes.Enums.Opcodes;

/// <summary>
/// 
/// </summary>
public enum BoosterOpcode : byte
{
    /// <summary>
    /// Response
    /// </summary>
    ListLoad = 0x01,

    /// <summary>
    /// Response
    /// </summary>
    Add = 0x02,

    /// <summary>
    /// Response
    /// </summary>
    Remove = 0x03,

    /// <summary>
    /// Response
    /// </summary>
    Clear = 0x04,
}
