// <auto-generated>

namespace OpenWorker.GameServer.SoulWorker.Network.DataTypes.Enums.Opcodes;

/// <summary>
/// 
/// </summary>
public enum ChannelOpcode : byte
{
    /// <summary>
    /// Request, Response
    /// </summary>
    Info = 0x01,

    /// <summary>
    /// Request, Response
    /// </summary>
    Change = 0x02,
}
