// <auto-generated>

namespace OpenWorker.GameServer.SoulWorker.Network.DataTypes.Enums.Opcodes;

/// <summary>
/// 
/// </summary>
public enum CharacterOpcode : byte
{
    /// <summary>
    /// Request
    /// </summary>
    CreateReq = 0x01,

    /// <summary>
    /// Request
    /// </summary>
    DeleteReq = 0x02,

    /// <summary>
    /// 
    /// </summary>
    DeleteRes = 0x03,

    /// <summary>
    /// 
    /// </summary>
    KickOut = 0x04,

    /// <summary>
    /// 
    /// </summary>
    PacketStepCheck = 0x05,

    /// <summary>
    /// 
    /// </summary>
    ChangeSlot = 0x06,

    /// <summary>
    /// 
    /// </summary>
    UpdateAwaken = 0x07,

    /// <summary>
    /// 
    /// </summary>
    UpdateFreeRevive = 0x08,

    /// <summary>
    /// 
    /// </summary>
    ProfilePhotoLoad = 0x09,

    /// <summary>
    /// 
    /// </summary>
    ProfilePhotoUpdate = 0x0a,

    /// <summary>
    /// 
    /// </summary>
    ProfilePhotoFavorite = 0x0b,

    /// <summary>
    /// 
    /// </summary>
    ProfilePhotoChange = 0x0c,

    /// <summary>
    /// 
    /// </summary>
    RepresentativeCheck = 0x0d,

    /// <summary>
    /// 
    /// </summary>
    RepresentativeChange = 0x0f,

    /// <summary>
    /// Request
    /// </summary>
    ListReq = 0x11,

    /// <summary>
    /// 
    /// </summary>
    ListRes = 0x12,

    /// <summary>
    /// Request
    /// </summary>
    SelectReq = 0x13,

    /// <summary>
    /// 
    /// </summary>
    SelectRes = 0x14,

    /// <summary>
    /// 
    /// </summary>
    EnterPrologue = 0x15,

    /// <summary>
    /// 
    /// </summary>
    EnterBattleZone = 0x16,

    /// <summary>
    /// Request
    /// </summary>
    SecondPassword = 0x17,

    /// <summary>
    /// Request
    /// </summary>
    TradePassword = 0x18,

    /// <summary>
    /// Request
    /// </summary>
    UpdateCutscene = 0x19,

    /// <summary>
    /// 
    /// </summary>
    PlayCutscene = 0x20,

    /// <summary>
    /// Request
    /// </summary>
    EnterGameServerReq = 0x21,

    /// <summary>
    /// 
    /// </summary>
    EnterGameServerRes = 0x22,

    /// <summary>
    /// Request
    /// </summary>
    LoadTitle = 0x23,

    /// <summary>
    /// 
    /// </summary>
    AddTitle = 0x24,

    /// <summary>
    /// Request
    /// </summary>
    UpdateTitle = 0x25,

    /// <summary>
    /// 
    /// </summary>
    UpdateTitleBt = 0x26,

    /// <summary>
    /// 
    /// </summary>
    ClearTitle = 0x27,

    /// <summary>
    /// 
    /// </summary>
    DeleteTitle = 0x28,

    /// <summary>
    /// 
    /// </summary>
    UpdateOpenTitle = 0x29,

    /// <summary>
    /// 
    /// </summary>
    FavoriteTitle = 0x2a,

    /// <summary>
    /// 
    /// </summary>
    ChangeBackground = 0x2c,

    /// <summary>
    /// 
    /// </summary>
    AddBackground = 0x2b,

    /// <summary>
    /// 
    /// </summary>
    DbLoadSync = 0x30,

    /// <summary>
    /// Request
    /// </summary>
    InfoReq = 0x31,

    /// <summary>
    /// 
    /// </summary>
    InfoRes = 0x32,

    /// <summary>
    /// 
    /// </summary>
    SaveReq = 0x33,

    /// <summary>
    /// 
    /// </summary>
    UpdateStatList = 0x34,

    /// <summary>
    /// 
    /// </summary>
    UpdateStat = 0x35,

    /// <summary>
    /// 
    /// </summary>
    Level = 0x36,

    /// <summary>
    /// 
    /// </summary>
    Exp = 0x37,

    /// <summary>
    /// 
    /// </summary>
    Money = 0x38,

    /// <summary>
    /// 
    /// </summary>
    HeartBeat = 0x39,

    /// <summary>
    /// 
    /// </summary>
    CheckEnterMaze = 0x40,

    /// <summary>
    /// 
    /// </summary>
    Die = 0x41,

    /// <summary>
    /// Request
    /// </summary>
    ReviveReq = 0x42,

    /// <summary>
    /// 
    /// </summary>
    ReviveRes = 0x43,

    /// <summary>
    /// 
    /// </summary>
    ReviveBt = 0x44,

    /// <summary>
    /// Request
    /// </summary>
    ChangeMotionReq = 0x45,

    /// <summary>
    /// 
    /// </summary>
    ChangeMotionBt = 0x46,

    /// <summary>
    /// 
    /// </summary>
    UpdateSpecialOptionList = 0x47,

    /// <summary>
    /// 
    /// </summary>
    ReserveReviveBt = 0x48,

    /// <summary>
    /// 
    /// </summary>
    ReserveReviveReq = 0x49,

    /// <summary>
    /// 
    /// </summary>
    UpdateOriginStat = 0x51,

    /// <summary>
    /// 
    /// </summary>
    UpdateEchelonInfo = 0x52,

    /// <summary>
    /// 
    /// </summary>
    UpdateEchelonBt = 0x53,

    /// <summary>
    /// 
    /// </summary>
    UpdateNetcafe = 0x54,

    /// <summary>
    /// 
    /// </summary>
    CheckName = 0x57,

    /// <summary>
    /// 
    /// </summary>
    UpdateSharePoint = 0x58,

    /// <summary>
    /// 
    /// </summary>
    ResetSharePoint = 0x59,

    /// <summary>
    /// Request
    /// </summary>
    GobackLobby = 0x60,

    /// <summary>
    /// 
    /// </summary>
    LoadDistrictState = 0x61,

    /// <summary>
    /// 
    /// </summary>
    LoadMazeState = 0x62,

    /// <summary>
    /// Request
    /// </summary>
    GetRewardSharePoint = 0x63,

    /// <summary>
    /// 
    /// </summary>
    FpUpdate = 0x64,

    /// <summary>
    /// 
    /// </summary>
    NpcCreditLoad = 0x65,

    /// <summary>
    /// 
    /// </summary>
    NpcCreditUpdate = 0x66,

    /// <summary>
    /// 
    /// </summary>
    NpcCreditInit = 0x67,

    /// <summary>
    /// 
    /// </summary>
    OtherInfoRefuse = 0x68,

    /// <summary>
    /// 
    /// </summary>
    AchieveSelect = 0x70,

    /// <summary>
    /// 
    /// </summary>
    AchieveUpdate = 0x71,

    /// <summary>
    /// 
    /// </summary>
    AchieveComplete = 0x72,

    /// <summary>
    /// 
    /// </summary>
    AchieveReset = 0x73,

    /// <summary>
    /// Request
    /// </summary>
    AchieveReward = 0x74,

    /// <summary>
    /// Request
    /// </summary>
    OtherInfo = 0x75,

    /// <summary>
    /// 
    /// </summary>
    ClassScene = 0x76,

    /// <summary>
    /// Request
    /// </summary>
    Community = 0x77,

    /// <summary>
    /// 
    /// </summary>
    LeagueWithdrawPenalty = 0x78,

    /// <summary>
    /// 
    /// </summary>
    LeagueDeletePenalty = 0x79,

    /// <summary>
    /// 
    /// </summary>
    EqualizerUpdate = 0x7a,

    /// <summary>
    /// 
    /// </summary>
    CashMileageInfo = 0x7b,
}
