// <auto-generated>

namespace OpenWorker.GameServer.SoulWorker.Network.DataTypes.Enums.Opcodes;

/// <summary>
/// 
/// </summary>
public enum ChatOpcode : byte
{
    /// <summary>
    /// Unused
    /// </summary>
    Null = 0x00,

    /// <summary>
    /// Request, Response
    /// </summary>
    Normal = 0x01,

    /// <summary>
    /// Request, Response
    /// </summary>
    Whisper = 0x02,

    /// <summary>
    /// Request, Response
    /// </summary>
    Trade = 0x03,

    /// <summary>
    /// Response
    /// </summary>
    Notice = 0x04,

    /// <summary>
    /// Response
    /// </summary>
    Notify = 0x05,

    /// <summary>
    /// Request, Response
    /// </summary>
    Megaphone = 0x06,

    /// <summary>
    /// Response
    /// </summary>
    Memory = 0x07,

    /// <summary>
    /// Unused
    /// </summary>
    NoticeEx = 0x08,

    /// <summary>
    /// Request
    /// </summary>
    GmCommand = 0x0a,
}
