// <auto-generated>

namespace OpenWorker.GameServer.SoulWorker.Network.DataTypes.Enums.Opcodes;

/// <summary>
/// 
/// </summary>
public enum DailyMissionOpcode : byte
{
    /// <summary>
    /// Unused
    /// </summary>
    Null = 0x0,

    /// <summary>
    /// Response
    /// </summary>
    List = 0x01,

    /// <summary>
    /// Request, Response
    /// </summary>
    Accept = 0x02,

    /// <summary>
    /// Response
    /// </summary>
    Update = 0x03,

    /// <summary>
    /// Request, Response
    /// </summary>
    Helper = 0x04,

    /// <summary>
    /// Unused
    /// </summary>
    InitAll = 0x05,

    /// <summary>
    /// Unused
    /// </summary>
    End = 0x80,
}
