// <auto-generated>

namespace OpenWorker.GameServer.SoulWorker.Network.DataTypes.Enums.Opcodes;

/// <summary>
/// 
/// </summary>
public enum DropOpcode : byte
{
    /// <summary>
    /// 
    /// </summary>
    Infos = 0x01,

    /// <summary>
    /// 
    /// </summary>
    PickUp = 0x02,

    /// <summary>
    /// 
    /// </summary>
    Delete = 0x03,
}
