// <auto-generated>

namespace OpenWorker.GameServer.SoulWorker.Network.DataTypes.Enums.Opcodes;

/// <summary>
/// 
/// </summary>
public enum EventOpcode : byte
{
    /// <summary>
    /// Response 
    /// </summary>
    AttendanceLoad = 0x1,
        
    /// <summary>
    /// Request, Response
    /// </summary>
    AttendanceReward = 0x2,
    
    /// <summary>
    /// Response 
    /// </summary>
    AttendanceNotice = 0x3,
    
    /// <summary>
    /// Response 
    /// </summary>
    AttendancePlayTimeInit = 0x4,
    
    /// <summary>
    /// Request, Response
    /// </summary>
    AttendancePlayTimeReward = 0x5,
    
    /// <summary>
    /// Response 
    /// </summary>
    LuaValues = 0x20
}
