// <auto-generated>

namespace OpenWorker.GameServer.SoulWorker.Network.DataTypes.Enums.Opcodes;

/// <summary>
/// 
/// </summary>
public enum ExchangeOpcode : byte
{
    /// <summary>
    /// 
    /// </summary>
    Search = 0x1,

    /// <summary>
    /// 
    /// </summary>
    PriceHistory = 0x2,

    /// <summary>
    /// 
    /// </summary>
    InterestList = 0x3,

    /// <summary>
    /// 
    /// </summary>
    InterestItem = 0x4,

    /// <summary>
    /// 
    /// </summary>
    SellRegister = 0x5,

    /// <summary>
    /// 
    /// </summary>
    ItemBuy = 0x6,

    /// <summary>
    /// 
    /// </summary>
    ItemRecall = 0x7,

    /// <summary>
    /// 
    /// </summary>
    MyList = 0x8,
}