// <auto-generated>

namespace OpenWorker.GameServer.SoulWorker.Network.DataTypes.Enums.Opcodes;

/// <summary>
///
/// </summary>
public enum FriendOpcode : byte
{
    /// <summary>
    /// [GameServer] Unused
    /// </summary>
    Null = 0x0,

    /// <summary>
    /// Request, Response
    /// </summary>
    Load = 0x1,

    /// <summary>
    /// Request, Response
    /// </summary>
    LoadBlocklist = 0x2,

    /// <summary>
    /// Request, Response
    /// </summary>
    Invite = 0x11,

    /// <summary>
    /// Response
    /// </summary>
    InviteReq = 0x12,

    /// <summary>
    /// Request, Response
    /// </summary>
    InviteAccept = 0x13,

    /// <summary>
    /// Response
    /// </summary>
    Add = 0x14,

    /// <summary>
    /// Request, Response
    /// </summary>
    Delete = 0x15,

    /// <summary>
    /// Request, Response
    /// </summary>
    BlockAdd = 0x21,

    /// <summary>
    /// Request, Response
    /// </summary>
    BlockDel = 0x22,

    /// <summary>
    /// Response
    /// </summary>
    UpdateInfo = 0x31,

    /// <summary>
    /// Request, Response
    /// </summary>
    Info = 0x32,

    /// <summary>
    /// Request, Response
    /// </summary>
    Find = 0x33,

    /// <summary>
    /// Request, Response
    /// </summary>
    RecruitList = 0x41,

    /// <summary>
    /// Request, Response
    /// </summary>
    RecruitAdd = 0x42,

    /// <summary>
    /// Request, Response
    /// </summary>
    RecruitDel = 0x43,

    /// <summary>
    /// Request, Response
    /// </summary>
    RecruitInfo = 0x44,

    /// <summary>
    /// Request, Response
    /// </summary>
    RecommendList = 0x51,

    /// <summary>
    /// [GameServer] Unused
    /// </summary>
    Message = 0x61,

    /// <summary>
    /// [GameServer] Unused
    /// </summary>
    Clear = 0x62,

    /// <summary>
    /// [GameServer] Unused
    /// </summary>
    ClearBlocklist = 0x63,

    /// <summary>
    /// [GameServer] Unused
    /// </summary>
    End = 0x80,
}