// <auto-generated>

namespace OpenWorker.GameServer.SoulWorker.Network.DataTypes.Enums.Opcodes;

/// <summary>
/// 
/// </summary>
public enum GestureOpcode : byte
{
    /// <summary>
    /// Request, Response
    /// </summary>
    Show = 0x1,

    /// <summary>
    /// Response
    /// </summary>
    SlotLoad = 0x2,

    /// <summary>
    /// Request, Response
    /// </summary>
    SlotUpdate = 0x3,
}
