// <auto-generated>

namespace OpenWorker.GameServer.SoulWorker.Network.DataTypes.Enums.Opcodes;

/// <summary>
/// 
/// </summary>
public enum GroupOpcode : byte
{
    /// <summary>
    ///
    /// </summary>
    System = 0x01,

    /// <summary>
    /// 
    /// </summary>
    Login = 0x02,

    /// <summary>
    ///
    /// </summary>
    Character = 0x03,

    /// <summary>
    /// 
    /// </summary>
    World = 0x04,

    /// <summary>
    ///
    /// </summary>
    Move = 0x05,

    /// <summary>
    /// 
    /// </summary>
    Skill = 0x06,

    /// <summary>
    /// 
    /// </summary>
    Chat = 0x07,

    /// <summary>
    /// 
    /// </summary>
    Item = 0x08,

    /// <summary>
    /// 
    /// </summary>
    Shop = 0x09,

    /// <summary>
    /// 
    /// </summary>
    Trade = 0x0a,

    /// <summary>
    /// 
    /// </summary>
    Maze = 0x11,

    /// <summary>
    /// 
    /// </summary>
    Party = 0x12,

    /// <summary>
    /// 
    /// </summary>
    ItemUpgrade = 0x13,

    /// <summary>
    /// 
    /// </summary>
    Drop = 0x14,

    /// <summary>
    /// 
    /// </summary>
    Quest = 0x15,

    /// <summary>
    /// 
    /// </summary>
    Option = 0x16,

    /// <summary>
    /// 
    /// </summary>
    Monster = 0x17,

    /// <summary>
    /// 
    /// </summary>
    ItemSetup = 0x18,

    /// <summary>
    /// 
    /// </summary>
    Friend = 0x19,

    /// <summary>
    /// 
    /// </summary>
    Post = 0x20,

    /// <summary>
    /// 
    /// </summary>
    SoulMetry = 0x21,

    /// <summary>
    /// 
    /// </summary>
    League = 0x22,

    /// <summary>
    /// 
    /// </summary>
    Gesture = 0x23,

    /// <summary>
    /// 
    /// </summary>
    DailyMission = 0x24,

    /// <summary>
    /// 
    /// </summary>
    Vaccum = 0x25,

    /// <summary>
    /// 
    /// </summary>
    MyRoom = 0x26,

    /// <summary>
    /// 
    /// </summary>
    Helper = 0x27,

    /// <summary>
    /// 
    /// </summary>
    InfiniteTower = 0x28,

    /// <summary>
    /// 
    /// </summary>
    Booster = 0x29,

    /// <summary>
    /// 
    /// </summary>
    Event = 0x2a,

    /// <summary>
    /// 
    /// </summary>
    Exchange = 0x2b,

    /// <summary>
    /// 
    /// </summary>
    Ranking = 0x2c,

    /// <summary>
    /// 
    /// </summary>
    SocialItem = 0x2d,

    /// <summary>
    /// 
    /// </summary>
    Force = 0x2e,

    /// <summary>
    /// 
    /// </summary>
    WorldMode = 0x30,

    /// <summary>
    /// 
    /// </summary>
    WeeklyMission = 0x32,

    /// <summary>
    /// 
    /// </summary>
    ModeMaze = 0x33,

    /// <summary>
    /// 
    /// </summary>
    Restart = 0x34,

    /// <summary>
    /// 
    /// </summary>
    Tool = 0x40,

    /// <summary>
    /// 
    /// </summary>
    Channel = 0xf1,

    /// <summary>
    /// 
    /// </summary>
    Server = 0xf2,

    /// <summary>
    /// 
    /// </summary>
    ServerUser = 0xf3,

    /// <summary>
    /// 
    /// </summary>
    ServerParty = 0xf4,

    /// <summary>
    /// 
    /// </summary>
    ServerFriend = 0xf5,

    /// <summary>
    /// 
    /// </summary>
    ServerLeague = 0xf6,

    /// <summary>
    /// 
    /// </summary>
    Monitor = 0xf7,

    /// <summary>
    /// 
    /// </summary>
    GmAgent = 0xf8,

    /// <summary>
    /// 
    /// </summary>
    ServerForce = 0xfa,

    /// <summary>
    /// 
    /// </summary>
    ServerWorldMode = 0xfb,

    /// <summary>
    /// 
    /// </summary>
    ServerModeMaze = 0xfd,
}
