// <auto-generated>

namespace OpenWorker.GameServer.SoulWorker.Network.DataTypes.Enums.Opcodes;

/// <summary>
/// 
/// </summary>
public enum ItemOpcode : byte
{
  /// <summary>
  /// Unused
  /// </summary>
  Null = 0x0,

  /// <summary>
  /// Request, Response
  /// </summary>
  InventoryInfo = 0x1,

  /// <summary>
  /// Request, Response
  /// </summary>
  Move = 0x2,

  /// <summary>
  /// Request, Response
  /// </summary>
  Combine = 0x3,

  /// <summary>
  /// Request, Response
  /// </summary>
  Divide = 0x4,

  /// <summary>
  /// Request, Response
  /// </summary>
  Break = 0x5,

  /// <summary>
  /// Response
  /// </summary>
  Create = 0x6,

  /// <summary>
  /// Response
  /// </summary>
  MoveBt = 0xD,

  /// <summary>
  /// Response
  /// </summary>
  OpenSlotInfo = 0xE,

  /// <summary>
  /// Request, Response
  /// </summary>
  AddSlot = 0xF,

  /// <summary>
  /// Request, Response
  /// </summary>
  BankInfo = 0x10,

  /// <summary>
  /// Request, Response
  /// </summary>
  Use = 0x11,

  /// <summary>
  /// Response
  /// </summary>
  Reduce = 0x12,

  /// <summary>
  /// Response
  /// </summary>
  UseBt = 0x13,

  /// <summary>
  /// Response
  /// </summary>
  EquipSlotOpen = 0x14,

  /// <summary>
  /// Response
  /// </summary>
  Update = 0x15,

  /// <summary>
  /// Response
  /// </summary>
  UpdateInvenMoney = 0x20,

  /// <summary>
  /// Unused
  /// </summary>
  UpdateBankMoney = 0x21,

  /// <summary>
  /// Unused
  /// </summary>
  MoveMoneyToBankReq = 0x22,

  /// <summary>
  /// Unused
  /// </summary>
  MoveMoneyToInvenReq = 0x23,

  /// <summary>
  /// Unused
  /// </summary>
  MoveMoney = 0x24,

  /// <summary>
  /// Request, Response
  /// </summary>
  LineUp = 0x25,

  /// <summary>
  /// Response
  /// </summary>
  LoadQuickSlot = 0x26,

  /// <summary>
  /// Request, Response
  /// </summary>
  UpdateQuickSlotCard = 0x27,

  /// <summary>
  /// Request, Response
  /// </summary>
  UpdateQuickslotItem = 0x28,

  /// <summary>
  /// Response
  /// </summary>
  UpdateBp = 0x31,

  /// <summary>
  /// Response
  /// </summary>
  UpdateEther = 0x32,

  /// <summary>
  /// Response
  /// </summary>
  UpdateCash = 0x33,

  /// <summary>
  /// Response
  /// </summary>
  UpdateFriendPoint = 0x34,

  /// <summary>
  /// Request, Response
  /// </summary>
  MazeRewardItem = 0x47,

  /// <summary>
  /// Response
  /// </summary>
  UseInfoList = 0x48,

  /// <summary>
  /// Response
  /// </summary>
  UseInfoUpdate = 0x49,

  /// <summary>
  /// Response
  /// </summary>
  CubeReq = 0x4A,

  /// <summary>
  /// Response
  /// </summary>
  AppearanceLoad = 0x50,

  /// <summary>
  /// Unused
  /// </summary>
  AppearanceEnd = 0x51,

  /// <summary>
  /// Request, Response
  /// </summary>
  AppearanceEquip = 0x52,

  /// <summary>
  /// Unused
  /// </summary>
  NameChange = 0x53,

  /// <summary>
  /// Response
  /// </summary>
  SocketLoad = 0x55,

  /// <summary>
  /// Response
  /// </summary>
  BroachLoad = 0x56,

  /// <summary>
  /// Response
  /// </summary>
  AkashicRecordLoad = 0x57,

  /// <summary>
  /// Response
  /// </summary>
  AkashicRecordAdd = 0x58,

  /// <summary>
  /// Response
  /// </summary>
  Unknown1 = 0x59,

  /// <summary>
  /// Response
  /// </summary>
  Unknown2 = 0x60,

  /// <summary>
  /// Response
  /// </summary>
  SocketUpdate = 0x61,

  /// <summary>
  /// Response
  /// </summary>
  BroachUpdate = 0x62,

  /// <summary>
  /// Unused
  /// </summary>
  UpdateRecycle = 0x63,

  /// <summary>
  /// Unused
  /// </summary>
  OptionEffectBt = 0x64,

  /// <summary>
  /// Unused
  /// </summary>
  UseAppearance = 0x65,

  /// <summary>
  /// Unused
  /// </summary>
  CoolTimeInfo = 0x66,

  /// <summary>
  /// Unused
  /// </summary>
  UseSelect = 0x67,

  /// <summary>
  /// Unused
  /// </summary>
  MakeLimitList = 0x68,

  /// <summary>
  /// Unused
  /// </summary>
  MakeLimitUpdate = 0x69,

  /// <summary>
  /// Unused
  /// </summary>
  UseWarpRes = 0x70,

  /// <summary>
  /// Unused
  /// </summary>
  ResealPackage = 0x71,

  /// <summary>
  /// Unused
  /// </summary>
  ResealPackageInfo = 0x72,

  /// <summary>
  /// Unused
  /// </summary>
  DeckPageOpen = 0x73,

  /// <summary>
  /// Unused
  /// </summary>
  End = 0x80,
}
