// <auto-generated>

namespace OpenWorker.GameServer.SoulWorker.Network.DataTypes.Enums.Opcodes;

/// <summary>
/// 
/// </summary>
public enum ItemSetupOpcode : byte
{
    /// <summary>
    /// Request
    /// </summary>
    Make = 0x1,

    /// <summary>
    /// Request
    /// </summary>
    Upgrade = 0x2,

    /// <summary>
    /// Request
    /// </summary>
    Exchange = 0x3,

    /// <summary>
    /// Request
    /// </summary>
    Disassemble = 0x4,

    /// <summary>
    /// Request
    /// </summary>
    SocketEquip = 0x5,

    /// <summary>
    /// Request
    /// </summary>
    SocketActive = 0x6,

    /// <summary>
    /// Request
    /// </summary>
    SocketDetach = 0x7,

    /// <summary>
    /// Request
    /// </summary>
    Repair = 0x8,

    /// <summary>
    /// Request
    /// </summary>
    RepairNpc = 0x9,

    /// <summary>
    /// Request
    /// </summary>
    RepairEquip = 0x10,

    /// <summary>
    /// Request
    /// </summary>
    RepairAll = 0x11,

    /// <summary>
    /// Request
    /// </summary>
    Endurance = 0x12,

    /// <summary>
    /// Request
    /// </summary>
    Evolution = 0x13,

    /// <summary>
    /// Request
    /// </summary>
    AkashicMake = 0x14,

    /// <summary>
    /// Request
    /// </summary>
    AkashicDisassemble = 0x15,

    /// <summary>
    /// Request
    /// </summary>
    UpgradeLimit = 0x16,

    /// <summary>
    /// Request
    /// </summary>
    AkashicCompose = 0x17,

    /// <summary>
    /// Request
    /// </summary>
    DisassembleEx = 0x18,

    /// <summary>
    /// Request
    /// </summary>
    BroachEquip = 0x20,

    /// <summary>
    /// Request
    /// </summary>
    BroachActive = 0x21,

    /// <summary>
    /// Request
    /// </summary>
    Restore = 0x22,

    /// <summary>
    /// Request
    /// </summary>
    BroachCompose = 0x23,

    /// <summary>
    /// Request
    /// </summary>
    Unseal = 0x24,

    /// <summary>
    /// Request
    /// </summary>
    AkashicMakeEx = 0x25,

    /// <summary>
    /// Request
    /// </summary>
    UseEffect = 0x26,

    /// <summary>
    /// Request
    /// </summary>
    Renovate = 0x27,

    /// <summary>
    /// Request
    /// </summary>
    BroachRemove = 0x28,

    /// <summary>
    /// Request
    /// </summary>
    Refine = 0x29,

    /// <summary>
    /// Request
    /// </summary>
    SocketExchange = 0x30,

    /// <summary>
    /// Request
    /// </summary>
    SocketUpgrade = 0x31,

    /// <summary>
    /// Request
    /// </summary>
    SocketExtract = 0x32,

    /// <summary>
    /// Request
    /// </summary>
    AkashicComposeEx = 0x33,

    /// <summary>
    /// Request
    /// </summary>
    AkashicGetInfoAdd = 0x34,

    /// <summary>
    /// Request
    /// </summary>
    AkashicGetInfoLoad = 0x35,

    /// <summary>
    /// Request
    /// </summary>
    Dye = 0x36,

    /// <summary>
    /// Request
    /// </summary>
    TitleChange = 0x37,

    /// <summary>
    /// 
    /// </summary>
    RenovateComplete = 0x38,

    /// <summary>
    /// 
    /// </summary>
    BroachRemoveEx = 0x39
}
