// <auto-generated>

namespace OpenWorker.GameServer.SoulWorker.Network.DataTypes.Enums.Opcodes;

/// <summary>
/// 
/// </summary>
public enum LeagueOpcode : byte
{
    /// <summary>
    /// Request, Response
    /// </summary>
    Create = 0x1,
    
    /// <summary>
    /// Request, Response
    /// </summary>
    Delete = 0x2,
    
    /// <summary>
    /// Request, Response
    /// </summary>
    List = 0x3,
    
    /// <summary>
    /// Request
    /// </summary>
    Applicant = 0x5,
    
    /// <summary>
    /// Response
    /// </summary>
    Info = 0x7,
    
    /// <summary>
    /// Request, Response
    /// </summary>
    Board = 0x8,
    
    /// <summary>
    /// Request, Response
    /// </summary>
    Withdraw = 0x9,
    
    /// <summary>
    /// Response
    /// </summary>
    Delegate = 0xA,
    
    /// <summary>
    /// Request, Response
    /// </summary>
    Kick = 0xF,
    
    /// <summary>
    /// Request, Response
    /// </summary>
    Invite = 0x13,
    
    /// <summary>
    /// Request, Response
    /// </summary>
    InviteAccept = 0x14,
    
    /// <summary>
    /// Request, Response
    /// </summary>
    InviteReject = 0x15,
    
    /// <summary>
    /// Response
    /// </summary>
    JoinUser = 0x17,
    
    /// <summary>
    /// Request
    /// </summary>
    ApplicantAccept = 0x18,
    
    /// <summary>
    /// Request
    /// </summary>
    ApplicantReject = 0x19,
    
    /// <summary>
    /// Request, Response
    /// </summary>
    Search = 0x20,
    
    /// <summary>
    /// Request, Response
    /// </summary>
    OverlapName = 0x21,
    
    /// <summary>
    /// Response
    /// </summary>
    MemberUpdate = 0x22,
    
    /// <summary>
    /// Response
    /// </summary>
    ApplicantRes = 0x23,
    
    /// <summary>
    /// Response
    /// </summary>
    ApplicantAdd = 0x24,
    
    /// <summary>
    /// Response
    /// </summary>
    ApplicantRejectRes = 0x25,
    
    /// <summary>
    /// Response
    /// </summary>
    ApplicantDelete = 0x26,
    
    /// <summary>
    /// Response
    /// </summary>
    WithdrawRes = 0x27,
    
    /// <summary>
    /// Response
    /// </summary>
    KickRes = 0x28,
    
    /// <summary>
    /// Request, Response
    /// </summary>
    NoticeChange = 0x29,
    
    /// <summary>
    /// Unused
    /// </summary>
    NameChange = 0x30,
    
    /// <summary>
    /// Unused
    /// </summary>
    CardChange = 0x31,
    
    /// <summary>
    /// Request, Response
    /// </summary>
    AuthChange = 0x32,
    
    /// <summary>
    /// Request, Response
    /// </summary>
    PositionNameChange = 0x33,
    
    /// <summary>
    /// Response
    /// </summary>
    PositionNameChangeRes = 0x34,
    
    /// <summary>
    /// Response
    /// </summary>
    AuthChangeRes = 0x35,
    
    /// <summary>
    /// Response
    /// </summary>
    NoticeChangeRes = 0x36,
    
    /// <summary>
    /// Unused
    /// </summary>
    InviteRes = 0x37,
    
    /// <summary>
    /// Unused
    /// </summary>
    BoardRes = 0x38,
    
    /// <summary>
    /// Request
    /// </summary>
    MemberPositionChange = 0x39,
    
    /// <summary>
    /// , Response
    /// </summary>
    MemberLeave = 0x41,
    
    /// <summary>
    /// Unused
    /// </summary>
    MemberPositionChangeRes = 0x42,
    
    /// <summary>
    /// Response
    /// </summary>
    InfoUpdate = 0x43,
    
    /// <summary>
    /// Response
    /// </summary>
    InfoAlert = 0x44,
    
    /// <summary>
    /// Response
    /// </summary>
    CreateRes = 0x45,
    
    /// <summary>
    /// Request, Response
    /// </summary>
    OpenOrNot = 0x46,
    
    /// <summary>
    /// Request, Response
    /// </summary>
    RecruitNotice = 0x47,
    
    /// <summary>
    /// Unused
    /// </summary>
    RecordUpdate = 0x48,
    
    /// <summary>
    /// Unused
    /// </summary>
    DelegateRes = 0x49,
    
    /// <summary>
    /// Unused
    /// </summary>
    CardChangeRes = 0x50,
    
    /// <summary>
    /// Unused
    /// </summary>
    Exp = 0x51,
    
    /// <summary>
    /// Unused
    /// </summary>
    Levleup = 0x52,
    
    /// <summary>
    /// Unused
    /// </summary>
    SkillLearn = 0x53,
    
    /// <summary>
    /// Unused
    /// </summary>
    InventoryMove = 0x54,
    
    /// <summary>
    /// Unused
    /// </summary>
    InventoryInfo = 0x56,
    
    /// <summary>
    /// Unused
    /// </summary>
    InventoryMoveCast = 0x57,
    
    /// <summary>
    /// Unused
    /// </summary>
    NameChangeRes = 0x58,
}
