// <auto-generated>

namespace OpenWorker.GameServer.SoulWorker.Network.DataTypes.Enums.Opcodes;

/// <summary>
///
/// </summary>
public enum LoginOpcode : byte
{
    /// <summary>
    /// Request
    /// </summary>
    Req = 0x01,

    /// <summary>
    /// Response
    /// </summary>
    Result = 0x02,

    /// <summary>
    /// Request
    /// </summary>
    ServerListReq = 0x03,

    /// <summary>
    /// Response
    /// </summary>
    ServerList = 0x04,

    /// <summary>
    /// Request
    /// </summary>
    ServerConnectReq = 0x05,

    /// <summary>
    /// Unused
    /// </summary>
    Logout = 0x06,

    /// <summary>
    /// Response
    /// </summary>
    EnterServer = 0x11,

    /// <summary>
    /// Request
    /// </summary>
    EnterServerReq = 0x13,

    /// <summary>
    /// Response
    /// </summary>
    EnterServerRes = 0x14,

    /// <summary>
    /// Request
    /// </summary>
    FromNextHumanNetwork = 0x15,

    /// <summary>
    /// Unused
    /// </summary>
    ForSega = 0x16,

    /// <summary>
    /// Unused
    /// </summary>
    ForSg = 0x17,

    /// <summary>
    /// Unused
    /// </summary>
    ForGameForge = 0x18,

    /// <summary>
    /// Unused
    /// </summary>
    ForTwn = 0x19,

    /// <summary>
    /// Unused
    /// </summary>
    ForWm = 0x20,

    /// <summary>
    /// Unused
    /// </summary>
    ForChn = 0x21,

    /// <summary>
    /// Unused
    /// </summary>
    ForSteam = 0x22,

    /// <summary>
    /// Response
    /// </summary>
    OptionLoad = 0x31,

    /// <summary>
    /// Request
    /// </summary>
    OptionUpdate = 0x32,

    /// <summary>
    /// Unused
    /// </summary>
    MobileAuth = 0x33,

    /// <summary>
    /// Unused
    /// </summary>
    EnterWaitCheck = 0x34,

    /// <summary>
    /// Unused
    /// </summary>
    EnterWaitCancel = 0x35,
}