// <auto-generated>

namespace OpenWorker.GameServer.SoulWorker.Network.DataTypes.Enums.Opcodes;

/// <summary>
/// 
/// </summary>
public enum MoveOpcode : byte
{
    /// <summary>
    /// Unused
    /// </summary>
    None = 0x00,

    /// <summary>
    /// Request
    /// </summary>
    Move = 0x01,

    /// <summary>
    /// Response
    /// </summary>
    MoveBt = 0x02,

    /// <summary>
    /// Request
    /// </summary>
    Stop = 0x03,

    /// <summary>
    /// Response
    /// </summary>
    StopBt = 0x04,

    /// <summary>
    /// Request
    /// </summary>
    Jump = 0x05,

    /// <summary>
    /// Response
    /// </summary>
    JumpBt = 0x06,

    /// <summary>
    /// Request
    /// </summary>
    Battle = 0x07,

    /// <summary>
    /// Response
    /// </summary>
    BattleBt = 0x08,

    /// <summary>
    /// Unused
    /// </summary>
    Gaze = 0x09,

    /// <summary>
    /// Response
    /// </summary>
    GazeBt = 0x0a,

    /// <summary>
    /// Response
    /// </summary>
    TraceBt = 0x0b,

    /// <summary>
    /// Response
    /// </summary>
    IdleBt = 0x0c,

    /// <summary>
    /// Response
    /// </summary>
    InfoBt = 0x0d,

    /// <summary>
    /// Response
    /// </summary>
    IdlesBt = 0x0f,

    /// <summary>
    /// Request
    /// </summary>
    Motion = 0x10,

    /// <summary>
    /// Response
    /// </summary>
    MotionBt = 0x11,

    /// <summary>
    /// Response
    /// </summary>
    StiffenBt = 0x12,

    /// <summary>
    /// Request, Response
    /// </summary>
    IgnoreMotionDelta = 0x13,

    /// <summary>
    /// Response
    /// </summary>
    UpdateDir = 0x14,

    /// <summary>
    /// Response
    /// </summary>
    Drop = 0x15,

    /// <summary>
    /// Request, Response
    /// </summary>
    TransportTake = 0x16,

    /// <summary>
    /// Request, Response
    /// </summary>
    TransportOff = 0x17,

    /// <summary>
    /// Response
    /// </summary>
    Grap = 0x20,

    /// <summary>
    /// Request, Response
    /// </summary>
    Rotation = 0x21,

    /// <summary>
    /// Request
    /// </summary>
    Position = 0x22,

    /// <summary>
    /// Request
    /// </summary>
    LoopMotionStart = 0x30,

    /// <summary>
    /// Response
    /// </summary>
    LoopMotionStartBt = 0x31,

    /// <summary>
    /// Request
    /// </summary>
    LoopMotionEnd = 0x32,

    /// <summary>
    /// Response
    /// </summary>
    LoopMotionEndBt = 0x33,

    /// <summary>
    /// Response
    /// </summary>
    AttacedBt = 0x34,

    /// <summary>
    /// Response
    /// </summary>
    AttacedEndBt = 0x35,

    /// <summary>
    /// Request
    /// </summary>
    AttacedEnd = 0x36,

    /// <summary>
    /// Request
    /// </summary>
    GroundStatus = 0x40,

    /// <summary>
    /// Request
    /// </summary>
    JumpQuickDown = 0x50,
}
