// <auto-generated>

namespace OpenWorker.GameServer.SoulWorker.Network.DataTypes.Enums.Opcodes;

/// <summary>
///
/// </summary>
public enum PartyOpcode : byte
{
    /// <summary>
    /// Request, Response (Normal)
    /// </summary>
    Invite = 0x1,

    /// <summary>
    /// Request, Response (Unnamed)
    /// </summary>
    Accept = 0x2,

    /// <summary>
    /// Request, Response (Normal)
    /// </summary>
    ChangeMaster = 0x3,

    /// <summary>
    /// Request
    /// </summary>
    KickOut = 0x4,

    /// <summary>
    /// Request, Response (Normal)
    /// </summary>
    Leave = 0x5,

    /// <summary>
    /// Response (Normal)
    /// </summary>
    UpdateMemberInfo = 0x6,

    /// <summary>
    /// Response (Normal)
    /// </summary>
    Delete = 0x7,

    /// <summary>
    /// Request, Response (Unnamed)
    /// </summary>
    Cancel = 0x8,

    /// <summary>
    /// Request, Response
    /// </summary>
    UpdateInfo = 0x9,

    /// <summary>
    /// Response
    /// </summary>
    AddMember = 0x10,

    /// <summary>
    ///
    /// </summary>
    RemoveMember = 0x11,

    /// <summary>
    /// Response
    /// </summary>
    UpdateMemberHp = 0x12,

    /// <summary>
    /// Response (defined but not implemented)
    /// </summary>
    UpdateMemberSg = 0x13,

    /// <summary>
    ///
    /// </summary>
    Message = 0x20,

    /// <summary>
    /// Request, Response
    /// </summary>
    MatchingEnter = 0x30,

    /// <summary>
    /// Request, Response
    /// </summary>
    MatchingExit = 0x31,

    /// <summary>
    /// Request, Response
    /// </summary>
    MatchingCheck = 0x32,

    /// <summary>
    /// Response
    /// </summary>
    MatchingReset = 0x33,

    /// <summary>
    /// Response
    /// </summary>
    MatchingWait = 0x34,

    /// <summary>
    /// Response (renamed)
    /// </summary>
    RecruitPenalty = 0x35,

    /// <summary>
    /// Request, Response
    /// </summary>
    RecruitList = 0x36,

    /// <summary>
    /// Request, Response
    /// </summary>
    RecruitAdd = 0x37,

    /// <summary>
    /// Request, Response
    /// </summary>
    RecruitApply = 0x38,

    /// <summary>
    /// Request, Response
    /// </summary>
    RecruitApplyAccept = 0x39,

    /// <summary>
    /// Response
    /// </summary>
    RecruitApplyReject = 0x3A,

    /// <summary>
    /// Request, Response
    /// </summary>
    RecruitApplyUpdate = 0x3B,

    /// <summary>
    /// Request, Response
    /// </summary>
    RecruitDel = 0x3C,

    /// <summary>
    /// Response
    /// </summary>
    RecruitApplyList = 0x3D,

    /// <summary>
    /// Response
    /// </summary>
    RecruitInfo = 0x3E,

    /// <summary>
    /// Request, Response
    /// </summary>
    AwaiterAdd = 0x3F,

    /// <summary>
    /// Response
    /// </summary>
    AwaiterDel = 0x40,

    /// <summary>
    /// Request, Response
    /// </summary>
    AwaiterList = 0x41,

    /// <summary>
    /// Request, Response
    /// </summary>
    RecruitApplyInfo = 0x42,

    /// <summary>
    /// Response
    /// </summary>
    AwaiterInfo = 0x43,

    /// <summary>
    /// Response
    /// </summary>
    RecruitApplyNotice = 0x44,

    /// <summary>
    /// Response
    /// </summary>
    MazeClear = 0x45,

    /// <summary>
    /// Response
    /// </summary>
    Unknown5 = 0x46
}
