// <auto-generated>

namespace OpenWorker.GameServer.SoulWorker.Network.DataTypes.Enums.Opcodes;

/// <summary>
/// 
/// </summary>
public enum QuestOpcode : byte
{
    /// <summary>
    /// Unused
    /// </summary>
    Null = 0x0,

    /// <summary>
    /// Response
    /// </summary>
    CompleteList = 0x1,

    /// <summary>
    /// Response
    /// </summary>
    List = 0x2,

    /// <summary>
    /// Request, Response
    /// </summary>
    Accept = 0x3,

    /// <summary>
    /// Unused
    /// </summary>
    OrderComplete = 0x4,

    /// <summary>
    /// Request, Response
    /// </summary>
    EpisodeComplete = 0x5,

    /// <summary>
    /// Request, Response
    /// </summary>
    GiveUp = 0x6,

    /// <summary>
    /// Response
    /// </summary>
    Update = 0x7,

    /// <summary>
    /// Request, Response
    /// </summary>
    EventUpdate = 0x8,

    /// <summary>
    /// Request, Response
    /// </summary>
    Helper = 0x9,

    /// <summary>
    /// Response
    /// </summary>
    Reset = 0x10,

    /// <summary>
    /// Request, Response
    /// </summary>
    Fail = 0x11,

    /// <summary>
    /// Response
    /// </summary>
    EpisodeReset = 0x12,

    /// <summary>
    /// Unused
    /// </summary>
    RepeatReset = 0x13,

    /// <summary>
    /// Unused
    /// </summary>
    End = 0x80,
}

// https://youtu.be/p-m2s6hZtGc?list=RDMM6phjA0c4sp4
