// <auto-generated>

namespace OpenWorker.GameServer.SoulWorker.Network.DataTypes.Enums.Opcodes;

/// <summary>
/// 
/// </summary>
public enum RankingOpcode : byte
{
    /// <summary>
    /// 
    /// </summary>
    TimeAttackList = 0x1,
    
    /// <summary>
    /// 
    /// </summary>
    PvpList = 0x02,
    
    /// <summary>
    /// Request, Response
    /// </summary>
    InfiniteTowerList = 0x03
}