// <auto-generated>

namespace OpenWorker.GameServer.SoulWorker.Network.DataTypes.Enums.Opcodes;

/// <summary>
/// 
/// </summary>
public enum ShopOpcode : byte
{
    /// <summary>
    /// Unused
    /// </summary>
    Null = 0x0,

    /// <summary>
    /// Request, Response
    /// </summary>
    Buy = 0x1,

    /// <summary>
    /// Request, Response
    /// </summary>
    Sell = 0x2,

    /// <summary>
    /// Request, Response
    /// </summary>
    RepurchaserList = 0x3,

    /// <summary>
    /// Request, Response
    /// </summary>
    Repurchaser = 0x4,

    /// <summary>
    /// Response
    /// </summary>
    RepurchaserAdd = 0x5,

    /// <summary>
    /// Response
    /// </summary>
    RepurchaserDelete = 0x6,

    /// <summary>
    /// Response
    /// </summary>
    ItemLoad = 0x10,

    /// <summary>
    /// Response
    /// </summary>
    ItemUpdate = 0x11,

    /// <summary>
    /// Response
    /// </summary>
    ItemInit = 0x12,

    /// <summary>
    /// Request, Response
    /// </summary>
    CashLoad = 0x20,

    /// <summary>
    /// Request, Response
    /// </summary>
    CashBuy = 0x21,

    /// <summary>
    /// Response
    /// </summary>
    CashSetLoad = 0x22,

    /// <summary>
    /// Request, Response
    /// </summary>
    CashSet = 0x23,

    /// <summary>
    /// Request, Response
    /// </summary>
    CashSetDel = 0x24,

    /// <summary>
    /// Request, Response
    /// </summary>
    CashGift = 0x25,

    /// <summary>
    /// Request
    /// </summary>
    Gacha = 0x26,

    /// <summary>
    /// Response
    /// </summary>
    GachaRes = 0x27,

    /// <summary>
    /// Response
    /// </summary>
    BannerLoad = 0x28,

    /// <summary>
    /// Unused
    /// </summary>
    CashTabLoad = 0x29,

    /// <summary>
    /// Unused
    /// </summary>
    CashUpdate = 0x2A,

    /// <summary>
    /// Unused
    /// </summary>
    CashTabUpdate = 0x2B,

    /// <summary>
    /// Unused
    /// </summary>
    CashBuyCountLoad = 0x30,

    /// <summary>
    /// Unused
    /// </summary>
    CashBuyCountUpdate = 0x31,

    /// <summary>
    /// Unused
    /// </summary>
    GetUrl = 0x32,

    /// <summary>
    /// Unused
    /// </summary>
    CashClose = 0x33,

    /// <summary>
    /// Unused
    /// </summary>
    AccountItemUpdate = 0x34,

    /// <summary>
    /// Unused
    /// </summary>
    End = 0x80,
}
