// <auto-generated>

namespace OpenWorker.GameServer.SoulWorker.Network.DataTypes.Enums.Opcodes;

/// <summary>
///
/// </summary>
public enum SkillOpcode : byte
{
    /// <summary>
    /// Request
    /// </summary>
    PassiveSkillEndReq = 0x05,

    /// <summary>
    /// Request
    /// </summary>
    PassiveSkillReq = 0x06,

    /// <summary>
    /// Response
    /// </summary>
    PassiveSkillRes = 0x07,

    /// <summary>
    /// Request
    /// </summary>
    ActiveSkillReq = 0x08,

    /// <summary>
    /// Response
    /// </summary>
    ActiveSkillRes = 0x09,

    /// <summary>
    /// Response
    /// </summary>
    ActiveSkillBt = 0x10,

    /// <summary>
    ///
    /// </summary>
    ActionSkillReq = 0x11,

    /// <summary>
    /// Response
    /// </summary>
    ActionSkillRes = 0x12,

    /// <summary>
    /// Response
    /// </summary>
    ActionSkillBt = 0x13,

    /// <summary>
    /// Response
    /// </summary>
    BuffUpdateBt = 0x14,

    /// <summary>
    /// Response
    /// </summary>
    BuffDeleteBt = 0x15,

    /// <summary>
    /// Response
    /// </summary>
    BuffChangeBt = 0x16,

    /// <summary>
    /// Response
    /// </summary>
    BuffDamageBt = 0x17,

    /// <summary>
    /// Response
    /// </summary>
    AuraUpdateBt = 0x18,

    /// <summary>
    ///
    /// </summary>
    BuffActiveBroachEffect = 0x19,

    /// <summary>
    ///
    /// </summary>
    CallOutSkillReq = 0x1a,

    /// <summary>
    ///
    /// </summary>
    CallOutSkillRes = 0x1b,

    /// <summary>
    ///
    /// </summary>
    CallOutSkillBt = 0x1c,

    /// <summary>
    /// Request
    /// </summary>
    AkashicRecordReq = 0x20,

    /// <summary>
    /// Response
    /// </summary>
    AkashicRecordRes = 0x21,

    /// <summary>
    /// Response
    /// </summary>
    AkashicRecordBt = 0x22,

    /// <summary>
    /// Request
    /// </summary>
    ProjectileReq = 0x31,

    /// <summary>
    /// Response
    /// </summary>
    ProjectileBt = 0x32,

    /// <summary>
    /// Request
    /// </summary>
    TrapPosUpdateReq = 0x33,

    /// <summary>
    /// Response
    /// </summary>
    TrapPosUpdateBt = 0x34,

    /// <summary>
    /// Response
    /// </summary>
    ProjectileAttachBt = 0x35,

    /// <summary>
    /// Request, Response
    /// </summary>
    PreTargetList = 0x36,

    /// <summary>
    /// Request
    /// </summary>
    ChainReq = 0x37,

    /// <summary>
    /// Response
    /// </summary>
    ChainBt = 0x38,

    /// <summary>
    /// Response
    /// </summary>
    ChainUpdateTarget = 0x39,

    /// <summary>
    /// Response
    /// </summary>
    ProjectileUpdateTarget = 0x3a,

    /// <summary>
    /// Response
    /// </summary>
    ProjectileRemove = 0x3b,

    /// <summary>
    ///
    /// </summary>
    CombatType = 0x3c,

    /// <summary>
    /// Request
    /// </summary>
    SkillKeypressReq = 0x41,

    /// <summary>
    /// Response
    /// </summary>
    SkillKeypressBt = 0x42,

    /// <summary>
    /// Request
    /// </summary>
    SkillTargetChangeReq = 0x43,

    /// <summary>
    /// Response
    /// </summary>
    SkillTargetChangeBt = 0x44,

    /// <summary>
    /// Request
    /// </summary>
    SkillWarpPositionReq = 0x45,

    /// <summary>
    /// Response
    /// </summary>
    SkillWarpPositionBt = 0x46,

    /// <summary>
    /// Request
    /// </summary>
    SkillSyncPositionReq = 0x47,

    /// <summary>
    /// Response
    /// </summary>
    SkillSyncPositionBt = 0x48,

    /// <summary>
    /// Response
    /// </summary>
    SkillMoveWithTimeBt = 0x49,

    /// <summary>
    /// Request
    /// </summary>
    SkillSuboInputReq = 0x4a,

    /// <summary>
    /// Response
    /// </summary>
    SkillSubInputBt = 0x4b,

    /// <summary>
    /// Request
    /// </summary>
    SkillChargingStart = 0x4c,

    /// <summary>
    /// Response
    /// </summary>
    SkillChargingStartBt = 0x4d,

    /// <summary>
    ///
    /// </summary>
    SkillChargingEnd = 0x4e,

    /// <summary>
    /// Response
    /// </summary>
    SkillChargingEndBt = 0x50,

    /// <summary>
    ///
    /// </summary>
    SkillChargingBothInputReq = 0x51,

    /// <summary>
    ///
    /// </summary>
    SkillChargingBothInputBt = 0x52,

    /// <summary>
    ///
    /// </summary>
    SkillMovingTarget = 0x53,

    /// <summary>
    ///
    /// </summary>
    DeckPageActive = 0x54,

    /// <summary>
    ///
    /// </summary>
    DeckPageName = 0x55,

    /// <summary>
    ///
    /// </summary>
    SkillDeckPageOpen = 0x56,

    /// <summary>
    /// Response
    /// </summary>
    SkillStartSoulViperBt = 0x61,

    /// <summary>
    /// Response
    /// </summary>
    SkillEndSoulViperBt = 0x62,

    /// <summary>
    /// Response
    /// </summary>
    SkillDelete = 0x63,

    /// <summary>
    ///
    /// </summary>
    SkillResetCooltime = 0x64,

    /// <summary>
    /// Response
    /// </summary>
    SkillLoadInfo = 0x70,

    /// <summary>
    /// Request, Response
    /// </summary>
    SkillLearn = 0x71,

    /// <summary>
    /// Request, Response
    /// </summary>
    SkillReset = 0x72,

    /// <summary>
    /// Response
    /// </summary>
    SkillUpdatePoint = 0x73,

    /// <summary>
    /// Response
    /// </summary>
    SkillLoadDeck = 0x74,

    /// <summary>
    /// Request, Response
    /// </summary>
    SkillUpdateDeck = 0x75,

    /// <summary>
    /// Request, Response
    /// </summary>
    SkillAddDeckSlot = 0x76,

    /// <summary>
    /// Request, Response
    /// </summary>
    SkillDivergenceLearn = 0x77,

    /// <summary>
    /// Response
    /// </summary>
    GestureQuickSlot = 0x78,

    /// <summary>
    /// Request, Response
    /// </summary>
    SkillDeckBonus = 0x79,

    /// <summary>
    /// Request, Response
    /// </summary>
    SkillResetTaget = 0x7a,

    /// <summary>
    /// Response
    /// </summary>
    SkillSummonAkashic = 0x7b,

    /// <summary>
    /// Response
    /// </summary>
    SkillCooltimeReduce = 0x7c,

    /// <summary>
    /// Response
    /// </summary>
    SkillDefenceType = 0x7d,

    /// <summary>
    ///
    /// </summary>
    PassiveSkillCooltime = 0x7e,
}
