// <auto-generated>

namespace OpenWorker.GameServer.SoulWorker.Network.DataTypes.Enums.Opcodes;

/// <summary>
/// 
/// </summary>
public enum SoulMetryOpcode : byte
{
    /// <summary>
    /// Unused
    /// </summary>
    Null = 0x0,

    /// <summary>
    /// Response
    /// </summary>
    List = 0x1,

    /// <summary>
    /// Response
    /// </summary>
    CompleteList = 0x2,

    /// <summary>
    /// Response
    /// </summary>
    Add = 0x3,

    /// <summary>
    /// Response
    /// </summary>
    Update = 0x4,

    /// <summary>
    /// Request, Response
    /// </summary>
    Complete = 0x5,

    /// <summary>
    /// Response
    /// </summary>
    Reset = 0x6,

    /// <summary>
    /// Unused
    /// </summary>
    End = 0x80,
}
