// <auto-generated>

namespace OpenWorker.GameServer.SoulWorker.Network.DataTypes.Enums.Opcodes;

/// <summary>
/// 
/// </summary>
public enum SystemOpcode : byte
{
    /// <summary>
    /// Unused
    /// </summary>
    KeyOptionUpdate = 0x01,

    /// <summary>
    /// Request
    /// </summary>
    OptionUpdate = 0x02,

    /// <summary>
    /// Request
    /// </summary>
    Xigncode = 0x03,

    /// <summary>
    /// Unused
    /// </summary>
    XigncodeError = 0x04,

    /// <summary>
    /// Request, Response
    /// </summary>
    KeepAlive = 0x05,

    /// <summary>
    /// Request, Response
    /// </summary>
    Ping = 0x06,

    /// <summary>
    /// Response
    /// </summary>
    ServerOptionUpdate = 0x07,

    /// <summary>
    /// Unused
    /// </summary>
    ClientLog = 0x08,

    /// <summary>
    /// Unused
    /// </summary>
    Event = 0x09,

    /// <summary>
    /// Unused
    /// </summary>
    Indulgence = 0x10,

    /// <summary>
    /// Unused
    /// </summary>
    SgTokenUpdate = 0x11,

    /// <summary>
    /// Unused
    /// </summary>
    GameGuardAuth = 0x12,

    /// <summary>
    /// Unused
    /// </summary>
    GameGuardError = 0x13,

    /// <summary>
    /// Unused
    /// </summary>
    TickLog = 0x21,
}
