// <auto-generated>

namespace OpenWorker.GameServer.SoulWorker.Network.DataTypes.Enums.Opcodes;

/// <summary>
/// 
/// </summary>
public enum WorldOpcode : byte
{
    /// <summary>
    /// Request
    /// </summary>
    EnterReq = 0x01,

    /// <summary>
    /// Response
    /// </summary>
    EnterRes = 0x02,

    /// <summary>
    /// Response
    /// </summary>
    CurDate = 0x03,

    /// <summary>
    /// Response
    /// </summary>
    Version = 0x04,

    /// <summary>
    /// Request
    /// </summary>
    ObjectReq = 0x06,

    /// <summary>
    /// Request
    /// </summary>
    WarpReq = 0x07,

    /// <summary>
    /// Response
    /// </summary>
    WarpRes = 0x08,

    /// <summary>
    /// Response
    /// </summary>
    WarpEnableRes = 0x09,

    /// <summary>
    /// Response
    /// </summary>
    GateEnableRes = 0x0a,

    /// <summary>
    /// Request
    /// </summary>
    CheckSectorReq = 0x0b,

    /// <summary>
    /// 
    /// </summary>
    CheckSectorRes = 0x0c,

    /// <summary>
    /// Request
    /// </summary>
    WarpOutReq = 0x0d,

    /// <summary>
    /// Response
    /// </summary>
    WarpMazeRes = 0x0e,

    /// <summary>
    /// Response
    /// </summary>
    WarpMazeTimeRes = 0x0f,

    /// <summary>
    /// Response
    /// </summary>
    InInfoPc = 0x11,

    /// <summary>
    /// Response
    /// </summary>
    OutInfoPc = 0x12,

    /// <summary>
    /// Response
    /// </summary>
    InInfoNpc = 0x13,

    /// <summary>
    /// Response
    /// </summary>
    OutInfoNpc = 0x14,

    /// <summary>
    /// Response
    /// </summary>
    InInfoMonster = 0x15,

    /// <summary>
    /// Response
    /// </summary>
    OutInfoMonster = 0x16,

    /// <summary>
    /// Response
    /// </summary>
    InInfoSpawnBox = 0x18,

    /// <summary>
    /// 
    /// </summary>
    GameOut = 0x19,

    /// <summary>
    /// Response
    /// </summary>
    OtherInfosPc = 0x21,

    /// <summary>
    /// Response
    /// </summary>
    OtherInfosNpc = 0x22,

    /// <summary>
    /// Response
    /// </summary>
    OtherInfosMonster = 0x23,

    /// <summary>
    /// Response
    /// </summary>
    OutOtherInfosPc = 0x24,

    /// <summary>
    /// 
    /// </summary>
    MoverInfoReq = 0x31,

    /// <summary>
    /// 
    /// </summary>
    EnterBattleCry = 0x32,

    /// <summary>
    /// Request
    /// </summary>
    Escape = 0x33,

    /// <summary>
    /// 
    /// </summary>
    DistrictTransportReq = 0x40,

    /// <summary>
    /// Request
    /// </summary>
    MazeCreateReq = 0x41,

    /// <summary>
    /// 
    /// </summary>
    MazeCreateRes = 0x42,

    /// <summary>
    /// 
    /// </summary>
    EnterMazeLimitCountLoad = 0x43,

    /// <summary>
    /// Response
    /// </summary>
    EnterMazeLimitCountReset = 0x44,

    /// <summary>
    /// Response
    /// </summary>
    EnterMazeLimitCountUpdate = 0x45,

    /// <summary>
    /// 
    /// </summary>
    EnterMazeLimitCountGroupLoad = 0x46,

    /// <summary>
    /// 
    /// </summary>
    EnterMazeLimitCountGroupReset = 0x47,

    /// <summary>
    /// 
    /// </summary>
    EnterMazeLimitCountGroupUpdate = 0x48,

    /// <summary>
    /// 
    /// </summary>
    EnterMapPc = 0x51,

    /// <summary>
    /// 
    /// </summary>
    ExitMapPc = 0x52,

    /// <summary>
    /// 
    /// </summary>
    ChangePacketOptimization = 0x60,

    /// <summary>
    /// 
    /// </summary>
    SkipInTutorial02Req = 0x61,
}
