# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
  branches:
    include:
    - '*'

pr:
  branches:
    include:
    - '*'

schedules:
- cron: "0 12 * * *"
  displayName: 'Daily Build'
  branches:
    include:
    - main
  
strategy:
  matrix:
    linux-Release:
      buildConfiguration: Release
      imageName: 'windows-latest'
    mac-Release:
      buildConfiguration: Release
      imageName: 'ubuntu-latest'
    windows-Release:
      buildConfiguration: Release
      imageName: 'macOS-latest'
    linux-Debug:
      buildConfiguration: Debug
      imageName: 'windows-latest'
    mac-Debug:
      buildConfiguration: Debug
      imageName: 'ubuntu-latest'
    windows-Debug:
      buildConfiguration: Debug
      imageName: 'macOS-latest'

pool:
  vmImage: $(imageName)

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: '$(solution)'
    feedsToUse: 'config'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      touch ow.Framework/config/commonsettings.json
      touch ow.Framework/config/appsettings.json
      touch ow.Framework.Tests/config/appsettings.json
      touch ow.Service.District/config/appsettings.json
      touch ow.Service.World/config/appsettings.json
      touch ow.Utils.ItemView.Generator/config/appsettings.json

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    configuration: '$(buildConfiguration)'
