// <auto-generated>

using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using OpenWorker.GameServer.SoulWorker.Network.DataTypes.Enums.Opcodes;

namespace OpenWorker.GameServer.SoulWorker.Network.DataTypes;

[StructLayout(LayoutKind.Explicit)]
public readonly struct MessageOpcode
{
    #region Properties

    [field: FieldOffset(0)]
    public byte Group { get; }

    [field: FieldOffset(1)]
    public byte Command { get; }

    #endregion Properties

    #region Internal Properties

    [field: FieldOffset(0)]
    internal short Value { get; }

    #endregion Internal Properties

    #region Operators

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static implicit operator short(MessageOpcode value) => value.Value;

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static implicit operator GroupOpcode(MessageOpcode value) => (GroupOpcode)value.Group;

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static implicit operator SystemOpcode(MessageOpcode value) => (SystemOpcode)value.Group;

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static implicit operator LoginOpcode(MessageOpcode value) => (LoginOpcode)value.Group;

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static implicit operator CharacterOpcode(MessageOpcode value) => (CharacterOpcode)value.Group;

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static implicit operator WorldOpcode(MessageOpcode value) => (WorldOpcode)value.Group;

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static implicit operator MoveOpcode(MessageOpcode value) => (MoveOpcode)value.Group;

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static implicit operator SkillOpcode(MessageOpcode value) => (SkillOpcode)value.Group;

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static implicit operator ChatOpcode(MessageOpcode value) => (ChatOpcode)value.Group;

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static implicit operator ItemOpcode(MessageOpcode value) => (ItemOpcode)value.Group;

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static implicit operator ShopOpcode(MessageOpcode value) => (ShopOpcode)value.Group;

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static implicit operator TradeOpcode(MessageOpcode value) => (TradeOpcode)value.Group;

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static implicit operator MazeOpcode(MessageOpcode value) => (MazeOpcode)value.Group;

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static implicit operator PartyOpcode(MessageOpcode value) => (PartyOpcode)value.Group;

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static implicit operator ItemUpgradeOpcode(MessageOpcode value) => (ItemUpgradeOpcode)value.Group;

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static implicit operator DropOpcode(MessageOpcode value) => (DropOpcode)value.Group;

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static implicit operator QuestOpcode(MessageOpcode value) => (QuestOpcode)value.Group;

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static implicit operator OptionOpcode(MessageOpcode value) => (OptionOpcode)value.Group;

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static implicit operator MonsterOpcode(MessageOpcode value) => (MonsterOpcode)value.Group;

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static implicit operator ItemSetupOpcode(MessageOpcode value) => (ItemSetupOpcode)value.Group;

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static implicit operator FriendOpcode(MessageOpcode value) => (FriendOpcode)value.Group;

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static implicit operator PostOpcode(MessageOpcode value) => (PostOpcode)value.Group;

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static implicit operator SoulMetryOpcode(MessageOpcode value) => (SoulMetryOpcode)value.Group;

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static implicit operator LeagueOpcode(MessageOpcode value) => (LeagueOpcode)value.Group;

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static implicit operator GestureOpcode(MessageOpcode value) => (GestureOpcode)value.Group;

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static implicit operator DailyMissionOpcode(MessageOpcode value) => (DailyMissionOpcode)value.Group;

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static implicit operator VaccumOpcode(MessageOpcode value) => (VaccumOpcode)value.Group;

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static implicit operator MyRoomOpcode(MessageOpcode value) => (MyRoomOpcode)value.Group;

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static implicit operator HelperOpcode(MessageOpcode value) => (HelperOpcode)value.Group;

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static implicit operator InfiniteTowerOpcode(MessageOpcode value) => (InfiniteTowerOpcode)value.Group;

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static implicit operator BoosterOpcode(MessageOpcode value) => (BoosterOpcode)value.Group;

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static implicit operator EventOpcode(MessageOpcode value) => (EventOpcode)value.Group;

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static implicit operator ExchangeOpcode(MessageOpcode value) => (ExchangeOpcode)value.Group;

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static implicit operator RankingOpcode(MessageOpcode value) => (RankingOpcode)value.Group;

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static implicit operator SocialItemOpcode(MessageOpcode value) => (SocialItemOpcode)value.Group;

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static implicit operator ForceOpcode(MessageOpcode value) => (ForceOpcode)value.Group;

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static implicit operator WorldModeOpcode(MessageOpcode value) => (WorldModeOpcode)value.Group;

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static implicit operator WeeklyMissionOpcode(MessageOpcode value) => (WeeklyMissionOpcode)value.Group;

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static implicit operator ModeMazeOpcode(MessageOpcode value) => (ModeMazeOpcode)value.Group;

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static implicit operator RestartOpcode(MessageOpcode value) => (RestartOpcode)value.Group;

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static implicit operator ToolOpcode(MessageOpcode value) => (ToolOpcode)value.Group;

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static implicit operator ChannelOpcode(MessageOpcode value) => (ChannelOpcode)value.Group;

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static implicit operator ServerOpcode(MessageOpcode value) => (ServerOpcode)value.Group;

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static implicit operator ServerUserOpcode(MessageOpcode value) => (ServerUserOpcode)value.Group;

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static implicit operator ServerPartyOpcode(MessageOpcode value) => (ServerPartyOpcode)value.Group;

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static implicit operator ServerFriendOpcode(MessageOpcode value) => (ServerFriendOpcode)value.Group;

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static implicit operator ServerLeagueOpcode(MessageOpcode value) => (ServerLeagueOpcode)value.Group;

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static implicit operator MonitorOpcode(MessageOpcode value) => (MonitorOpcode)value.Group;

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static implicit operator GmAgentOpcode(MessageOpcode value) => (GmAgentOpcode)value.Group;

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static implicit operator ServerForceOpcode(MessageOpcode value) => (ServerForceOpcode)value.Group;

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static implicit operator ServerWorldModeOpcode(MessageOpcode value) => (ServerWorldModeOpcode)value.Group;

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static implicit operator ServerModeMazeOpcode(MessageOpcode value) => (ServerModeMazeOpcode)value.Group;

    #endregion Operators

    #region Constructors

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public MessageOpcode(BinaryReader reader) => Value = reader.ReadInt16();

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public MessageOpcode(byte group, byte command) => (Group, Command) = (group, command);

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public MessageOpcode(GroupOpcode group, SystemOpcode command) : this((byte)group, (byte)command) { }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public MessageOpcode(GroupOpcode group, LoginOpcode command) : this((byte)group, (byte)command) { }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public MessageOpcode(GroupOpcode group, CharacterOpcode command) : this((byte)group, (byte)command) { }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public MessageOpcode(GroupOpcode group, WorldOpcode command) : this((byte)group, (byte)command) { }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public MessageOpcode(GroupOpcode group, MoveOpcode command) : this((byte)group, (byte)command) { }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public MessageOpcode(GroupOpcode group, SkillOpcode command) : this((byte)group, (byte)command) { }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public MessageOpcode(GroupOpcode group, ChatOpcode command) : this((byte)group, (byte)command) { }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public MessageOpcode(GroupOpcode group, ItemOpcode command) : this((byte)group, (byte)command) { }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public MessageOpcode(GroupOpcode group, ShopOpcode command) : this((byte)group, (byte)command) { }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public MessageOpcode(GroupOpcode group, TradeOpcode command) : this((byte)group, (byte)command) { }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public MessageOpcode(GroupOpcode group, MazeOpcode command) : this((byte)group, (byte)command) { }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public MessageOpcode(GroupOpcode group, PartyOpcode command) : this((byte)group, (byte)command) { }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public MessageOpcode(GroupOpcode group, ItemUpgradeOpcode command) : this((byte)group, (byte)command) { }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public MessageOpcode(GroupOpcode group, DropOpcode command) : this((byte)group, (byte)command) { }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public MessageOpcode(GroupOpcode group, QuestOpcode command) : this((byte)group, (byte)command) { }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public MessageOpcode(GroupOpcode group, OptionOpcode command) : this((byte)group, (byte)command) { }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public MessageOpcode(GroupOpcode group, MonsterOpcode command) : this((byte)group, (byte)command) { }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public MessageOpcode(GroupOpcode group, ItemSetupOpcode command) : this((byte)group, (byte)command) { }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public MessageOpcode(GroupOpcode group, FriendOpcode command) : this((byte)group, (byte)command) { }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public MessageOpcode(GroupOpcode group, PostOpcode command) : this((byte)group, (byte)command) { }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public MessageOpcode(GroupOpcode group, SoulMetryOpcode command) : this((byte)group, (byte)command) { }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public MessageOpcode(GroupOpcode group, LeagueOpcode command) : this((byte)group, (byte)command) { }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public MessageOpcode(GroupOpcode group, GestureOpcode command) : this((byte)group, (byte)command) { }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public MessageOpcode(GroupOpcode group, DailyMissionOpcode command) : this((byte)group, (byte)command) { }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public MessageOpcode(GroupOpcode group, VaccumOpcode command) : this((byte)group, (byte)command) { }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public MessageOpcode(GroupOpcode group, MyRoomOpcode command) : this((byte)group, (byte)command) { }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public MessageOpcode(GroupOpcode group, HelperOpcode command) : this((byte)group, (byte)command) { }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public MessageOpcode(GroupOpcode group, InfiniteTowerOpcode command) : this((byte)group, (byte)command) { }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public MessageOpcode(GroupOpcode group, BoosterOpcode command) : this((byte)group, (byte)command) { }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public MessageOpcode(GroupOpcode group, EventOpcode command) : this((byte)group, (byte)command) { }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public MessageOpcode(GroupOpcode group, ExchangeOpcode command) : this((byte)group, (byte)command) { }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public MessageOpcode(GroupOpcode group, RankingOpcode command) : this((byte)group, (byte)command) { }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public MessageOpcode(GroupOpcode group, SocialItemOpcode command) : this((byte)group, (byte)command) { }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public MessageOpcode(GroupOpcode group, ForceOpcode command) : this((byte)group, (byte)command) { }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public MessageOpcode(GroupOpcode group, WorldModeOpcode command) : this((byte)group, (byte)command) { }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public MessageOpcode(GroupOpcode group, WeeklyMissionOpcode command) : this((byte)group, (byte)command) { }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public MessageOpcode(GroupOpcode group, ModeMazeOpcode command) : this((byte)group, (byte)command) { }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public MessageOpcode(GroupOpcode group, RestartOpcode command) : this((byte)group, (byte)command) { }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public MessageOpcode(GroupOpcode group, ToolOpcode command) : this((byte)group, (byte)command) { }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public MessageOpcode(GroupOpcode group, ChannelOpcode command) : this((byte)group, (byte)command) { }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public MessageOpcode(GroupOpcode group, ServerOpcode command) : this((byte)group, (byte)command) { }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public MessageOpcode(GroupOpcode group, ServerUserOpcode command) : this((byte)group, (byte)command) { }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public MessageOpcode(GroupOpcode group, ServerPartyOpcode command) : this((byte)group, (byte)command) { }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public MessageOpcode(GroupOpcode group, ServerFriendOpcode command) : this((byte)group, (byte)command) { }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public MessageOpcode(GroupOpcode group, ServerLeagueOpcode command) : this((byte)group, (byte)command) { }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public MessageOpcode(GroupOpcode group, MonitorOpcode command) : this((byte)group, (byte)command) { }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public MessageOpcode(GroupOpcode group, GmAgentOpcode command) : this((byte)group, (byte)command) { }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public MessageOpcode(GroupOpcode group, ServerForceOpcode command) : this((byte)group, (byte)command) { }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public MessageOpcode(GroupOpcode group, ServerWorldModeOpcode command) : this((byte)group, (byte)command) { }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public MessageOpcode(GroupOpcode group, ServerModeMazeOpcode command) : this((byte)group, (byte)command) { }

    #endregion Constructors

    public override string ToString() => string.Format("{0:X2}:{1:X2}", (int)Group, (int)Command);

    public string ToFullString() => string.Format("{0}:{1}", (GroupOpcode)Group, ToCommandString());

    public string ToCommandString() => (GroupOpcode)Group switch
    {
        GroupOpcode.System => $"{(SystemOpcode)Command}",
        GroupOpcode.Login => $"{(LoginOpcode)Command}",
        GroupOpcode.Character => $"{(CharacterOpcode)Command}",
        GroupOpcode.World => $"{(WorldOpcode)Command}",
        GroupOpcode.Move => $"{(MoveOpcode)Command}",
        GroupOpcode.Skill => $"{(SkillOpcode)Command}",
        GroupOpcode.Chat => $"{(ChatOpcode)Command}",
        GroupOpcode.Item => $"{(ItemOpcode)Command}",
        GroupOpcode.Shop => $"{(ShopOpcode)Command}",
        GroupOpcode.Trade => $"{(TradeOpcode)Command}",
        GroupOpcode.Maze => $"{(MazeOpcode)Command}",
        GroupOpcode.Party => $"{(PartyOpcode)Command}",
        GroupOpcode.ItemUpgrade => $"{(ItemUpgradeOpcode)Command}",
        GroupOpcode.Drop => $"{(DropOpcode)Command}",
        GroupOpcode.Quest => $"{(QuestOpcode)Command}",
        GroupOpcode.Option => $"{(OptionOpcode)Command}",
        GroupOpcode.Monster => $"{(MonsterOpcode)Command}",
        GroupOpcode.ItemSetup => $"{(ItemSetupOpcode)Command}",
        GroupOpcode.Friend => $"{(FriendOpcode)Command}",
        GroupOpcode.Post => $"{(PostOpcode)Command}",
        GroupOpcode.SoulMetry => $"{(SoulMetryOpcode)Command}",
        GroupOpcode.League => $"{(LeagueOpcode)Command}",
        GroupOpcode.Gesture => $"{(GestureOpcode)Command}",
        GroupOpcode.DailyMission => $"{(DailyMissionOpcode)Command}",
        GroupOpcode.Vaccum => $"{(VaccumOpcode)Command}",
        GroupOpcode.MyRoom => $"{(MyRoomOpcode)Command}",
        GroupOpcode.Helper => $"{(HelperOpcode)Command}",
        GroupOpcode.InfiniteTower => $"{(InfiniteTowerOpcode)Command}",
        GroupOpcode.Booster => $"{(BoosterOpcode)Command}",
        GroupOpcode.Event => $"{(EventOpcode)Command}",
        GroupOpcode.Exchange => $"{(ExchangeOpcode)Command}",
        GroupOpcode.Ranking => $"{(RankingOpcode)Command}",
        GroupOpcode.SocialItem => $"{(SocialItemOpcode)Command}",
        GroupOpcode.Force => $"{(ForceOpcode)Command}",
        GroupOpcode.WorldMode => $"{(WorldModeOpcode)Command}",
        GroupOpcode.WeeklyMission => $"{(WeeklyMissionOpcode)Command}",
        GroupOpcode.ModeMaze => $"{(ModeMazeOpcode)Command}",
        GroupOpcode.Restart => $"{(RestartOpcode)Command}",
        GroupOpcode.Tool => $"{(ToolOpcode)Command}",
        GroupOpcode.Channel => $"{(ChannelOpcode)Command}",
        GroupOpcode.Server => $"{(ServerOpcode)Command}",
        GroupOpcode.ServerUser => $"{(ServerUserOpcode)Command}",
        GroupOpcode.ServerParty => $"{(ServerPartyOpcode)Command}",
        GroupOpcode.ServerFriend => $"{(ServerFriendOpcode)Command}",
        GroupOpcode.ServerLeague => $"{(ServerLeagueOpcode)Command}",
        GroupOpcode.Monitor => $"{(MonitorOpcode)Command}",
        GroupOpcode.GmAgent => $"{(GmAgentOpcode)Command}",
        GroupOpcode.ServerForce => $"{(ServerForceOpcode)Command}",
        GroupOpcode.ServerWorldMode => $"{(ServerWorldModeOpcode)Command}",
        GroupOpcode.ServerModeMaze => $"{(ServerModeMazeOpcode)Command}",
        _ => throw new ArgumentOutOfRangeException(nameof(Group), Group, null)
    };
}

