<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Arch" Version="2.1.0" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Abstractions" Version="10.0.5" />
        <PackageReference Include="Redis.OM" Version="1.1.0" />
    </ItemGroup>

    <ItemGroup>
        <Folder Include="Batch\"/>
        <Folder Include="Extensions\" />
    </ItemGroup>

</Project>
