<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>preview</LangVersion>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="LuaCSharp" Version="0.4.2" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\OpenWorker.Batch\OpenWorker.Batch.csproj" />
      <ProjectReference Include="..\OpenWorker.Hotspot\OpenWorker.Hotspot.csproj" />
    </ItemGroup>

</Project>
