// <auto-generated>

using OpenWorker.Extensions;
using OpenWorker.Res.Attributes;

namespace OpenWorker.UpdateContent.Res.Rows;

[BinaryResourceTable("tb_Achievement")]
public readonly struct AchievementRow(BinaryReader reader)
{
    public int Id { get; } = reader.ReadInt32();
    public byte Field1 { get; } = reader.ReadByte();
    public short Field2 { get; } = reader.ReadInt16();
    public byte Field3 { get; } = reader.ReadByte();
    public short Field4 { get; } = reader.ReadInt16();
    public string Field5 { get; } = reader.ReadUtf16UnicodeStringWithoutTerminator();
    public short Field6 { get; } = reader.ReadInt16();
    public int Field7 { get; } = reader.ReadInt32();
    public int Field8 { get; } = reader.ReadInt32();
    public int Field9 { get; } = reader.ReadInt32();
    public int Field10 { get; } = reader.ReadInt32();
    public int Field11 { get; } = reader.ReadInt32();
    public int Field12 { get; } = reader.ReadInt32();
    public int Field13 { get; } = reader.ReadInt32();
    public int Field14 { get; } = reader.ReadInt32();
    public byte Field15 { get; } = reader.ReadByte();
    public byte Field16 { get; } = reader.ReadByte();
    public int Field17 { get; } = reader.ReadInt32();
    public int Field18 { get; } = reader.ReadInt32();
    public byte Field19 { get; } = reader.ReadByte();
    public byte Field20 { get; } = reader.ReadByte();
}
