// <auto-generated>

using OpenWorker.Res.Attributes;

namespace OpenWorker.UpdateContent.Res.Rows;

[BinaryResourceTable("tb_Achievement_begin")]
public readonly struct AchievementBeginRow(BinaryReader reader)
{
    public short Id { get; } = reader.ReadInt16();
    public int Field1 { get; } = reader.ReadInt32();
    public byte Field2 { get; } = reader.ReadByte();
}
