// <auto-generated>

using OpenWorker.Extensions;
using OpenWorker.Res.Attributes;

namespace OpenWorker.UpdateContent.Res.Rows;

[BinaryResourceTable("tb_Akashic_Records")]
public readonly struct AkashicRecordsRow(BinaryReader reader)
{
    public int Id { get; } = reader.ReadInt32();
    public short Field1 { get; } = reader.ReadInt16();
    public int Field2 { get; } = reader.ReadInt32();
    public short Field3 { get; } = reader.ReadInt16();
    public short Field4 { get; } = reader.ReadInt16();
    public byte Field5 { get; } = reader.ReadByte();
    public byte Field6 { get; } = reader.ReadByte();
    public byte Field7 { get; } = reader.ReadByte();
    public byte Field8 { get; } = reader.ReadByte();
    public byte Field9 { get; } = reader.ReadByte();
    public string Field10 { get; } = reader.ReadUtf16UnicodeStringWithoutTerminator();
    public string Field11 { get; } = reader.ReadUtf16UnicodeStringWithoutTerminator();
    public short Field12 { get; } = reader.ReadInt16();
    public short Field13 { get; } = reader.ReadInt16();
    public short Field14 { get; } = reader.ReadInt16();
    public string Field15 { get; } = reader.ReadUtf16UnicodeStringWithoutTerminator();
    public short Field16 { get; } = reader.ReadInt16();
    public int Field17 { get; } = reader.ReadInt32();
    public byte Field18 { get; } = reader.ReadByte();
    public short Field19 { get; } = reader.ReadInt16();
    public int Field20 { get; } = reader.ReadInt32();
    public int Field21 { get; } = reader.ReadInt32();
    public int Field22 { get; } = reader.ReadInt32();
    public byte Field23 { get; } = reader.ReadByte();
    public short Field24 { get; } = reader.ReadInt16();
    public int Field25 { get; } = reader.ReadInt32();
    public int Field26 { get; } = reader.ReadInt32();
    public int Field27 { get; } = reader.ReadInt32();
    public byte Field28 { get; } = reader.ReadByte();
    public int Field29 { get; } = reader.ReadInt32();
    public int Field30 { get; } = reader.ReadInt32();
    public int Field31 { get; } = reader.ReadInt32();
    public int Field32 { get; } = reader.ReadInt32();
}
