// <auto-generated>

using OpenWorker.Res.Attributes;

namespace OpenWorker.UpdateContent.Res.Rows;

[BinaryResourceTable("tb_Akashic_Disassemble")]
public readonly struct AkashicDisassembleRow(BinaryReader reader)
{
    public int Id { get; } = reader.ReadInt32();
    public short Field1 { get; } = reader.ReadInt16();
    public int Field2 { get; } = reader.ReadInt32();
    public byte Field3 { get; } = reader.ReadByte();
    public int Field4 { get; } = reader.ReadInt32();
}
