// <auto-generated>

using OpenWorker.Res.Attributes;

namespace OpenWorker.UpdateContent.Res.Rows;

[BinaryResourceTable("tb_Booster")]
public readonly struct BoosterRow(BinaryReader reader)
{
    public short Id { get; } = reader.ReadInt16();
    public short Field1 { get; } = reader.ReadInt16();
    public byte Field2 { get; } = reader.ReadByte();
    public byte Field3 { get; } = reader.ReadByte();
    public byte Field4 { get; } = reader.ReadByte();
    public byte Field5 { get; } = reader.ReadByte();
    public byte Field6 { get; } = reader.ReadByte();
    public byte Field7 { get; } = reader.ReadByte();
    public byte Field8 { get; } = reader.ReadByte();
    public byte Field9 { get; } = reader.ReadByte();
    public byte Field10 { get; } = reader.ReadByte();
    public byte Field11 { get; } = reader.ReadByte();
    public byte Field12 { get; } = reader.ReadByte();
    public byte Field13 { get; } = reader.ReadByte();
    public byte Field14 { get; } = reader.ReadByte();
    public byte Field15 { get; } = reader.ReadByte();
    public byte Field16 { get; } = reader.ReadByte();
    public byte Field17 { get; } = reader.ReadByte();
    public float Field18 { get; } = reader.ReadSingle();
    public float Field19 { get; } = reader.ReadSingle();
    public float Field20 { get; } = reader.ReadSingle();
    public float Field21 { get; } = reader.ReadSingle();
    public float Field22 { get; } = reader.ReadSingle();
    public float Field23 { get; } = reader.ReadSingle();
    public float Field24 { get; } = reader.ReadSingle();
    public float Field25 { get; } = reader.ReadSingle();
    public short Field26 { get; } = reader.ReadInt16();
    public short Field27 { get; } = reader.ReadInt16();
    public short Field28 { get; } = reader.ReadInt16();
    public short Field29 { get; } = reader.ReadInt16();
    public short Field30 { get; } = reader.ReadInt16();
    public short Field31 { get; } = reader.ReadInt16();
    public short Field32 { get; } = reader.ReadInt16();
    public short Field33 { get; } = reader.ReadInt16();
    public short Field34 { get; } = reader.ReadInt16();
    public byte Field35 { get; } = reader.ReadByte();
    public int Field36 { get; } = reader.ReadInt32();
}
