// <auto-generated>

using OpenWorker.Extensions;
using OpenWorker.Res.Attributes;

namespace OpenWorker.UpdateContent.Res.Rows;

[BinaryResourceTable("tb_Booster_Script")]
public readonly struct BoosterScriptRow(BinaryReader reader)
{
    public short Id { get; } = reader.ReadInt16();
    public string Field1 { get; } = reader.ReadUtf16UnicodeStringWithoutTerminator();
    public string Field2 { get; } = reader.ReadUtf16UnicodeStringWithoutTerminator();
    public string Field3 { get; } = reader.ReadUtf16UnicodeStringWithoutTerminator();
}
