// <auto-generated>

using OpenWorker.Extensions;
using OpenWorker.Res.Attributes;

namespace OpenWorker.UpdateContent.Res.Rows;

[BinaryResourceTable("tb_Buff")]
public readonly struct BuffRow(BinaryReader reader)
{
    public short Id { get; } = reader.ReadInt16();
    public byte Field1 { get; } = reader.ReadByte();
    public byte Field2 { get; } = reader.ReadByte();
    public short Field3 { get; } = reader.ReadInt16();
    public short Field4 { get; } = reader.ReadInt16();
    public int Field5 { get; } = reader.ReadInt32();
    public byte Field6 { get; } = reader.ReadByte();
    public int Field7 { get; } = reader.ReadInt32();
    public int Field8 { get; } = reader.ReadInt32();
    public int Field9 { get; } = reader.ReadInt32();
    public byte Field10 { get; } = reader.ReadByte();
    public byte Field11 { get; } = reader.ReadByte();
    public byte Field12 { get; } = reader.ReadByte();
    public string Field13 { get; } = reader.ReadUtf16UnicodeStringWithoutTerminator();
    public short Field14 { get; } = reader.ReadInt16();
    public int Field15 { get; } = reader.ReadInt32();
    public short Field16 { get; } = reader.ReadInt16();
    public short Field17 { get; } = reader.ReadInt16();
    public byte Field18 { get; } = reader.ReadByte();
    public int Field19 { get; } = reader.ReadInt32();
    public byte Field20 { get; } = reader.ReadByte();
    public int Field21 { get; } = reader.ReadInt32();
    public byte Field22 { get; } = reader.ReadByte();
    public int Field23 { get; } = reader.ReadInt32();
    public short Field24 { get; } = reader.ReadInt16();
    public short Field25 { get; } = reader.ReadInt16();
    public short Field26 { get; } = reader.ReadInt16();
    public short Field27 { get; } = reader.ReadInt16();
    public short Field28 { get; } = reader.ReadInt16();
    public short Field29 { get; } = reader.ReadInt16();
    public string Field30 { get; } = reader.ReadUtf16UnicodeStringWithoutTerminator();
    public short Field31 { get; } = reader.ReadInt16();
    public int Field32 { get; } = reader.ReadInt32();
    public byte Field33 { get; } = reader.ReadByte();
    public byte Field34 { get; } = reader.ReadByte();
}
