// <auto-generated>

using OpenWorker.Extensions;
using OpenWorker.Res.Attributes;

namespace OpenWorker.UpdateContent.Res.Rows;

[BinaryResourceTable("tb_CashShop")]
public readonly struct CashShopRow(BinaryReader reader)
{
    public int Id { get; } = reader.ReadInt32();
    public short Field1 { get; } = reader.ReadInt16();
    public short Field2 { get; } = reader.ReadInt16();
    public byte Field3 { get; } = reader.ReadByte();
    public int Field4 { get; } = reader.ReadInt32();
    public byte Field5 { get; } = reader.ReadByte();
    public byte Field6 { get; } = reader.ReadByte();
    public byte Field7 { get; } = reader.ReadByte();
    public byte Field8 { get; } = reader.ReadByte();
    public string Field9 { get; } = reader.ReadUtf16UnicodeStringWithoutTerminator();
    public string Field10 { get; } = reader.ReadUtf16UnicodeStringWithoutTerminator();
    public byte Field11 { get; } = reader.ReadByte();
    public short Field12 { get; } = reader.ReadInt16();
    public byte Field13 { get; } = reader.ReadByte();
    public short Field14 { get; } = reader.ReadInt16();
}
