// <auto-generated>

using OpenWorker.Res.Attributes;

namespace OpenWorker.UpdateContent.Res.Rows;

[BinaryResourceTable("tb_CashBilling_Info")]
public readonly struct CashBillingInfoRow(BinaryReader reader)
{
    public short Id { get; } = reader.ReadInt16();
    public int Field1 { get; } = reader.ReadInt32();
    public int Field2 { get; } = reader.ReadInt32();
    public int Field3 { get; } = reader.ReadInt32();
    public int Field4 { get; } = reader.ReadInt32();
    public int Field5 { get; } = reader.ReadInt32();
    public int Field6 { get; } = reader.ReadInt32();
    public int Field7 { get; } = reader.ReadInt32();
    public int Field8 { get; } = reader.ReadInt32();
    public int Field9 { get; } = reader.ReadInt32();
    public int Field10 { get; } = reader.ReadInt32();
    public int Field11 { get; } = reader.ReadInt32();
    public int Field12 { get; } = reader.ReadInt32();
    public int Field13 { get; } = reader.ReadInt32();
    public int Field14 { get; } = reader.ReadInt32();
    public int Field15 { get; } = reader.ReadInt32();
    public int Field16 { get; } = reader.ReadInt32();
    public int Field17 { get; } = reader.ReadInt32();
    public int Field18 { get; } = reader.ReadInt32();
    public int Field19 { get; } = reader.ReadInt32();
    public int Field20 { get; } = reader.ReadInt32();
}
