// <auto-generated>

using OpenWorker.Extensions;
using OpenWorker.Res.Attributes;

namespace OpenWorker.UpdateContent.Res.Rows;

[BinaryResourceTable("tb_Character_Info")]
public readonly struct CharacterInfoRow(BinaryReader reader)
{
    public short Id { get; } = reader.ReadInt16();
    public string Field1 { get; } = reader.ReadUtf16UnicodeStringWithoutTerminator();
    public string Field2 { get; } = reader.ReadUtf16UnicodeStringWithoutTerminator();
    public string Field3 { get; } = reader.ReadUtf16UnicodeStringWithoutTerminator();
    public string Field4 { get; } = reader.ReadUtf16UnicodeStringWithoutTerminator();
    public string Field5 { get; } = reader.ReadUtf16UnicodeStringWithoutTerminator();
    public string Field6 { get; } = reader.ReadUtf16UnicodeStringWithoutTerminator();
    public string Field7 { get; } = reader.ReadUtf16UnicodeStringWithoutTerminator();
    public int Field8 { get; } = reader.ReadInt32();
    public int Field9 { get; } = reader.ReadInt32();
    public int Field10 { get; } = reader.ReadInt32();
    public int Field11 { get; } = reader.ReadInt32();
    public int Field12 { get; } = reader.ReadInt32();
    public int Field13 { get; } = reader.ReadInt32();
    public int Field14 { get; } = reader.ReadInt32();
    public int Field15 { get; } = reader.ReadInt32();
    public int Field16 { get; } = reader.ReadInt32();
    public short Field17 { get; } = reader.ReadInt16();
    public short Field18 { get; } = reader.ReadInt16();
    public int Field19 { get; } = reader.ReadInt32();
    public int Field20 { get; } = reader.ReadInt32();
    public int Default_Cloth_ID_01 { get; } = reader.ReadInt32();
    public int Default_Cloth_ID_02 { get; } = reader.ReadInt32();
    public int Default_Cloth_ID_03 { get; } = reader.ReadInt32();
    public int Default_Cloth_ID_04 { get; } = reader.ReadInt32();
    public short District_ID { get; } = reader.ReadInt16();
    public short Field26 { get; } = reader.ReadInt16();
    public short District_Position_X { get; } = reader.ReadInt16();
    public short District_Position_Y { get; } = reader.ReadInt16();
    public short District_Position_Z { get; } = reader.ReadInt16();
    public byte Character_Status_Type { get; } = reader.ReadByte();
    public int Character_Status { get; } = reader.ReadInt32();
    public int Field32 { get; } = reader.ReadInt32();
    public int Field33 { get; } = reader.ReadInt32();
    public short Field34 { get; } = reader.ReadInt16();
    public float Field35 { get; } = reader.ReadSingle();
    public short Char_Height_Value { get; } = reader.ReadInt16();
    public short Normal_Walk_Speed { get; } = reader.ReadInt16();
    public short Normal_Run_Speed { get; } = reader.ReadInt16();
    public short Normal_JumpMove_Speed { get; } = reader.ReadInt16();
    public short Battle_Run_Speed { get; } = reader.ReadInt16();
    public short Battle_JumpMove_Speed { get; } = reader.ReadInt16();
    public short Battle_Dash_Speed { get; } = reader.ReadInt16();
    public float Battle_BackMove_Ratio { get; } = reader.ReadSingle();
    public byte PC_Faction { get; } = reader.ReadByte();
    public short Field45 { get; } = reader.ReadInt16();
    public short Field46 { get; } = reader.ReadInt16();
    public short Field47 { get; } = reader.ReadInt16();
    public short Field48 { get; } = reader.ReadInt16();
    public short Field49 { get; } = reader.ReadInt16();
    public short Field50 { get; } = reader.ReadInt16();
    public short Field51 { get; } = reader.ReadInt16();
    public short Field52 { get; } = reader.ReadInt16();
    public short Field53 { get; } = reader.ReadInt16();
    public short Field54 { get; } = reader.ReadInt16();
    public short Char_CollisionRadius { get; } = reader.ReadInt16();
    public short Char_CollisionHeight { get; } = reader.ReadInt16();
    public short Char_RealHeight { get; } = reader.ReadInt16();
    public int Default_Skill_ID_01 { get; } = reader.ReadInt32();
    public int Default_Skill_ID_02 { get; } = reader.ReadInt32();
    public int Default_Skill_ID_03 { get; } = reader.ReadInt32();
    public int Default_Skill_ID_04 { get; } = reader.ReadInt32();
    public int Default_Skill_ID_05 { get; } = reader.ReadInt32();
    public int Default_Skill_ID_06 { get; } = reader.ReadInt32();
    public int Default_Skill_ID_07 { get; } = reader.ReadInt32();
    public int Default_Skill_ID_08 { get; } = reader.ReadInt32();
    public int Default_Skill_ID_09 { get; } = reader.ReadInt32();
    public int Default_Skill_ID_10 { get; } = reader.ReadInt32();
    public int Default_Skill_ID_11 { get; } = reader.ReadInt32();
    public int Default_Skill_ID_12 { get; } = reader.ReadInt32();
    public int Default_Skill_ID_13 { get; } = reader.ReadInt32();
    public int Default_Skill_ID_14 { get; } = reader.ReadInt32();
    public int Default_Skill_ID_15 { get; } = reader.ReadInt32();
    public int Default_Skill_ID_16 { get; } = reader.ReadInt32();
    public int Default_Skill_ID_17 { get; } = reader.ReadInt32();
    public int Default_Skill_ID_18 { get; } = reader.ReadInt32();
    public int Default_Skill_ID_19 { get; } = reader.ReadInt32();
    public int Default_Skill_ID_20 { get; } = reader.ReadInt32();
    public short Field78 { get; } = reader.ReadInt16();
    public float Akashic_Active_Time { get; } = reader.ReadSingle();
    public int Field80 { get; } = reader.ReadInt32();
    public short Field81 { get; } = reader.ReadInt16();
    
    public byte Character => (byte)Math.Floor(Id * 0.001);

    public IEnumerable<int> GetSkillList()
    {
        yield return Default_Skill_ID_01;
        yield return Default_Skill_ID_02;
        yield return Default_Skill_ID_03;
        yield return Default_Skill_ID_04;
        yield return Default_Skill_ID_05;
        yield return Default_Skill_ID_06;
        yield return Default_Skill_ID_07;
        yield return Default_Skill_ID_08;
        yield return Default_Skill_ID_09;
        yield return Default_Skill_ID_10;
        yield return Default_Skill_ID_11;
        yield return Default_Skill_ID_12;
        yield return Default_Skill_ID_13;
        yield return Default_Skill_ID_14;
        yield return Default_Skill_ID_15;
        yield return Default_Skill_ID_16;
        yield return Default_Skill_ID_17;
        yield return Default_Skill_ID_18;
        yield return Default_Skill_ID_19;
        yield return Default_Skill_ID_20;
    }
}
