// <auto-generated>

using OpenWorker.Extensions;
using OpenWorker.Res.Attributes;

namespace OpenWorker.UpdateContent.Res.Rows;

[BinaryResourceTable("tb_Character_Parts")]
public readonly struct CharacterPartsRow(BinaryReader reader)
{
    public short Id { get; } = reader.ReadInt16();
    public short Field1 { get; } = reader.ReadInt16();
    public byte Field2 { get; } = reader.ReadByte();
    public string Field3 { get; } = reader.ReadUtf16UnicodeStringWithoutTerminator();
    public string Field4 { get; } = reader.ReadUtf16UnicodeStringWithoutTerminator();
    public string Field5 { get; } = reader.ReadUtf16UnicodeStringWithoutTerminator();
    public string Field6 { get; } = reader.ReadUtf16UnicodeStringWithoutTerminator();
    public string Field7 { get; } = reader.ReadUtf16UnicodeStringWithoutTerminator();
}
