// <auto-generated>

using OpenWorker.Res.Attributes;

namespace OpenWorker.UpdateContent.Res.Rows;

[BinaryResourceTable("tb_Check_Attendance_Info")]
public readonly struct CheckAttendanceInfoRow(BinaryReader reader)
{
    public int Id { get; } = reader.ReadInt32();
    public int Field1 { get; } = reader.ReadInt32();
    public int Field2 { get; } = reader.ReadInt32();
}
