// <auto-generated>

using OpenWorker.Extensions;
using OpenWorker.Res.Attributes;

namespace OpenWorker.UpdateContent.Res.Rows;

[BinaryResourceTable("tb_ClassSelect_Info")]
public readonly struct ClassSelectInfoRow(BinaryReader reader)
{
    public byte Id { get; } = reader.ReadByte();
    public string Field1 { get; } = reader.ReadUtf16UnicodeStringWithoutTerminator();
    public string Field2 { get; } = reader.ReadUtf16UnicodeStringWithoutTerminator();
    public int Field3 { get; } = reader.ReadInt32();
    public int Field4 { get; } = reader.ReadInt32();
    public int Field5 { get; } = reader.ReadInt32();
    public int Field6 { get; } = reader.ReadInt32();
    public int Field7 { get; } = reader.ReadInt32();
    public int Field8 { get; } = reader.ReadInt32();
    public int Field9 { get; } = reader.ReadInt32();
    public int Field10 { get; } = reader.ReadInt32();
    public int Field11 { get; } = reader.ReadInt32();
    public int Field12 { get; } = reader.ReadInt32();
    public int Field13 { get; } = reader.ReadInt32();
    public int Field14 { get; } = reader.ReadInt32();
    public int Field15 { get; } = reader.ReadInt32();
    public short Field16 { get; } = reader.ReadInt16();
    public short Field17 { get; } = reader.ReadInt16();
    public int Field18 { get; } = reader.ReadInt32();
    public short Field19 { get; } = reader.ReadInt16();
    public string Field20 { get; } = reader.ReadUtf16UnicodeStringWithoutTerminator();
    public string Field21 { get; } = reader.ReadUtf16UnicodeStringWithoutTerminator();
    public string Field22 { get; } = reader.ReadUtf16UnicodeStringWithoutTerminator();
}
