// <auto-generated>

using OpenWorker.Res.Attributes;

namespace OpenWorker.UpdateContent.Res.Rows;

[BinaryResourceTable("tb_Color")]
public readonly struct ColorRow(BinaryReader reader)
{
    public int Id { get; } = reader.ReadInt32();
    public byte Field1 { get; } = reader.ReadByte();
    public byte Field2 { get; } = reader.ReadByte();
    public byte Field3 { get; } = reader.ReadByte();
    public byte Field4 { get; } = reader.ReadByte();
    public byte Field5 { get; } = reader.ReadByte();
    public byte Field6 { get; } = reader.ReadByte();
    public byte Field7 { get; } = reader.ReadByte();
    public byte Field8 { get; } = reader.ReadByte();
    public byte Field9 { get; } = reader.ReadByte();
    public byte Field10 { get; } = reader.ReadByte();
}
