// <auto-generated>

using OpenWorker.Res.Attributes;

namespace OpenWorker.UpdateContent.Res.Rows;

[BinaryResourceTable("tb_ControlKeyInfo")]
public readonly struct ControlKeyInfoRow(BinaryReader reader)
{
    public short Id { get; } = reader.ReadInt16();
    public short Field1 { get; } = reader.ReadInt16();
    public short Field2 { get; } = reader.ReadInt16();
    public short Field3 { get; } = reader.ReadInt16();
    public short Field4 { get; } = reader.ReadInt16();
    public short Field5 { get; } = reader.ReadInt16();
    public short Field6 { get; } = reader.ReadInt16();
    public short Field7 { get; } = reader.ReadInt16();
    public short Field8 { get; } = reader.ReadInt16();
    public short Field9 { get; } = reader.ReadInt16();
    public short Field10 { get; } = reader.ReadInt16();
    public short Field11 { get; } = reader.ReadInt16();
    public short Field12 { get; } = reader.ReadInt16();
}
