// <auto-generated>

using OpenWorker.Extensions;
using OpenWorker.Res.Attributes;

namespace OpenWorker.UpdateContent.Res.Rows;

[BinaryResourceTable("tb_Create_Cloth")]
public readonly struct CreateClothRow(BinaryReader reader)
{
    public short Id { get; } = reader.ReadInt16();
    public int Field1 { get; } = reader.ReadInt32();
    public int Field2 { get; } = reader.ReadInt32();
    public int Field3 { get; } = reader.ReadInt32();
    public int Field4 { get; } = reader.ReadInt32();
    public int Field5 { get; } = reader.ReadInt32();
    public string Field6 { get; } = reader.ReadUtf16UnicodeStringWithoutTerminator();
}
