// <auto-generated>

using OpenWorker.Res.Attributes;

namespace OpenWorker.UpdateContent.Res.Rows;

[BinaryResourceTable("tb_Credit_Raise")]
public readonly struct CreditRaiseRow(BinaryReader reader)
{
    public short Id { get; } = reader.ReadInt16();
    public short Field1 { get; } = reader.ReadInt16();
    public byte Field2 { get; } = reader.ReadByte();
    public byte Field3 { get; } = reader.ReadByte();
    public byte Field4 { get; } = reader.ReadByte();
}
