// <auto-generated>

using OpenWorker.Extensions;
using OpenWorker.Res.Attributes;

namespace OpenWorker.UpdateContent.Res.Rows;

[BinaryResourceTable("tb_Customize_Skin")]
public readonly struct CustomizeSkinRow(BinaryReader reader)
{
    public byte Id { get; } = reader.ReadByte();
    public int Field1 { get; } = reader.ReadInt32();
    public int Field2 { get; } = reader.ReadInt32();
    public int Field3 { get; } = reader.ReadInt32();
    public int Field4 { get; } = reader.ReadInt32();
    public int Field5 { get; } = reader.ReadInt32();
    public int Field6 { get; } = reader.ReadInt32();
    public int Field7 { get; } = reader.ReadInt32();
    public int Field8 { get; } = reader.ReadInt32();
    public int Field9 { get; } = reader.ReadInt32();
    public int Field10 { get; } = reader.ReadInt32();
    public string Field11 { get; } = reader.ReadUtf16UnicodeStringWithoutTerminator();
    public string Field12 { get; } = reader.ReadUtf16UnicodeStringWithoutTerminator();
    public string Field13 { get; } = reader.ReadUtf16UnicodeStringWithoutTerminator();
    public string Field14 { get; } = reader.ReadUtf16UnicodeStringWithoutTerminator();
    public string Field15 { get; } = reader.ReadUtf16UnicodeStringWithoutTerminator();
    public string Field16 { get; } = reader.ReadUtf16UnicodeStringWithoutTerminator();
    public string Field17 { get; } = reader.ReadUtf16UnicodeStringWithoutTerminator();
    public string Field18 { get; } = reader.ReadUtf16UnicodeStringWithoutTerminator();
    public string Field19 { get; } = reader.ReadUtf16UnicodeStringWithoutTerminator();
    public string Field20 { get; } = reader.ReadUtf16UnicodeStringWithoutTerminator();
    public int Field21 { get; } = reader.ReadInt32();
    public int Field22 { get; } = reader.ReadInt32();
    public int Field23 { get; } = reader.ReadInt32();
    public int Field24 { get; } = reader.ReadInt32();
    public int Field25 { get; } = reader.ReadInt32();
    public int Field26 { get; } = reader.ReadInt32();
    public int Field27 { get; } = reader.ReadInt32();
    public int Field28 { get; } = reader.ReadInt32();
    public int Field29 { get; } = reader.ReadInt32();
    public int Field30 { get; } = reader.ReadInt32();
}
