// <auto-generated>

using OpenWorker.Extensions;
using OpenWorker.Res.Attributes;

namespace OpenWorker.UpdateContent.Res.Rows;

[BinaryResourceTable("tb_Customize_Hair")]
public readonly struct CustomizeHairRow(BinaryReader reader)
{
    public byte Id { get; } = reader.ReadByte();
    public int Field1 { get; } = reader.ReadInt32();
    public int Field2 { get; } = reader.ReadInt32();
    public int Field3 { get; } = reader.ReadInt32();
    public int Field4 { get; } = reader.ReadInt32();
    public int Field5 { get; } = reader.ReadInt32();
    public int Field6 { get; } = reader.ReadInt32();
    public int Field7 { get; } = reader.ReadInt32();
    public int Field8 { get; } = reader.ReadInt32();
    public int Field9 { get; } = reader.ReadInt32();
    public int Field10 { get; } = reader.ReadInt32();
    public int Field11 { get; } = reader.ReadInt32();
    public int Field12 { get; } = reader.ReadInt32();
    public int Field13 { get; } = reader.ReadInt32();
    public int Field14 { get; } = reader.ReadInt32();
    public int Field15 { get; } = reader.ReadInt32();
    public int Field16 { get; } = reader.ReadInt32();
    public int Field17 { get; } = reader.ReadInt32();
    public int Field18 { get; } = reader.ReadInt32();
    public int Field19 { get; } = reader.ReadInt32();
    public int Field20 { get; } = reader.ReadInt32();
    public int Field21 { get; } = reader.ReadInt32();
    public int Field22 { get; } = reader.ReadInt32();
    public int Field23 { get; } = reader.ReadInt32();
    public int Field24 { get; } = reader.ReadInt32();
    public int Field25 { get; } = reader.ReadInt32();
    public int Field26 { get; } = reader.ReadInt32();
    public int Field27 { get; } = reader.ReadInt32();
    public int Field28 { get; } = reader.ReadInt32();
    public int Field29 { get; } = reader.ReadInt32();
    public int Field30 { get; } = reader.ReadInt32();
    public string Field31 { get; } = reader.ReadUtf16UnicodeStringWithoutTerminator();
    public string Field32 { get; } = reader.ReadUtf16UnicodeStringWithoutTerminator();
    public string Field33 { get; } = reader.ReadUtf16UnicodeStringWithoutTerminator();
    public string Field34 { get; } = reader.ReadUtf16UnicodeStringWithoutTerminator();
    public string Field35 { get; } = reader.ReadUtf16UnicodeStringWithoutTerminator();
    public string Field36 { get; } = reader.ReadUtf16UnicodeStringWithoutTerminator();
    public string Field37 { get; } = reader.ReadUtf16UnicodeStringWithoutTerminator();
    public string Field38 { get; } = reader.ReadUtf16UnicodeStringWithoutTerminator();
    public string Field39 { get; } = reader.ReadUtf16UnicodeStringWithoutTerminator();
    public string Field40 { get; } = reader.ReadUtf16UnicodeStringWithoutTerminator();
    public int Field41 { get; } = reader.ReadInt32();
    public int Field42 { get; } = reader.ReadInt32();
    public int Field43 { get; } = reader.ReadInt32();
    public int Field44 { get; } = reader.ReadInt32();
    public int Field45 { get; } = reader.ReadInt32();
    public int Field46 { get; } = reader.ReadInt32();
    public int Field47 { get; } = reader.ReadInt32();
    public int Field48 { get; } = reader.ReadInt32();
    public int Field49 { get; } = reader.ReadInt32();
    public int Field50 { get; } = reader.ReadInt32();
}
