// <auto-generated>

using OpenWorker.Res.Attributes;

namespace OpenWorker.UpdateContent.Res.Rows;

[BinaryResourceTable("tb_Customize_View_Weapon")]
public readonly struct CustomizeViewWeaponRow(BinaryReader reader)
{
    public byte Id { get; } = reader.ReadByte();
    public int Field1 { get; } = reader.ReadInt32();
    public int Field2 { get; } = reader.ReadInt32();
    public int Field3 { get; } = reader.ReadInt32();
    public int Field4 { get; } = reader.ReadInt32();
    public int Field5 { get; } = reader.ReadInt32();
}
