// <auto-generated>

using OpenWorker.Extensions;
using OpenWorker.Res.Attributes;

namespace OpenWorker.UpdateContent.Res.Rows;

[BinaryResourceTable("tb_Customize_Info")]
public readonly struct CustomizeInfoRow(BinaryReader reader)
{
    public byte Id { get; } = reader.ReadByte();
    public byte Field1 { get; } = reader.ReadByte();
    public byte Field2 { get; } = reader.ReadByte();
    public byte Field3 { get; } = reader.ReadByte();
    public byte Field4 { get; } = reader.ReadByte();
    public byte Field5 { get; } = reader.ReadByte();
    public byte Field6 { get; } = reader.ReadByte();
    public byte Field7 { get; } = reader.ReadByte();
    public byte Field8 { get; } = reader.ReadByte();
    public byte Field9 { get; } = reader.ReadByte();
    public byte Field10 { get; } = reader.ReadByte();
    public byte Field11 { get; } = reader.ReadByte();
    public string Field12 { get; } = reader.ReadUtf16UnicodeStringWithoutTerminator();
    public string Field13 { get; } = reader.ReadUtf16UnicodeStringWithoutTerminator();
    public string Field14 { get; } = reader.ReadUtf16UnicodeStringWithoutTerminator();
    public string Field15 { get; } = reader.ReadUtf16UnicodeStringWithoutTerminator();
    public string Field16 { get; } = reader.ReadUtf16UnicodeStringWithoutTerminator();
}
