// <auto-generated>

using OpenWorker.Extensions;
using OpenWorker.Res.Attributes;

namespace OpenWorker.UpdateContent.Res.Rows;

[BinaryResourceTable("tb_Daily_Mission")]
public readonly struct DailyMissionRow(BinaryReader reader)
{
    public int Id { get; } = reader.ReadInt32();
    public byte Field1 { get; } = reader.ReadByte();
    public int Field2 { get; } = reader.ReadInt32();
    public int Field3 { get; } = reader.ReadInt32();
    public byte Field4 { get; } = reader.ReadByte();
    public byte Field5 { get; } = reader.ReadByte();
    public int Field6 { get; } = reader.ReadInt32();
    public byte Field7 { get; } = reader.ReadByte();
    public int Field8 { get; } = reader.ReadInt32();
    public int Field9 { get; } = reader.ReadInt32();
    public byte Field10 { get; } = reader.ReadByte();
    public int Field11 { get; } = reader.ReadInt32();
    public int Field12 { get; } = reader.ReadInt32();
    public byte Field13 { get; } = reader.ReadByte();
    public byte Field14 { get; } = reader.ReadByte();
    public string Field15 { get; } = reader.ReadUtf16UnicodeStringWithoutTerminator();
    public string Field16 { get; } = reader.ReadUtf16UnicodeStringWithoutTerminator();
    public int Field17 { get; } = reader.ReadInt32();
    public int Field18 { get; } = reader.ReadInt32();
    public int Field19 { get; } = reader.ReadInt32();
    public byte Field20 { get; } = reader.ReadByte();
    public byte Field21 { get; } = reader.ReadByte();
    public byte Field22 { get; } = reader.ReadByte();
}
