// <auto-generated>

using OpenWorker.Res.Attributes;

namespace OpenWorker.UpdateContent.Res.Rows;

[BinaryResourceTable("tb_Deck_Bonus")]
public readonly struct DeckBonusRow(BinaryReader reader)
{
    public short Id { get; } = reader.ReadInt16();
    public byte Field1 { get; } = reader.ReadByte();
    public byte Field2 { get; } = reader.ReadByte();
    public short Field3 { get; } = reader.ReadInt16();
    public byte Field4 { get; } = reader.ReadByte();
    public float BonusValue { get; } = reader.ReadSingle();
}
