// <auto-generated>

using OpenWorker.Res.Attributes;

namespace OpenWorker.UpdateContent.Res.Rows;

[BinaryResourceTable("tb_Disassemble")]
public readonly struct DisassembleRow(BinaryReader reader)
{
    public int Id { get; } = reader.ReadInt32();
}
