// <auto-generated>

using OpenWorker.Extensions;
using OpenWorker.Res.Attributes;

namespace OpenWorker.UpdateContent.Res.Rows;

[BinaryResourceTable("tb_district")]
public readonly struct DistrictRow(BinaryReader reader)
{
    public short Id { get; } = reader.ReadInt16();
    public short Field1 { get; } = reader.ReadInt16();
    public short Field2 { get; } = reader.ReadInt16();
    public short Field3 { get; } = reader.ReadInt16();
    public string Field4 { get; } = reader.ReadUtf16UnicodeStringWithoutTerminator();
    public string Batch { get; } = reader.ReadUtf16UnicodeStringWithoutTerminator();
    public short Field6 { get; } = reader.ReadInt16();
    public int Field7 { get; } = reader.ReadInt32();
    public int Field8 { get; } = reader.ReadInt32();
    public string Field9 { get; } = reader.ReadUtf16UnicodeStringWithoutTerminator();
    public string Field10 { get; } = reader.ReadUtf16UnicodeStringWithoutTerminator();
    public byte Field11 { get; } = reader.ReadByte();
    public byte Field12 { get; } = reader.ReadByte();
    public string Field13 { get; } = reader.ReadUtf16UnicodeStringWithoutTerminator();
    public byte Field14 { get; } = reader.ReadByte();
}
