// <auto-generated>

using OpenWorker.Extensions;
using OpenWorker.Res;
using OpenWorker.Res.Attributes;

namespace OpenWorker.UpdateContent.Res.Rows;

[BinaryResourceTable("tb_Divergence")]
public readonly struct DivergenceRow(BinaryReader reader)
{
    public int Id { get; } = reader.ReadInt32();
    public int Group { get; } = reader.ReadInt32();
    public int SwapIdentifier { get; } = reader.ReadInt32();
    public byte Level { get; } = reader.ReadByte();
    public byte MaxLevel { get; } = reader.ReadByte();
    public int Next { get; } = reader.ReadInt32();
    public byte NeedLevel { get; } = reader.ReadByte();
    public byte NeedPointCount { get; } = reader.ReadByte();
    public short Field8 { get; } = reader.ReadInt16();
    public byte Field9 { get; } = reader.ReadByte();
    public string DescriptionImage { get; } = reader.ReadUtf16UnicodeStringWithoutTerminator();
    public DivergenceVariant OptionType { get; } = (DivergenceVariant)reader.ReadByte();
    public int OptionValue { get; } = reader.ReadInt32();
    public float SubOptionValue { get; } = reader.ReadSingle();
}
