// <auto-generated>

using OpenWorker.Res.Attributes;

namespace OpenWorker.UpdateContent.Res.Rows;

[BinaryResourceTable("tb_DS_Point")]
public readonly struct DSPointRow(BinaryReader reader)
{
    public short Id { get; } = reader.ReadInt16();
    public short Field1 { get; } = reader.ReadInt16();
    public short Field2 { get; } = reader.ReadInt16();
    public byte Field3 { get; } = reader.ReadByte();
    public byte Field4 { get; } = reader.ReadByte();
    public byte Field5 { get; } = reader.ReadByte();
    public byte Field6 { get; } = reader.ReadByte();
    public byte Field7 { get; } = reader.ReadByte();
    public byte Field8 { get; } = reader.ReadByte();
    public short Field9 { get; } = reader.ReadInt16();
    public short Field10 { get; } = reader.ReadInt16();
    public short Field11 { get; } = reader.ReadInt16();
    public short Field12 { get; } = reader.ReadInt16();
    public short Field13 { get; } = reader.ReadInt16();
    public byte Field14 { get; } = reader.ReadByte();
    public byte Field15 { get; } = reader.ReadByte();
    public byte Field16 { get; } = reader.ReadByte();
    public byte Field17 { get; } = reader.ReadByte();
    public byte Field18 { get; } = reader.ReadByte();
    public int Field19 { get; } = reader.ReadInt32();
    public int Field20 { get; } = reader.ReadInt32();
    public int Field21 { get; } = reader.ReadInt32();
    public int Field22 { get; } = reader.ReadInt32();
    public int Field23 { get; } = reader.ReadInt32();
    public byte Field24 { get; } = reader.ReadByte();
    public byte Field25 { get; } = reader.ReadByte();
    public byte Field26 { get; } = reader.ReadByte();
    public byte Field27 { get; } = reader.ReadByte();
    public byte Field28 { get; } = reader.ReadByte();
}
