// <auto-generated>

using OpenWorker.Extensions;
using OpenWorker.Res.Attributes;

namespace OpenWorker.UpdateContent.Res.Rows;

[BinaryResourceTable("tb_Echelon")]
public readonly struct EchelonRow(BinaryReader reader)
{
    public byte Id { get; } = reader.ReadByte();
    public short Field1 { get; } = reader.ReadInt16();
    public short Field2 { get; } = reader.ReadInt16();
    public string Field3 { get; } = reader.ReadUtf16UnicodeStringWithoutTerminator();
    public string Field4 { get; } = reader.ReadUtf16UnicodeStringWithoutTerminator();
    public int Field5 { get; } = reader.ReadInt32();
}
