// <auto-generated>

using OpenWorker.Extensions;
using OpenWorker.Res.Attributes;

namespace OpenWorker.UpdateContent.Res.Rows;

[BinaryResourceTable("tb_FX_BattleMaterial_Link")]
public readonly struct FXBattleMaterialLinkRow(BinaryReader reader)
{
    public byte Id { get; } = reader.ReadByte();
    public string Field1 { get; } = reader.ReadUtf16UnicodeStringWithoutTerminator();
    public byte Field2 { get; } = reader.ReadByte();
    public byte Field3 { get; } = reader.ReadByte();
}
