// <auto-generated>

using OpenWorker.Extensions;
using OpenWorker.Res.Attributes;

namespace OpenWorker.UpdateContent.Res.Rows;

[BinaryResourceTable("tb_Gesture")]
public readonly struct GestureRow(BinaryReader reader)
{
    public short Id { get; } = reader.ReadInt16();
    public byte Field1 { get; } = reader.ReadByte();
    public byte Field2 { get; } = reader.ReadByte();
    public byte Field3 { get; } = reader.ReadByte();
    public int Field4 { get; } = reader.ReadInt32();
    public short Field5 { get; } = reader.ReadInt16();
    public int Field6 { get; } = reader.ReadInt32();
    public string Field7 { get; } = reader.ReadUtf16UnicodeStringWithoutTerminator();
    public byte Field8 { get; } = reader.ReadByte();
    public int Field9 { get; } = reader.ReadInt32();
    public int Field10 { get; } = reader.ReadInt32();
    public int Field11 { get; } = reader.ReadInt32();
    public int Field12 { get; } = reader.ReadInt32();
    public string Field13 { get; } = reader.ReadUtf16UnicodeStringWithoutTerminator();
    public string Field14 { get; } = reader.ReadUtf16UnicodeStringWithoutTerminator();
    public string Field15 { get; } = reader.ReadUtf16UnicodeStringWithoutTerminator();
    public int Field16 { get; } = reader.ReadInt32();
    public short Field17 { get; } = reader.ReadInt16();
}
