// <auto-generated>

using OpenWorker.Res.Attributes;

namespace OpenWorker.UpdateContent.Res.Rows;

[BinaryResourceTable("tb_Helper_Reward")]
public readonly struct HelperRewardRow(BinaryReader reader)
{
    public byte Id { get; } = reader.ReadByte();
    public byte Field1 { get; } = reader.ReadByte();
    public short Field2 { get; } = reader.ReadInt16();
    public int Field3 { get; } = reader.ReadInt32();
    public int Field4 { get; } = reader.ReadInt32();
    public int Field5 { get; } = reader.ReadInt32();
    public byte Field6 { get; } = reader.ReadByte();
    public byte Field7 { get; } = reader.ReadByte();
    public byte Field8 { get; } = reader.ReadByte();
}
