// <auto-generated>

using OpenWorker.Extensions;
using OpenWorker.Res.Attributes;

namespace OpenWorker.UpdateContent.Res.Rows;

[BinaryResourceTable("tb_HitVFX")]
public readonly struct HitVFXRow(BinaryReader reader)
{
    public short Id { get; } = reader.ReadInt16();
    public short Field1 { get; } = reader.ReadInt16();
    public short Field2 { get; } = reader.ReadInt16();
    public short Field3 { get; } = reader.ReadInt16();
    public short Field4 { get; } = reader.ReadInt16();
    public short Field5 { get; } = reader.ReadInt16();
    public short Field6 { get; } = reader.ReadInt16();
    public short Field7 { get; } = reader.ReadInt16();
    public string Field8 { get; } = reader.ReadUtf16UnicodeStringWithoutTerminator();
    public string Field9 { get; } = reader.ReadUtf16UnicodeStringWithoutTerminator();
    public string Field10 { get; } = reader.ReadUtf16UnicodeStringWithoutTerminator();
    public string Field11 { get; } = reader.ReadUtf16UnicodeStringWithoutTerminator();
    public string Field12 { get; } = reader.ReadUtf16UnicodeStringWithoutTerminator();
    public string Field13 { get; } = reader.ReadUtf16UnicodeStringWithoutTerminator();
    public string Field14 { get; } = reader.ReadUtf16UnicodeStringWithoutTerminator();
}
