// <auto-generated>

using OpenWorker.Res.Attributes;

namespace OpenWorker.UpdateContent.Res.Rows;

[BinaryResourceTable("tb_Interaction_Item")]
public readonly struct InteractionItemRow(BinaryReader reader)
{
    public int Id { get; } = reader.ReadInt32();
}
