// <auto-generated>

using OpenWorker.Extensions;
using OpenWorker.Res.Attributes;

namespace OpenWorker.UpdateContent.Res.Rows;

[BinaryResourceTable("tb_Interaction_Object")]
public readonly struct InteractionObjectRow(BinaryReader reader)
{
    public int Id { get; } = reader.ReadInt32();
    public byte Field1 { get; } = reader.ReadByte();
    public string Field2 { get; } = reader.ReadUtf16UnicodeStringWithoutTerminator();
    public byte Field3 { get; } = reader.ReadByte();
    public int Field4 { get; } = reader.ReadInt32();
    public byte Field5 { get; } = reader.ReadByte();
    public byte Field6 { get; } = reader.ReadByte();
    public byte Field7 { get; } = reader.ReadByte();
    public string Field8 { get; } = reader.ReadUtf16UnicodeStringWithoutTerminator();
    public byte Field9 { get; } = reader.ReadByte();
    public byte Field10 { get; } = reader.ReadByte();
    public byte Field11 { get; } = reader.ReadByte();
    public int Field12 { get; } = reader.ReadInt32();
    public int Field13 { get; } = reader.ReadInt32();
    public int Field14 { get; } = reader.ReadInt32();
    public int Field15 { get; } = reader.ReadInt32();
    public int Field16 { get; } = reader.ReadInt32();
    public int Field17 { get; } = reader.ReadInt32();
    public int Field18 { get; } = reader.ReadInt32();
    public short Field19 { get; } = reader.ReadInt16();
    public short Field20 { get; } = reader.ReadInt16();
    public int Field21 { get; } = reader.ReadInt32();
    public int Field22 { get; } = reader.ReadInt32();
    public byte Field23 { get; } = reader.ReadByte();
    public int Field24 { get; } = reader.ReadInt32();
    public int Field25 { get; } = reader.ReadInt32();
    public int Field26 { get; } = reader.ReadInt32();
    public int Field27 { get; } = reader.ReadInt32();
    public int Field28 { get; } = reader.ReadInt32();
    public byte Field29 { get; } = reader.ReadByte();
    public string Field30 { get; } = reader.ReadUtf16UnicodeStringWithoutTerminator();
    public string Field31 { get; } = reader.ReadUtf16UnicodeStringWithoutTerminator();
    public string Field32 { get; } = reader.ReadUtf16UnicodeStringWithoutTerminator();
    public string Field33 { get; } = reader.ReadUtf16UnicodeStringWithoutTerminator();
    public string Field34 { get; } = reader.ReadUtf16UnicodeStringWithoutTerminator();
    public string Field35 { get; } = reader.ReadUtf16UnicodeStringWithoutTerminator();
    public string Field36 { get; } = reader.ReadUtf16UnicodeStringWithoutTerminator();
    public string Field37 { get; } = reader.ReadUtf16UnicodeStringWithoutTerminator();
    public string Field38 { get; } = reader.ReadUtf16UnicodeStringWithoutTerminator();
    public string Field39 { get; } = reader.ReadUtf16UnicodeStringWithoutTerminator();
    public float Field40 { get; } = reader.ReadSingle();
    public short Field41 { get; } = reader.ReadInt16();
    public short Field42 { get; } = reader.ReadInt16();
    public short Field43 { get; } = reader.ReadInt16();
    public short Field44 { get; } = reader.ReadInt16();
    public short Field45 { get; } = reader.ReadInt16();
    public short Field46 { get; } = reader.ReadInt16();
}
