// <auto-generated>

using OpenWorker.Res.Attributes;

namespace OpenWorker.UpdateContent.Res.Rows;

[BinaryResourceTable("tb_Inven_Slot_Extend")]
public readonly struct InvenSlotExtendRow(BinaryReader reader)
{
    public byte Id { get; } = reader.ReadByte();
    public byte Field1 { get; } = reader.ReadByte();
    public byte Field2 { get; } = reader.ReadByte();
    public byte Field3 { get; } = reader.ReadByte();
    public int Field4 { get; } = reader.ReadInt32();
    public byte Field5 { get; } = reader.ReadByte();
    public byte Field6 { get; } = reader.ReadByte();
    public byte Field7 { get; } = reader.ReadByte();
    public byte Field8 { get; } = reader.ReadByte();
    public int Field9 { get; } = reader.ReadInt32();
    public byte Field10 { get; } = reader.ReadByte();
    public byte Field11 { get; } = reader.ReadByte();
    public byte Field12 { get; } = reader.ReadByte();
    public byte Field13 { get; } = reader.ReadByte();
    public int Field14 { get; } = reader.ReadInt32();
    public byte Field15 { get; } = reader.ReadByte();
    public byte Field16 { get; } = reader.ReadByte();
    public byte Field17 { get; } = reader.ReadByte();
    public byte Field18 { get; } = reader.ReadByte();
    public int Field19 { get; } = reader.ReadInt32();
    public byte Field20 { get; } = reader.ReadByte();
    public byte Field21 { get; } = reader.ReadByte();
}
