// <auto-generated>

using OpenWorker.Res.Attributes;

namespace OpenWorker.UpdateContent.Res.Rows;

[BinaryResourceTable("tb_Item_RandomBox")]
public readonly struct ItemRandomBoxRow(BinaryReader reader)
{
    public int Id { get; } = reader.ReadInt32();
    public byte Field1 { get; } = reader.ReadByte();
    public int Field2 { get; } = reader.ReadInt32();
    public int Field3 { get; } = reader.ReadInt32();
    public short Field4 { get; } = reader.ReadInt16();
    public short Field5 { get; } = reader.ReadInt16();
    public short Field6 { get; } = reader.ReadInt16();
    public short Field7 { get; } = reader.ReadInt16();
    public short Field8 { get; } = reader.ReadInt16();
    public short Field9 { get; } = reader.ReadInt16();
    public short Field10 { get; } = reader.ReadInt16();
    public short Field11 { get; } = reader.ReadInt16();
    public short Field12 { get; } = reader.ReadInt16();
    public short Field13 { get; } = reader.ReadInt16();
    public short Field14 { get; } = reader.ReadInt16();
    public short Field15 { get; } = reader.ReadInt16();
    public short Field16 { get; } = reader.ReadInt16();
    public short Field17 { get; } = reader.ReadInt16();
    public short Field18 { get; } = reader.ReadInt16();
    public short Field19 { get; } = reader.ReadInt16();
    public short Field20 { get; } = reader.ReadInt16();
    public short Field21 { get; } = reader.ReadInt16();
    public int Field22 { get; } = reader.ReadInt32();
    public int Field23 { get; } = reader.ReadInt32();
    public int Field24 { get; } = reader.ReadInt32();
    public int Field25 { get; } = reader.ReadInt32();
    public int Field26 { get; } = reader.ReadInt32();
    public int Field27 { get; } = reader.ReadInt32();
    public int Field28 { get; } = reader.ReadInt32();
    public int Field29 { get; } = reader.ReadInt32();
    public int Field30 { get; } = reader.ReadInt32();
    public int Field31 { get; } = reader.ReadInt32();
    public int Field32 { get; } = reader.ReadInt32();
    public int Field33 { get; } = reader.ReadInt32();
    public int Field34 { get; } = reader.ReadInt32();
    public int Field35 { get; } = reader.ReadInt32();
    public int Field36 { get; } = reader.ReadInt32();
    public int Field37 { get; } = reader.ReadInt32();
    public int Field38 { get; } = reader.ReadInt32();
    public int Field39 { get; } = reader.ReadInt32();
    public int Field40 { get; } = reader.ReadInt32();
    public int Field41 { get; } = reader.ReadInt32();
    public int Field42 { get; } = reader.ReadInt32();
    public int Field43 { get; } = reader.ReadInt32();
    public int Field44 { get; } = reader.ReadInt32();
    public int Field45 { get; } = reader.ReadInt32();
    public int Field46 { get; } = reader.ReadInt32();
    public int Field47 { get; } = reader.ReadInt32();
    public int Field48 { get; } = reader.ReadInt32();
    public int Field49 { get; } = reader.ReadInt32();
    public int Field50 { get; } = reader.ReadInt32();
    public int Field51 { get; } = reader.ReadInt32();
    public int Field52 { get; } = reader.ReadInt32();
    public int Field53 { get; } = reader.ReadInt32();
}
