// <auto-generated>

using OpenWorker.Res.Attributes;

namespace OpenWorker.UpdateContent.Res.Rows;

[BinaryResourceTable("tb_Item_Repair")]
public readonly struct ItemRepairRow(BinaryReader reader)
{
    public int Id { get; } = reader.ReadInt32();
    public float Field1 { get; } = reader.ReadSingle();
    public float Field2 { get; } = reader.ReadSingle();
    public float Field3 { get; } = reader.ReadSingle();
    public float Field4 { get; } = reader.ReadSingle();
    public float Field5 { get; } = reader.ReadSingle();
    public float Field6 { get; } = reader.ReadSingle();
    public float Field7 { get; } = reader.ReadSingle();
    public float Field8 { get; } = reader.ReadSingle();
    public float Field9 { get; } = reader.ReadSingle();
    public float Field10 { get; } = reader.ReadSingle();
    public float Field11 { get; } = reader.ReadSingle();
    public float Field12 { get; } = reader.ReadSingle();
    public float Field13 { get; } = reader.ReadSingle();
    public float Field14 { get; } = reader.ReadSingle();
    public float Field15 { get; } = reader.ReadSingle();
    public float Field16 { get; } = reader.ReadSingle();
    public float Field17 { get; } = reader.ReadSingle();
    public float Field18 { get; } = reader.ReadSingle();
    public float Field19 { get; } = reader.ReadSingle();
}
