// <auto-generated>

using OpenWorker.Extensions;
using OpenWorker.Res.Attributes;
using OpenWorker.Res.Types;

namespace OpenWorker.UpdateContent.Res.Rows;

[BinaryResourceTable("tb_Item_Classify")]
public readonly struct ItemClassifyRow(BinaryReader reader)
{
    public int Id { get; } = reader.ReadInt32();
    public byte Field1 { get; } = reader.ReadByte();
    public short Field2 { get; } = reader.ReadInt16();
    public byte Field3 { get; } = reader.ReadByte();
    public short Field4 { get; } = reader.ReadInt16();
    public byte Field5 { get; } = reader.ReadByte();
    public short Field6 { get; } = reader.ReadInt16();
    public byte Field7 { get; } = reader.ReadByte();
    public short Field8 { get; } = reader.ReadInt16();
    public byte Field9 { get; } = reader.ReadByte();
    public byte Field10 { get; } = reader.ReadByte();
    public byte Field11 { get; } = reader.ReadByte();
    public byte Field12 { get; } = reader.ReadByte();
    public byte Field13 { get; } = reader.ReadByte();
    public ItemUseType ItemUseType { get; } = (ItemUseType)reader.ReadByte();
    public short Field15 { get; } = reader.ReadInt16();
    public short Field16 { get; } = reader.ReadInt16();
    public string Field17 { get; } = reader.ReadUtf16UnicodeStringWithoutTerminator();
    public string Field18 { get; } = reader.ReadUtf16UnicodeStringWithoutTerminator();
    public string Field19 { get; } = reader.ReadUtf16UnicodeStringWithoutTerminator();
    public string Field20 { get; } = reader.ReadUtf16UnicodeStringWithoutTerminator();
}