// <auto-generated>

using OpenWorker.Extensions;
using OpenWorker.Res.Attributes;

namespace OpenWorker.UpdateContent.Res.Rows;

[BinaryResourceTable("tb_item_information")]
public readonly struct ItemInformationRow(BinaryReader reader)
{
    public int Id { get; } = reader.ReadInt32();
    public string Field1 { get; } = reader.ReadUtf16UnicodeStringWithoutTerminator();
    public short Field2 { get; } = reader.ReadInt16();
}
