// <auto-generated>

using OpenWorker.Res.Attributes;

namespace OpenWorker.UpdateContent.Res.Rows;

[BinaryResourceTable("tb_Item_SetItem")]
public readonly struct ItemSetItemRow(BinaryReader reader)
{
    public int Id { get; } = reader.ReadInt32();
    public short Field1 { get; } = reader.ReadInt16();
    public byte Field2 { get; } = reader.ReadByte();
    public int Field3 { get; } = reader.ReadInt32();
    public int Field4 { get; } = reader.ReadInt32();
    public int Field5 { get; } = reader.ReadInt32();
    public int Field6 { get; } = reader.ReadInt32();
    public int Field7 { get; } = reader.ReadInt32();
    public int Field8 { get; } = reader.ReadInt32();
    public byte Field9 { get; } = reader.ReadByte();
    public byte Field10 { get; } = reader.ReadByte();
    public byte Field11 { get; } = reader.ReadByte();
    public byte Field12 { get; } = reader.ReadByte();
    public byte Field13 { get; } = reader.ReadByte();
    public byte Field14 { get; } = reader.ReadByte();
    public byte Field15 { get; } = reader.ReadByte();
    public byte Field16 { get; } = reader.ReadByte();
    public byte Field17 { get; } = reader.ReadByte();
    public byte Field18 { get; } = reader.ReadByte();
    public short Field19 { get; } = reader.ReadInt16();
    public short Field20 { get; } = reader.ReadInt16();
    public short Field21 { get; } = reader.ReadInt16();
    public short Field22 { get; } = reader.ReadInt16();
    public short Field23 { get; } = reader.ReadInt16();
    public float Field24 { get; } = reader.ReadSingle();
    public float Field25 { get; } = reader.ReadSingle();
    public float Field26 { get; } = reader.ReadSingle();
    public float Field27 { get; } = reader.ReadSingle();
    public float Field28 { get; } = reader.ReadSingle();
    public byte Field29 { get; } = reader.ReadByte();
    public byte Field30 { get; } = reader.ReadByte();
    public byte Field31 { get; } = reader.ReadByte();
    public byte Field32 { get; } = reader.ReadByte();
    public byte Field33 { get; } = reader.ReadByte();
    public short Field34 { get; } = reader.ReadInt16();
    public short Field35 { get; } = reader.ReadInt16();
    public short Field36 { get; } = reader.ReadInt16();
    public short Field37 { get; } = reader.ReadInt16();
    public short Field38 { get; } = reader.ReadInt16();
    public float Field39 { get; } = reader.ReadSingle();
    public float Field40 { get; } = reader.ReadSingle();
    public float Field41 { get; } = reader.ReadSingle();
    public float Field42 { get; } = reader.ReadSingle();
    public float Field43 { get; } = reader.ReadSingle();
    public byte Field44 { get; } = reader.ReadByte();
    public byte Field45 { get; } = reader.ReadByte();
    public byte Field46 { get; } = reader.ReadByte();
    public byte Field47 { get; } = reader.ReadByte();
    public byte Field48 { get; } = reader.ReadByte();
    public short Field49 { get; } = reader.ReadInt16();
    public short Field50 { get; } = reader.ReadInt16();
    public short Field51 { get; } = reader.ReadInt16();
    public short Field52 { get; } = reader.ReadInt16();
    public short Field53 { get; } = reader.ReadInt16();
    public float Field54 { get; } = reader.ReadSingle();
    public float Field55 { get; } = reader.ReadSingle();
    public float Field56 { get; } = reader.ReadSingle();
    public float Field57 { get; } = reader.ReadSingle();
    public float Field58 { get; } = reader.ReadSingle();
    public byte Field59 { get; } = reader.ReadByte();
    public byte Field60 { get; } = reader.ReadByte();
    public byte Field61 { get; } = reader.ReadByte();
    public byte Field62 { get; } = reader.ReadByte();
    public byte Field63 { get; } = reader.ReadByte();
    public short Field64 { get; } = reader.ReadInt16();
    public short Field65 { get; } = reader.ReadInt16();
    public short Field66 { get; } = reader.ReadInt16();
    public short Field67 { get; } = reader.ReadInt16();
    public short Field68 { get; } = reader.ReadInt16();
    public float Field69 { get; } = reader.ReadSingle();
    public float Field70 { get; } = reader.ReadSingle();
    public float Field71 { get; } = reader.ReadSingle();
    public float Field72 { get; } = reader.ReadSingle();
    public float Field73 { get; } = reader.ReadSingle();
}
