// <auto-generated>

using OpenWorker.Extensions;
using OpenWorker.Res.Attributes;

namespace OpenWorker.UpdateContent.Res.Rows;

[BinaryResourceTable("tb_Item")]
public readonly struct ItemRow(BinaryReader reader)
{
    public int Id { get; } = reader.ReadInt32();
    public int Classify { get; } = reader.ReadInt32();
    public byte Field2 { get; } = reader.ReadByte();
    public byte Field3 { get; } = reader.ReadByte();
    public short Field4 { get; } = reader.ReadInt16();
    public int Field5 { get; } = reader.ReadInt32();
    public int Price { get; } = reader.ReadInt32();
    public short Stack { get; } = reader.ReadInt16();
    public byte Field8 { get; } = reader.ReadByte();
    public int Field9 { get; } = reader.ReadInt32();
    public int Field10 { get; } = reader.ReadInt32();
    public int Field11 { get; } = reader.ReadInt32();
    public short Field12 { get; } = reader.ReadInt16();
    public byte Field13 { get; } = reader.ReadByte();
    public byte Field14 { get; } = reader.ReadByte();
    public byte Field15 { get; } = reader.ReadByte();
    public byte Field16 { get; } = reader.ReadByte();
    public int Field17 { get; } = reader.ReadInt32();
    public string Field18 { get; } = reader.ReadUtf16UnicodeStringWithoutTerminator();
    public byte Field19 { get; } = reader.ReadByte();
    public byte Field20 { get; } = reader.ReadByte();
    public int Field21 { get; } = reader.ReadInt32();
    public int Field22 { get; } = reader.ReadInt32();
    public int Field23 { get; } = reader.ReadInt32();
    public int Field24 { get; } = reader.ReadInt32();
    public byte Field25 { get; } = reader.ReadByte();
    public byte Field26 { get; } = reader.ReadByte();
    public byte Field27 { get; } = reader.ReadByte();
    public byte Field28 { get; } = reader.ReadByte();
    public byte Field29 { get; } = reader.ReadByte();
    public short Field30 { get; } = reader.ReadInt16();
    public short Field31 { get; } = reader.ReadInt16();
    public short Field32 { get; } = reader.ReadInt16();
    public short Field33 { get; } = reader.ReadInt16();
    public short Field34 { get; } = reader.ReadInt16();
    public int Field35 { get; } = reader.ReadInt32();
    public int Field36 { get; } = reader.ReadInt32();
    public int Field37 { get; } = reader.ReadInt32();
    public int Field38 { get; } = reader.ReadInt32();
    public int Field39 { get; } = reader.ReadInt32();
    public int Option { get; } = reader.ReadInt32();
    public int Socket { get; } = reader.ReadInt32();
    public int Field42 { get; } = reader.ReadInt32();
    public short Reinforce { get; } = reader.ReadInt16();
    public int Field44 { get; } = reader.ReadInt32();
    public short Field45 { get; } = reader.ReadInt16();
    public int Field46 { get; } = reader.ReadInt32();
    public byte Field47 { get; } = reader.ReadByte();
    public int Field48 { get; } = reader.ReadInt32();
    public byte Field49 { get; } = reader.ReadByte();
    public short Field50 { get; } = reader.ReadInt16();
    public int Field51 { get; } = reader.ReadInt32();
    public short Field52 { get; } = reader.ReadInt16();
    public byte Field53 { get; } = reader.ReadByte();
    public byte Field54 { get; } = reader.ReadByte();
    public int Field55 { get; } = reader.ReadInt32();
    public byte Field56 { get; } = reader.ReadByte();
    public int Field57 { get; } = reader.ReadInt32();
    public byte Field58 { get; } = reader.ReadByte();
    public byte Field59 { get; } = reader.ReadByte();
}
