// <auto-generated>

using OpenWorker.Extensions;
using OpenWorker.Res.Attributes;

namespace OpenWorker.UpdateContent.Res.Rows;

[BinaryResourceTable("tb_item_script")]
public readonly struct ItemScriptRow(BinaryReader reader)
{
    public int Id { get; } = reader.ReadInt32();
    public string Field1 { get; } = reader.ReadUtf16UnicodeStringWithoutTerminator();
    public string Field2 { get; } = reader.ReadUtf16UnicodeStringWithoutTerminator();
    public string Field3 { get; } = reader.ReadUtf16UnicodeStringWithoutTerminator();
    public string Field4 { get; } = reader.ReadUtf16UnicodeStringWithoutTerminator();
    public string Field5 { get; } = reader.ReadUtf16UnicodeStringWithoutTerminator();
    public string Field6 { get; } = reader.ReadUtf16UnicodeStringWithoutTerminator();
    public byte Field7 { get; } = reader.ReadByte();
    public byte Field8 { get; } = reader.ReadByte();
    public byte Field9 { get; } = reader.ReadByte();
    public byte Field10 { get; } = reader.ReadByte();
    public byte Field11 { get; } = reader.ReadByte();
    public string Field12 { get; } = reader.ReadUtf16UnicodeStringWithoutTerminator();
    public string Field13 { get; } = reader.ReadUtf16UnicodeStringWithoutTerminator();
}
