// <auto-generated>

using OpenWorker.Res.Attributes;

namespace OpenWorker.UpdateContent.Res.Rows;

[BinaryResourceTable("tb_Levelup_Point")]
public readonly struct LevelupPointRow(BinaryReader reader)
{
    public byte Id { get; } = reader.ReadByte();
    public int Field1 { get; } = reader.ReadInt32();
    public short Field2 { get; } = reader.ReadInt16();
}
