// <auto-generated>

using OpenWorker.Res.Attributes;

namespace OpenWorker.UpdateContent.Res.Rows;

[BinaryResourceTable("tb_Loading")]
public readonly struct LoadingRow(BinaryReader reader)
{
    public byte Id { get; } = reader.ReadByte();
    public short Field1 { get; } = reader.ReadInt16();
    public byte Field2 { get; } = reader.ReadByte();
    public short Field3 { get; } = reader.ReadInt16();
    public short Field4 { get; } = reader.ReadInt16();
}
