// <auto-generated>

using OpenWorker.Res.Attributes;

namespace OpenWorker.UpdateContent.Res.Rows;

[BinaryResourceTable("tb_Make")]
public readonly struct MakeRow(BinaryReader reader)
{
    public int Id { get; } = reader.ReadInt32();
    public int Field1 { get; } = reader.ReadInt32();
    public int Field2 { get; } = reader.ReadInt32();
    public int Field3 { get; } = reader.ReadInt32();
    public int Field4 { get; } = reader.ReadInt32();
    public int Field5 { get; } = reader.ReadInt32();
    public int Field6 { get; } = reader.ReadInt32();
    public int Field7 { get; } = reader.ReadInt32();
    public int Field8 { get; } = reader.ReadInt32();
    public int Field9 { get; } = reader.ReadInt32();
    public int Field10 { get; } = reader.ReadInt32();
    public short Field11 { get; } = reader.ReadInt16();
    public short Field12 { get; } = reader.ReadInt16();
    public short Field13 { get; } = reader.ReadInt16();
    public short Field14 { get; } = reader.ReadInt16();
    public short Field15 { get; } = reader.ReadInt16();
    public int Field16 { get; } = reader.ReadInt32();
    public short Field17 { get; } = reader.ReadInt16();
}
