// <auto-generated>

using OpenWorker.Extensions;
using OpenWorker.Res.Attributes;

namespace OpenWorker.UpdateContent.Res.Rows;

[BinaryResourceTable("tb_Maze_Info")]
public readonly struct MazeInfoRow(BinaryReader reader)
{
    public short Id { get; } = reader.ReadInt16();
    public byte Field1 { get; } = reader.ReadByte();
    public short Field2 { get; } = reader.ReadInt16();
    public byte Field3 { get; } = reader.ReadByte();
    public byte Field4 { get; } = reader.ReadByte();
    public short Field5 { get; } = reader.ReadInt16();
    public byte Field6 { get; } = reader.ReadByte();
    public byte Field7 { get; } = reader.ReadByte();
    public byte Field8 { get; } = reader.ReadByte();
    public byte Field9 { get; } = reader.ReadByte();
    public byte Field10 { get; } = reader.ReadByte();
    public short NextId { get; } = reader.ReadInt16();
    public string Batch { get; } = reader.ReadUtf16UnicodeStringWithoutTerminator();
    public string Field13 { get; } = reader.ReadUtf16UnicodeStringWithoutTerminator();
    public string Script { get; } = reader.ReadUtf16UnicodeStringWithoutTerminator();
    public string Field15 { get; } = reader.ReadUtf16UnicodeStringWithoutTerminator();
    public string Field16 { get; } = reader.ReadUtf16UnicodeStringWithoutTerminator();
    public string Field17 { get; } = reader.ReadUtf16UnicodeStringWithoutTerminator();
    public short Field18 { get; } = reader.ReadInt16();
    public short Field19 { get; } = reader.ReadInt16();
    public byte Field20 { get; } = reader.ReadByte();
    public short Field21 { get; } = reader.ReadInt16();
    public string Field22 { get; } = reader.ReadUtf16UnicodeStringWithoutTerminator();
    public string Field23 { get; } = reader.ReadUtf16UnicodeStringWithoutTerminator();
    public short Field24 { get; } = reader.ReadInt16();
    public short Field25 { get; } = reader.ReadInt16();
    public int Field26 { get; } = reader.ReadInt32();
    public int Field27 { get; } = reader.ReadInt32();
    public int Field28 { get; } = reader.ReadInt32();
    public int Field29 { get; } = reader.ReadInt32();
    public int Field30 { get; } = reader.ReadInt32();
    public int Field31 { get; } = reader.ReadInt32();
    public int Field32 { get; } = reader.ReadInt32();
    public byte Field33 { get; } = reader.ReadByte();
}
