// <auto-generated>

using OpenWorker.Extensions;
using OpenWorker.Res.Attributes;

namespace OpenWorker.UpdateContent.Res.Rows;

[BinaryResourceTable("tb_MazeReward_GoldDirect")]
public readonly struct MazeRewardGoldDirectRow(BinaryReader reader)
{
    public int Id { get; } = reader.ReadInt32();
    public int Field1 { get; } = reader.ReadInt32();
    public int Field2 { get; } = reader.ReadInt32();
    public int Field3 { get; } = reader.ReadInt32();
    public string Field4 { get; } = reader.ReadUtf16UnicodeStringWithoutTerminator();
    public string Field5 { get; } = reader.ReadUtf16UnicodeStringWithoutTerminator();
    public string Field6 { get; } = reader.ReadUtf16UnicodeStringWithoutTerminator();
    public string Field7 { get; } = reader.ReadUtf16UnicodeStringWithoutTerminator();
}
