// <auto-generated>

using OpenWorker.Res.Attributes;

namespace OpenWorker.UpdateContent.Res.Rows;

[BinaryResourceTable("tb_MazeReward_PartyValue")]
public readonly struct MazeRewardPartyValueRow(BinaryReader reader)
{
    public byte Id { get; } = reader.ReadByte();
}
