// <auto-generated>

using OpenWorker.Res.Attributes;

namespace OpenWorker.UpdateContent.Res.Rows;

[BinaryResourceTable("tb_MazeReward_SoulVaper")]
public readonly struct MazeRewardSoulVaperRow(BinaryReader reader)
{
    public short Id { get; } = reader.ReadInt16();
}
