// <auto-generated>

using OpenWorker.Res.Attributes;

namespace OpenWorker.UpdateContent.Res.Rows;

[BinaryResourceTable("tb_MazeReward_Level")]
public readonly struct MazeRewardLevelRow(BinaryReader reader)
{
    public byte Id { get; } = reader.ReadByte();
}
