// <auto-generated>

using OpenWorker.Res.Attributes;

namespace OpenWorker.UpdateContent.Res.Rows;

[BinaryResourceTable("tb_MazeReward_Time")]
public readonly struct MazeRewardTimeRow(BinaryReader reader)
{
    public short Id { get; } = reader.ReadInt16();
}
