// <auto-generated>

using OpenWorker.Res.Attributes;

namespace OpenWorker.UpdateContent.Res.Rows;

[BinaryResourceTable("tb_MazeReward_Rank")]
public readonly struct MazeRewardRankRow(BinaryReader reader)
{
    public byte Id { get; } = reader.ReadByte();
    public byte Field1 { get; } = reader.ReadByte();
}
