// <auto-generated>

using OpenWorker.Res.Attributes;

namespace OpenWorker.UpdateContent.Res.Rows;

[BinaryResourceTable("tb_MessageNotifyer")]
public readonly struct MessageNotifyerRow(BinaryReader reader)
{
    public int Id { get; } = reader.ReadInt32();
    public sbyte Field1 { get; } = reader.ReadSByte();
    public sbyte Field2 { get; } = reader.ReadSByte();
    public short Field3 { get; } = reader.ReadInt16();
    public short Field4 { get; } = reader.ReadInt16();
    public short Field5 { get; } = reader.ReadInt16();
    public int Field6 { get; } = reader.ReadInt32();
    public int Field7 { get; } = reader.ReadInt32();
}
