// <auto-generated>

using OpenWorker.Extensions;
using OpenWorker.Res.Attributes;

namespace OpenWorker.UpdateContent.Res.Rows;

[BinaryResourceTable("tb_Monster_Broken_Parts")]
public readonly struct MonsterBrokenPartsRow(BinaryReader reader)
{
    public int Id { get; } = reader.ReadInt32();
    public string Field1 { get; } = reader.ReadUtf16UnicodeStringWithoutTerminator();
    public string Field2 { get; } = reader.ReadUtf16UnicodeStringWithoutTerminator();
    public int Field3 { get; } = reader.ReadInt32();
    public int Field4 { get; } = reader.ReadInt32();
    public int Field5 { get; } = reader.ReadInt32();
    public string Field6 { get; } = reader.ReadUtf16UnicodeStringWithoutTerminator();
    public int Field7 { get; } = reader.ReadInt32();
    public int Field8 { get; } = reader.ReadInt32();
    public string Field9 { get; } = reader.ReadUtf16UnicodeStringWithoutTerminator();
}
