// <auto-generated>

using OpenWorker.Extensions;
using OpenWorker.Res.Attributes;

namespace OpenWorker.UpdateContent.Res.Rows;

[BinaryResourceTable("tb_Myroom_Furniture")]
public readonly struct MyroomFurnitureRow(BinaryReader reader)
{
    public int Id { get; } = reader.ReadInt32();
    public int Field1 { get; } = reader.ReadInt32();
    public string Field2 { get; } = reader.ReadUtf16UnicodeStringWithoutTerminator();
    public int Field3 { get; } = reader.ReadInt32();
    public int Field4 { get; } = reader.ReadInt32();
    public int Field5 { get; } = reader.ReadInt32();
    public int Field6 { get; } = reader.ReadInt32();
    public int Field7 { get; } = reader.ReadInt32();
    public int Field8 { get; } = reader.ReadInt32();
    public int Field9 { get; } = reader.ReadInt32();
    public int Field10 { get; } = reader.ReadInt32();
    public int Field11 { get; } = reader.ReadInt32();
    public int Field12 { get; } = reader.ReadInt32();
    public int Field13 { get; } = reader.ReadInt32();
    public int Field14 { get; } = reader.ReadInt32();
    public string Field15 { get; } = reader.ReadUtf16UnicodeStringWithoutTerminator();
    public int Field16 { get; } = reader.ReadInt32();
    public int Field17 { get; } = reader.ReadInt32();
    public string Field18 { get; } = reader.ReadUtf16UnicodeStringWithoutTerminator();
    public int Field19 { get; } = reader.ReadInt32();
    public int Field20 { get; } = reader.ReadInt32();
    public string Field21 { get; } = reader.ReadUtf16UnicodeStringWithoutTerminator();
    public int Field22 { get; } = reader.ReadInt32();
    public int Field23 { get; } = reader.ReadInt32();
    public string Field24 { get; } = reader.ReadUtf16UnicodeStringWithoutTerminator();
    public int Field25 { get; } = reader.ReadInt32();
    public string Field26 { get; } = reader.ReadUtf16UnicodeStringWithoutTerminator();
    public string Field27 { get; } = reader.ReadUtf16UnicodeStringWithoutTerminator();
    public int Field28 { get; } = reader.ReadInt32();
    public int Field29 { get; } = reader.ReadInt32();
    public int Field30 { get; } = reader.ReadInt32();
    public int Field31 { get; } = reader.ReadInt32();
    public string Field32 { get; } = reader.ReadUtf16UnicodeStringWithoutTerminator();
    public string Field33 { get; } = reader.ReadUtf16UnicodeStringWithoutTerminator();
    public string Field34 { get; } = reader.ReadUtf16UnicodeStringWithoutTerminator();
    public string Field35 { get; } = reader.ReadUtf16UnicodeStringWithoutTerminator();
    public string Field36 { get; } = reader.ReadUtf16UnicodeStringWithoutTerminator();
    public string Field37 { get; } = reader.ReadUtf16UnicodeStringWithoutTerminator();
    public string Field38 { get; } = reader.ReadUtf16UnicodeStringWithoutTerminator();
    public string Field39 { get; } = reader.ReadUtf16UnicodeStringWithoutTerminator();
    public string Field40 { get; } = reader.ReadUtf16UnicodeStringWithoutTerminator();
    public string Field41 { get; } = reader.ReadUtf16UnicodeStringWithoutTerminator();
    public string Field42 { get; } = reader.ReadUtf16UnicodeStringWithoutTerminator();
    public string Field43 { get; } = reader.ReadUtf16UnicodeStringWithoutTerminator();
}
