// <auto-generated>

using OpenWorker.Res.Attributes;

namespace OpenWorker.UpdateContent.Res.Rows;

[BinaryResourceTable("tb_Navigation_Warpmap")]
public readonly struct NavigationWarpmapRow(BinaryReader reader)
{
    public int Id { get; } = reader.ReadInt32();
    public short Field1 { get; } = reader.ReadInt16();
    public byte Field2 { get; } = reader.ReadByte();
    public short Field3 { get; } = reader.ReadInt16();
    public short Field4 { get; } = reader.ReadInt16();
    public int Field5 { get; } = reader.ReadInt32();
    public short Field6 { get; } = reader.ReadInt16();
    public short Field7 { get; } = reader.ReadInt16();
    public short Field8 { get; } = reader.ReadInt16();
    public int Field9 { get; } = reader.ReadInt32();
    public short Field10 { get; } = reader.ReadInt16();
}
