// <auto-generated>

using OpenWorker.Extensions;
using OpenWorker.Res.Attributes;

namespace OpenWorker.UpdateContent.Res.Rows;

[BinaryResourceTable("tb_NPC")]
public readonly struct NPCRow(BinaryReader reader)
{
    public int Id { get; } = reader.ReadInt32();
    public short Field1 { get; } = reader.ReadInt16();
    public byte Field2 { get; } = reader.ReadByte();
    public string Field3 { get; } = reader.ReadUtf16UnicodeStringWithoutTerminator();
    public int Field4 { get; } = reader.ReadInt32();
    public int Field5 { get; } = reader.ReadInt32();
    public int Field6 { get; } = reader.ReadInt32();
    public int Field7 { get; } = reader.ReadInt32();
    public int Field8 { get; } = reader.ReadInt32();
    public byte Field9 { get; } = reader.ReadByte();
    public int Field10 { get; } = reader.ReadInt32();
    public byte Level { get; } = reader.ReadByte();
    public byte Field12 { get; } = reader.ReadByte();
    public int Field13 { get; } = reader.ReadInt32();
    public byte Field14 { get; } = reader.ReadByte();
    public int Field15 { get; } = reader.ReadInt32();
    public byte Field16 { get; } = reader.ReadByte();
    public int Field17 { get; } = reader.ReadInt32();
    public short Field18 { get; } = reader.ReadInt16();
    public short Field19 { get; } = reader.ReadInt16();
    public short Field20 { get; } = reader.ReadInt16();
    public byte Field21 { get; } = reader.ReadByte();
    public byte Field22 { get; } = reader.ReadByte();
    public byte Field23 { get; } = reader.ReadByte();
    public byte Field24 { get; } = reader.ReadByte();
    public byte Field25 { get; } = reader.ReadByte();
    public byte Field26 { get; } = reader.ReadByte();
    public short Field27 { get; } = reader.ReadInt16();
    public short Field28 { get; } = reader.ReadInt16();
    public short Field29 { get; } = reader.ReadInt16();
    public string Field30 { get; } = reader.ReadUtf16UnicodeStringWithoutTerminator();
    public byte Field31 { get; } = reader.ReadByte();
    public int Field32 { get; } = reader.ReadInt32();
    public int Field33 { get; } = reader.ReadInt32();
    public string Field34 { get; } = reader.ReadUtf16UnicodeStringWithoutTerminator();
    public short Field35 { get; } = reader.ReadInt16();
    public short Field36 { get; } = reader.ReadInt16();
    public short Field37 { get; } = reader.ReadInt16();
    public short Field38 { get; } = reader.ReadInt16();
    public short Field39 { get; } = reader.ReadInt16();
    public short Field40 { get; } = reader.ReadInt16();
    public short Field41 { get; } = reader.ReadInt16();
    public short Field42 { get; } = reader.ReadInt16();
    public short Field43 { get; } = reader.ReadInt16();
    public short Field44 { get; } = reader.ReadInt16();
    public short Field45 { get; } = reader.ReadInt16();
    public short Field46 { get; } = reader.ReadInt16();
    public short Field47 { get; } = reader.ReadInt16();
    public short Field48 { get; } = reader.ReadInt16();
    public short Field49 { get; } = reader.ReadInt16();
    public short Field50 { get; } = reader.ReadInt16();
    public string Field51 { get; } = reader.ReadUtf16UnicodeStringWithoutTerminator();
    public string Field52 { get; } = reader.ReadUtf16UnicodeStringWithoutTerminator();
    public string Field53 { get; } = reader.ReadUtf16UnicodeStringWithoutTerminator();
    public string Field54 { get; } = reader.ReadUtf16UnicodeStringWithoutTerminator();
    public string Field55 { get; } = reader.ReadUtf16UnicodeStringWithoutTerminator();
}
