// <auto-generated>

using OpenWorker.Extensions;
using OpenWorker.Res.Attributes;

namespace OpenWorker.UpdateContent.Res.Rows;

[BinaryResourceTable("tb_NPC_Script")]
public readonly struct NPCScriptRow(BinaryReader reader)
{
    public int Id { get; } = reader.ReadInt32();
    public string Field1 { get; } = reader.ReadUtf16UnicodeStringWithoutTerminator();
}
