// <auto-generated>

using OpenWorker.Res.Attributes;

namespace OpenWorker.UpdateContent.Res.Rows;

[BinaryResourceTable("tb_PartyRevise")]
public readonly struct PartyReviseRow(BinaryReader reader)
{
    public short Id { get; } = reader.ReadInt16();
    public short Field1 { get; } = reader.ReadInt16();
    public byte Field2 { get; } = reader.ReadByte();
    public int Field3 { get; } = reader.ReadInt32();
}
