// <auto-generated>

using OpenWorker.Res.Attributes;

namespace OpenWorker.UpdateContent.Res.Rows;

[BinaryResourceTable("tb_PreSet")]
public readonly struct PreSetRow(BinaryReader reader)
{
    public short Id { get; } = reader.ReadInt16();
    public short Field1 { get; } = reader.ReadInt16();
    public byte Field2 { get; } = reader.ReadByte();
    public int Field3 { get; } = reader.ReadInt32();
    public int Field4 { get; } = reader.ReadInt32();
    public int Field5 { get; } = reader.ReadInt32();
    public int Field6 { get; } = reader.ReadInt32();
}
