// <auto-generated>

using OpenWorker.Extensions;
using OpenWorker.Res.Attributes;

namespace OpenWorker.UpdateContent.Res.Rows;

[BinaryResourceTable("tb_Quest_Script")]
public readonly struct QuestScriptRow(BinaryReader reader)
{
    public int Id { get; } = reader.ReadInt32();
    public string Field1 { get; } = reader.ReadUtf16UnicodeStringWithoutTerminator();
    public string Field2 { get; } = reader.ReadUtf16UnicodeStringWithoutTerminator();
    public string Field3 { get; } = reader.ReadUtf16UnicodeStringWithoutTerminator();
    public string Field4 { get; } = reader.ReadUtf16UnicodeStringWithoutTerminator();
    public string Field5 { get; } = reader.ReadUtf16UnicodeStringWithoutTerminator();
}
