// <auto-generated>

using OpenWorker.Extensions;
using OpenWorker.Res.Attributes;

namespace OpenWorker.UpdateContent.Res.Rows;

[BinaryResourceTable("tb_Quest_Condition")]
public readonly struct QuestConditionRow(BinaryReader reader)
{
    public int Id { get; } = reader.ReadInt32();
    public byte Field1 { get; } = reader.ReadByte();
    public int Field2 { get; } = reader.ReadInt32();
    public byte Field3 { get; } = reader.ReadByte();
    public int Field4 { get; } = reader.ReadInt32();
    public int Field5 { get; } = reader.ReadInt32();
    public byte Field6 { get; } = reader.ReadByte();
    public int Field7 { get; } = reader.ReadInt32();
    public int Field8 { get; } = reader.ReadInt32();
    public int Field9 { get; } = reader.ReadInt32();
    public int Field10 { get; } = reader.ReadInt32();
    public int Field11 { get; } = reader.ReadInt32();
    public int Field12 { get; } = reader.ReadInt32();
    public int Field13 { get; } = reader.ReadInt32();
    public int Field14 { get; } = reader.ReadInt32();
    public int Field15 { get; } = reader.ReadInt32();
    public int Field16 { get; } = reader.ReadInt32();
    public int Field17 { get; } = reader.ReadInt32();
    public int Field18 { get; } = reader.ReadInt32();
    public int Field19 { get; } = reader.ReadInt32();
    public int Field20 { get; } = reader.ReadInt32();
    public byte Field21 { get; } = reader.ReadByte();
    public int Field22 { get; } = reader.ReadInt32();
    public int Field23 { get; } = reader.ReadInt32();
    public byte Field24 { get; } = reader.ReadByte();
    public byte Field25 { get; } = reader.ReadByte();
    public int Field26 { get; } = reader.ReadInt32();
    public int Field27 { get; } = reader.ReadInt32();
    public byte Field28 { get; } = reader.ReadByte();
    public byte Field29 { get; } = reader.ReadByte();
    public int Field30 { get; } = reader.ReadInt32();
    public int Field31 { get; } = reader.ReadInt32();
    public int Field32 { get; } = reader.ReadInt32();
    public string Field33 { get; } = reader.ReadUtf16UnicodeStringWithoutTerminator();
}
