// <auto-generated>

using OpenWorker.Res.Attributes;

namespace OpenWorker.UpdateContent.Res.Rows;

[BinaryResourceTable("tb_Random_Get")]
public readonly struct RandomGetRow(BinaryReader reader)
{
    public short Id { get; } = reader.ReadInt16();
    public int Field1 { get; } = reader.ReadInt32();
    public int Field2 { get; } = reader.ReadInt32();
    public int Field3 { get; } = reader.ReadInt32();
    public int Field4 { get; } = reader.ReadInt32();
    public int Field5 { get; } = reader.ReadInt32();
    public int Field6 { get; } = reader.ReadInt32();
    public int Field7 { get; } = reader.ReadInt32();
    public int Field8 { get; } = reader.ReadInt32();
    public int Field9 { get; } = reader.ReadInt32();
    public int Field10 { get; } = reader.ReadInt32();
    public int Field11 { get; } = reader.ReadInt32();
    public int Field12 { get; } = reader.ReadInt32();
    public int Field13 { get; } = reader.ReadInt32();
    public int Field14 { get; } = reader.ReadInt32();
    public int Field15 { get; } = reader.ReadInt32();
    public int Field16 { get; } = reader.ReadInt32();
    public int Field17 { get; } = reader.ReadInt32();
    public int Field18 { get; } = reader.ReadInt32();
    public int Field19 { get; } = reader.ReadInt32();
    public int Field20 { get; } = reader.ReadInt32();
    public int Field21 { get; } = reader.ReadInt32();
    public int Field22 { get; } = reader.ReadInt32();
    public int Field23 { get; } = reader.ReadInt32();
    public int Field24 { get; } = reader.ReadInt32();
    public int Field25 { get; } = reader.ReadInt32();
    public int Field26 { get; } = reader.ReadInt32();
    public int Field27 { get; } = reader.ReadInt32();
    public int Field28 { get; } = reader.ReadInt32();
    public int Field29 { get; } = reader.ReadInt32();
    public int Field30 { get; } = reader.ReadInt32();
    public byte Field31 { get; } = reader.ReadByte();
    public byte Field32 { get; } = reader.ReadByte();
    public byte Field33 { get; } = reader.ReadByte();
    public byte Field34 { get; } = reader.ReadByte();
    public byte Field35 { get; } = reader.ReadByte();
    public byte Field36 { get; } = reader.ReadByte();
    public byte Field37 { get; } = reader.ReadByte();
    public byte Field38 { get; } = reader.ReadByte();
    public byte Field39 { get; } = reader.ReadByte();
    public byte Field40 { get; } = reader.ReadByte();
    public byte Field41 { get; } = reader.ReadByte();
    public byte Field42 { get; } = reader.ReadByte();
    public byte Field43 { get; } = reader.ReadByte();
    public byte Field44 { get; } = reader.ReadByte();
    public byte Field45 { get; } = reader.ReadByte();
    public byte Field46 { get; } = reader.ReadByte();
    public byte Field47 { get; } = reader.ReadByte();
    public byte Field48 { get; } = reader.ReadByte();
    public byte Field49 { get; } = reader.ReadByte();
    public byte Field50 { get; } = reader.ReadByte();
    public byte Field51 { get; } = reader.ReadByte();
    public byte Field52 { get; } = reader.ReadByte();
    public byte Field53 { get; } = reader.ReadByte();
    public byte Field54 { get; } = reader.ReadByte();
    public byte Field55 { get; } = reader.ReadByte();
    public byte Field56 { get; } = reader.ReadByte();
    public byte Field57 { get; } = reader.ReadByte();
    public byte Field58 { get; } = reader.ReadByte();
    public byte Field59 { get; } = reader.ReadByte();
    public byte Field60 { get; } = reader.ReadByte();
}
