// <auto-generated>

using OpenWorker.Res.Attributes;

namespace OpenWorker.UpdateContent.Res.Rows;

[BinaryResourceTable("tb_Random_Get_Group")]
public readonly struct RandomGetGroupRow(BinaryReader reader)
{
    public short Id { get; } = reader.ReadInt16();
    public int Field1 { get; } = reader.ReadInt32();
    public byte Field2 { get; } = reader.ReadByte();
    public byte Field3 { get; } = reader.ReadByte();
    public short Field4 { get; } = reader.ReadInt16();
    public byte Field5 { get; } = reader.ReadByte();
    public byte Field6 { get; } = reader.ReadByte();
    public short Field7 { get; } = reader.ReadInt16();
    public byte Field8 { get; } = reader.ReadByte();
    public byte Field9 { get; } = reader.ReadByte();
}
