// <auto-generated>

using OpenWorker.Res.Attributes;

namespace OpenWorker.UpdateContent.Res.Rows;

[BinaryResourceTable("tb_Random_Option")]
public readonly struct RandomOptionRow(BinaryReader reader)
{
    public int Id { get; } = reader.ReadInt32();
    public byte Min { get; } = reader.ReadByte();
    public byte Max { get; } = reader.ReadByte();
}
