// <auto-generated>

using OpenWorker.Res.Attributes;

namespace OpenWorker.UpdateContent.Res.Rows;

[BinaryResourceTable("tb_Rank_Reward")]
public readonly struct RankRewardRow(BinaryReader reader)
{
    public short Id { get; } = reader.ReadInt16();
    public short Field1 { get; } = reader.ReadInt16();
    public short Field2 { get; } = reader.ReadInt16();
    public int Field3 { get; } = reader.ReadInt32();
    public byte Field4 { get; } = reader.ReadByte();
}
