// <auto-generated>

using OpenWorker.Res.Attributes;

namespace OpenWorker.UpdateContent.Res.Rows;

[BinaryResourceTable("tb_Reinforce_Exchange")]
public readonly struct ReinforceExchangeRow(BinaryReader reader)
{
    public int Id { get; } = reader.ReadInt32();
    public byte Field1 { get; } = reader.ReadByte();
    public int Field2 { get; } = reader.ReadInt32();
    public byte Field3 { get; } = reader.ReadByte();
    public int Field4 { get; } = reader.ReadInt32();
    public byte Field5 { get; } = reader.ReadByte();
}
