// <auto-generated>

using OpenWorker.Extensions;
using OpenWorker.Res.Attributes;

namespace OpenWorker.UpdateContent.Res.Rows;

[BinaryResourceTable("tb_ResVFX")]
public readonly struct ResVFXRow(BinaryReader reader)
{
    public short Id { get; } = reader.ReadInt16();
    public string Field1 { get; } = reader.ReadUtf16UnicodeStringWithoutTerminator();
    public byte Field2 { get; } = reader.ReadByte();
    public string Field3 { get; } = reader.ReadUtf16UnicodeStringWithoutTerminator();
    public byte Field4 { get; } = reader.ReadByte();
    public string Field5 { get; } = reader.ReadUtf16UnicodeStringWithoutTerminator();
    public byte Field6 { get; } = reader.ReadByte();
    public byte Field7 { get; } = reader.ReadByte();
    public short Field8 { get; } = reader.ReadInt16();
    public short Field9 { get; } = reader.ReadInt16();
    public short Field10 { get; } = reader.ReadInt16();
    public byte Field11 { get; } = reader.ReadByte();
}
