// <auto-generated>

using OpenWorker.Extensions;
using OpenWorker.Res.Attributes;

namespace OpenWorker.UpdateContent.Res.Rows;

[BinaryResourceTable("tb_SFX_BattleMaterial")]
public readonly struct SFXBattleMaterialRow(BinaryReader reader)
{
    public byte Id { get; } = reader.ReadByte();
    public string Field1 { get; } = reader.ReadUtf16UnicodeStringWithoutTerminator();
}
