// <auto-generated>

using OpenWorker.Extensions;
using OpenWorker.Res.Attributes;

namespace OpenWorker.UpdateContent.Res.Rows;

[BinaryResourceTable("tb_SFX_GroundMaterial")]
public readonly struct SFXGroundMaterialRow(BinaryReader reader)
{
    public byte Id { get; } = reader.ReadByte();
    public string Field1 { get; } = reader.ReadUtf16UnicodeStringWithoutTerminator();
    public float Field2 { get; } = reader.ReadSingle();
}
