// <auto-generated>

using OpenWorker.Res.Attributes;

namespace OpenWorker.UpdateContent.Res.Rows;

[BinaryResourceTable("tb_Shop")]
public readonly struct ShopRow(BinaryReader reader)
{
    public int Id { get; } = reader.ReadInt32();
    public int Field1 { get; } = reader.ReadInt32();
    public short Field2 { get; } = reader.ReadInt16();
    public short Field3 { get; } = reader.ReadInt16();
    public short Field4 { get; } = reader.ReadInt16();
    public byte Field5 { get; } = reader.ReadByte();
    public int Item { get; } = reader.ReadInt32();
    public byte Field7 { get; } = reader.ReadByte();
    public byte Field8 { get; } = reader.ReadByte();
    public byte Field9 { get; } = reader.ReadByte();
    public byte Field10 { get; } = reader.ReadByte();
    public byte Field11 { get; } = reader.ReadByte();
    public short Count { get; } = reader.ReadInt16();
    public int Field13 { get; } = reader.ReadInt32();
    public int Field14 { get; } = reader.ReadInt32();
    public int Field15 { get; } = reader.ReadInt32();
    public int Field16 { get; } = reader.ReadInt32();
    public int Field17 { get; } = reader.ReadInt32();
    public byte Field18 { get; } = reader.ReadByte();
    public byte Field19 { get; } = reader.ReadByte();
    public int Field20 { get; } = reader.ReadInt32();
}
