// <auto-generated>

using OpenWorker.Extensions;
using OpenWorker.Res.Attributes;

namespace OpenWorker.UpdateContent.Res.Rows;

[BinaryResourceTable("tb_Skill_Script")]
public readonly struct SkillScriptRow(BinaryReader reader)
{
    public short Id { get; } = reader.ReadInt16();
    public string Field1 { get; } = reader.ReadUtf16UnicodeStringWithoutTerminator();
    public string Field2 { get; } = reader.ReadUtf16UnicodeStringWithoutTerminator();
    public string Field3 { get; } = reader.ReadUtf16UnicodeStringWithoutTerminator();
    public string Field4 { get; } = reader.ReadUtf16UnicodeStringWithoutTerminator();
    public int Field5 { get; } = reader.ReadInt32();
    public int Field6 { get; } = reader.ReadInt32();
    public string Field7 { get; } = reader.ReadUtf16UnicodeStringWithoutTerminator();
}
