// <auto-generated>

using OpenWorker.Extensions;
using OpenWorker.Res.Attributes;

namespace OpenWorker.UpdateContent.Res.Rows;

[BinaryResourceTable("tb_Social_Item")]
public readonly struct SocialItemRow(BinaryReader reader)
{
    public short Id { get; } = reader.ReadInt16();
    public short Field1 { get; } = reader.ReadInt16();
    public int Field2 { get; } = reader.ReadInt32();
    public int Field3 { get; } = reader.ReadInt32();
    public int Field4 { get; } = reader.ReadInt32();
    public byte Field5 { get; } = reader.ReadByte();
    public int Field6 { get; } = reader.ReadInt32();
    public short Field7 { get; } = reader.ReadInt16();
    public short Field8 { get; } = reader.ReadInt16();
    public string Field9 { get; } = reader.ReadUtf16UnicodeStringWithoutTerminator();
    public string Field10 { get; } = reader.ReadUtf16UnicodeStringWithoutTerminator();
    public string Field11 { get; } = reader.ReadUtf16UnicodeStringWithoutTerminator();
    public short Field12 { get; } = reader.ReadInt16();
    public string Field13 { get; } = reader.ReadUtf16UnicodeStringWithoutTerminator();
    public string Field14 { get; } = reader.ReadUtf16UnicodeStringWithoutTerminator();
    public short Field15 { get; } = reader.ReadInt16();
    public string Field16 { get; } = reader.ReadUtf16UnicodeStringWithoutTerminator();
}
