// <auto-generated>

using OpenWorker.Extensions;
using OpenWorker.Res.Attributes;

namespace OpenWorker.UpdateContent.Res.Rows;

[BinaryResourceTable("tb_soul_metry")]
public readonly struct SoulMetryRow(BinaryReader reader)
{
    public short Id { get; } = reader.ReadInt16();
    public short Field1 { get; } = reader.ReadInt16();
    public short Field2 { get; } = reader.ReadInt16();
    public short Field3 { get; } = reader.ReadInt16();
    public short Field4 { get; } = reader.ReadInt16();
    public short Field5 { get; } = reader.ReadInt16();
    public short Field6 { get; } = reader.ReadInt16();
    public short Field7 { get; } = reader.ReadInt16();
    public short Field8 { get; } = reader.ReadInt16();
    public int Field9 { get; } = reader.ReadInt32();
    public int Field10 { get; } = reader.ReadInt32();
    public int Field11 { get; } = reader.ReadInt32();
    public int Field12 { get; } = reader.ReadInt32();
    public int Field13 { get; } = reader.ReadInt32();
    public short Field14 { get; } = reader.ReadInt16();
    public short Field15 { get; } = reader.ReadInt16();
    public short Field16 { get; } = reader.ReadInt16();
    public short Field17 { get; } = reader.ReadInt16();
    public short Field18 { get; } = reader.ReadInt16();
    public string Field19 { get; } = reader.ReadUtf16UnicodeStringWithoutTerminator();
    public string Field20 { get; } = reader.ReadUtf16UnicodeStringWithoutTerminator();
    public string Field21 { get; } = reader.ReadUtf16UnicodeStringWithoutTerminator();
    public string Field22 { get; } = reader.ReadUtf16UnicodeStringWithoutTerminator();
    public string Field23 { get; } = reader.ReadUtf16UnicodeStringWithoutTerminator();
    public short Field24 { get; } = reader.ReadInt16();
    public short Field25 { get; } = reader.ReadInt16();
    public short Field26 { get; } = reader.ReadInt16();
    public short Field27 { get; } = reader.ReadInt16();
    public short Field28 { get; } = reader.ReadInt16();
    public byte Field29 { get; } = reader.ReadByte();
    public byte Field30 { get; } = reader.ReadByte();
    public int Field31 { get; } = reader.ReadInt32();
    public int Field32 { get; } = reader.ReadInt32();
    public byte Field33 { get; } = reader.ReadByte();
    public byte Field34 { get; } = reader.ReadByte();
}
