// <auto-generated>

using OpenWorker.Res.Attributes;

namespace OpenWorker.UpdateContent.Res.Rows;

[BinaryResourceTable("tb_Soul_Guage")]
public readonly struct SoulGuageRow(BinaryReader reader)
{
    public byte Id { get; } = reader.ReadByte();
    public short Field1 { get; } = reader.ReadInt16();
    public byte Field2 { get; } = reader.ReadByte();
    public int Field3 { get; } = reader.ReadInt32();
    public byte Field4 { get; } = reader.ReadByte();
    public byte Field5 { get; } = reader.ReadByte();
    public short Field6 { get; } = reader.ReadInt16();
    public short Field7 { get; } = reader.ReadInt16();
}
