// <auto-generated>

using OpenWorker.Extensions;
using OpenWorker.Res.Attributes;

namespace OpenWorker.UpdateContent.Res.Rows;

[BinaryResourceTable("tb_soul_metry_string")]
public readonly struct SoulMetryStringRow(BinaryReader reader)
{
    public short Id { get; } = reader.ReadInt16();
    public string Field1 { get; } = reader.ReadUtf16UnicodeStringWithoutTerminator();
}
