// <auto-generated>

using OpenWorker.Res.Attributes;

namespace OpenWorker.UpdateContent.Res.Rows;

[BinaryResourceTable("tb_SpecialMaze_Open")]
public readonly struct SpecialMazeOpenRow(BinaryReader reader)
{
    public short Id { get; } = reader.ReadInt16();
    public short Field1 { get; } = reader.ReadInt16();
    public short Field2 { get; } = reader.ReadInt16();
    public short Field3 { get; } = reader.ReadInt16();
    public short Field4 { get; } = reader.ReadInt16();
    public short Field5 { get; } = reader.ReadInt16();
    public short Field6 { get; } = reader.ReadInt16();
    public short Field7 { get; } = reader.ReadInt16();
    public short Field8 { get; } = reader.ReadInt16();
    public short Field9 { get; } = reader.ReadInt16();
    public short Field10 { get; } = reader.ReadInt16();
    public byte Field11 { get; } = reader.ReadByte();
    public byte Field12 { get; } = reader.ReadByte();
    public byte Field13 { get; } = reader.ReadByte();
    public byte Field14 { get; } = reader.ReadByte();
    public byte Field15 { get; } = reader.ReadByte();
    public byte Field16 { get; } = reader.ReadByte();
    public byte Field17 { get; } = reader.ReadByte();
    public byte Field18 { get; } = reader.ReadByte();
    public byte Field19 { get; } = reader.ReadByte();
    public byte Field20 { get; } = reader.ReadByte();
}
