// <auto-generated>

using OpenWorker.Res.Attributes;

namespace OpenWorker.UpdateContent.Res.Rows;

[BinaryResourceTable("tb_Status")]
public readonly struct StatusRow(BinaryReader reader)
{
    public short Id { get; } = reader.ReadInt16();
    public float Field1 { get; } = reader.ReadSingle();
    public float Field2 { get; } = reader.ReadSingle();
    public float Field3 { get; } = reader.ReadSingle();
    public float Field4 { get; } = reader.ReadSingle();
    public float Field5 { get; } = reader.ReadSingle();
    public float Field6 { get; } = reader.ReadSingle();
    public float Field7 { get; } = reader.ReadSingle();
    public float Field8 { get; } = reader.ReadSingle();
    public float Field9 { get; } = reader.ReadSingle();
    public float Field10 { get; } = reader.ReadSingle();
    public float Field11 { get; } = reader.ReadSingle();
    public float Field12 { get; } = reader.ReadSingle();
    public float Field13 { get; } = reader.ReadSingle();
    public float Field14 { get; } = reader.ReadSingle();
    public float Field15 { get; } = reader.ReadSingle();
    public float Field16 { get; } = reader.ReadSingle();
    public float Field17 { get; } = reader.ReadSingle();
    public float Field18 { get; } = reader.ReadSingle();
    public float Field19 { get; } = reader.ReadSingle();
    public float Field20 { get; } = reader.ReadSingle();
    public float Field21 { get; } = reader.ReadSingle();
    public float Field22 { get; } = reader.ReadSingle();
    public float Field23 { get; } = reader.ReadSingle();
    public float Field24 { get; } = reader.ReadSingle();
    public float Field25 { get; } = reader.ReadSingle();
    public float Field26 { get; } = reader.ReadSingle();
    public float Field27 { get; } = reader.ReadSingle();
    public float Field28 { get; } = reader.ReadSingle();
    public float Field29 { get; } = reader.ReadSingle();
    public float Field30 { get; } = reader.ReadSingle();
    public float Field31 { get; } = reader.ReadSingle();
    public float Field32 { get; } = reader.ReadSingle();
    public float Field33 { get; } = reader.ReadSingle();
    public float Field34 { get; } = reader.ReadSingle();
    public float Field35 { get; } = reader.ReadSingle();
    public byte Field36 { get; } = reader.ReadByte();
    public byte Field37 { get; } = reader.ReadByte();
    public byte Field38 { get; } = reader.ReadByte();
    public byte Field39 { get; } = reader.ReadByte();
    public byte Field40 { get; } = reader.ReadByte();
    public byte Field41 { get; } = reader.ReadByte();
    public byte Field42 { get; } = reader.ReadByte();
    public byte Field43 { get; } = reader.ReadByte();
    public byte Field44 { get; } = reader.ReadByte();
    public byte Field45 { get; } = reader.ReadByte();
    public byte Field46 { get; } = reader.ReadByte();
    public byte Field47 { get; } = reader.ReadByte();
    public float Field48 { get; } = reader.ReadSingle();
    public float Field49 { get; } = reader.ReadSingle();
    public float Field50 { get; } = reader.ReadSingle();
    public float Field51 { get; } = reader.ReadSingle();
    public float Field52 { get; } = reader.ReadSingle();
    public float Field53 { get; } = reader.ReadSingle();
    public float Field54 { get; } = reader.ReadSingle();
    public float Field55 { get; } = reader.ReadSingle();
}
