// <auto-generated>

using OpenWorker.Res.Attributes;

namespace OpenWorker.UpdateContent.Res.Rows;

[BinaryResourceTable("tb_Talk_List")]
public readonly struct TalkListRow(BinaryReader reader)
{
    public short Id { get; } = reader.ReadInt16();
    public short Field1 { get; } = reader.ReadInt16();
    public short Field2 { get; } = reader.ReadInt16();
    public short Field3 { get; } = reader.ReadInt16();
    public short Field4 { get; } = reader.ReadInt16();
    public short Field5 { get; } = reader.ReadInt16();
    public short Field6 { get; } = reader.ReadInt16();
    public short Field7 { get; } = reader.ReadInt16();
    public short Field8 { get; } = reader.ReadInt16();
    public short Field9 { get; } = reader.ReadInt16();
    public short Field10 { get; } = reader.ReadInt16();
    public short Field11 { get; } = reader.ReadInt16();
    public short Field12 { get; } = reader.ReadInt16();
    public short Field13 { get; } = reader.ReadInt16();
    public short Field14 { get; } = reader.ReadInt16();
    public short Field15 { get; } = reader.ReadInt16();
    public short Field16 { get; } = reader.ReadInt16();
    public short Field17 { get; } = reader.ReadInt16();
    public short Field18 { get; } = reader.ReadInt16();
    public short Field19 { get; } = reader.ReadInt16();
    public short Field20 { get; } = reader.ReadInt16();
    public short Field21 { get; } = reader.ReadInt16();
    public short Field22 { get; } = reader.ReadInt16();
    public short Field23 { get; } = reader.ReadInt16();
    public short Field24 { get; } = reader.ReadInt16();
    public short Field25 { get; } = reader.ReadInt16();
}
