// <auto-generated>

using OpenWorker.Extensions;
using OpenWorker.Res.Attributes;

namespace OpenWorker.UpdateContent.Res.Rows;

[BinaryResourceTable("tb_Transport_Info")]
public readonly struct TransportInfoRow(BinaryReader reader)
{
    public short Id { get; } = reader.ReadInt16();
    public byte Field1 { get; } = reader.ReadByte();
    public int Field2 { get; } = reader.ReadInt32();
    public string Field3 { get; } = reader.ReadUtf16UnicodeStringWithoutTerminator();
    public byte Field4 { get; } = reader.ReadByte();
    public int Field5 { get; } = reader.ReadInt32();
    public byte Field6 { get; } = reader.ReadByte();
    public short Field7 { get; } = reader.ReadInt16();
    public short Field8 { get; } = reader.ReadInt16();
    public short Field9 { get; } = reader.ReadInt16();
    public short Field10 { get; } = reader.ReadInt16();
    public short Field11 { get; } = reader.ReadInt16();
    public short Field12 { get; } = reader.ReadInt16();
    public byte Field13 { get; } = reader.ReadByte();
    public short Field14 { get; } = reader.ReadInt16();
    public short Field15 { get; } = reader.ReadInt16();
    public string Field16 { get; } = reader.ReadUtf16UnicodeStringWithoutTerminator();
}
