// <auto-generated>

using OpenWorker.Res.Attributes;

namespace OpenWorker.UpdateContent.Res.Rows;

[BinaryResourceTable("tb_UI_PopUp")]
public readonly struct UIPopUpRow(BinaryReader reader)
{
    public short Id { get; } = reader.ReadInt16();
    public byte Field1 { get; } = reader.ReadByte();
    public short Field2 { get; } = reader.ReadInt16();
    public short Field3 { get; } = reader.ReadInt16();
    public short Field4 { get; } = reader.ReadInt16();
    public byte Field5 { get; } = reader.ReadByte();
    public byte Field6 { get; } = reader.ReadByte();
    public byte Field7 { get; } = reader.ReadByte();
    public byte Field8 { get; } = reader.ReadByte();
    public short Field9 { get; } = reader.ReadInt16();
    public short Field10 { get; } = reader.ReadInt16();
    public byte Field11 { get; } = reader.ReadByte();
    public short Field12 { get; } = reader.ReadInt16();
    public short Field13 { get; } = reader.ReadInt16();
    public short Field14 { get; } = reader.ReadInt16();
    public short Field15 { get; } = reader.ReadInt16();
    public short Field16 { get; } = reader.ReadInt16();
    public short Field17 { get; } = reader.ReadInt16();
    public short Field18 { get; } = reader.ReadInt16();
    public short Field19 { get; } = reader.ReadInt16();
    public short Field20 { get; } = reader.ReadInt16();
    public short Field21 { get; } = reader.ReadInt16();
}
