// <auto-generated>

using OpenWorker.Extensions;
using OpenWorker.Res.Attributes;

namespace OpenWorker.UpdateContent.Res.Rows;

[BinaryResourceTable("tb_UI_String")]
public readonly struct UIStringRow(BinaryReader reader)
{
    public short Id { get; } = reader.ReadInt16();
    public byte Field1 { get; } = reader.ReadByte();
    public string Field2 { get; } = reader.ReadUtf16UnicodeStringWithoutTerminator();
}
