// <auto-generated>

using OpenWorker.Res.Attributes;

namespace OpenWorker.UpdateContent.Res.Rows;

[BinaryResourceTable("tb_Unity_Event")]
public readonly struct UnityEventRow(BinaryReader reader)
{
    public short Id { get; } = reader.ReadInt16();
    public short Field1 { get; } = reader.ReadInt16();
    public short Field2 { get; } = reader.ReadInt16();
    public short Field3 { get; } = reader.ReadInt16();
    public short Field4 { get; } = reader.ReadInt16();
    public short Field5 { get; } = reader.ReadInt16();
    public short Field6 { get; } = reader.ReadInt16();
    public short Field7 { get; } = reader.ReadInt16();
    public short Field8 { get; } = reader.ReadInt16();
    public short Field9 { get; } = reader.ReadInt16();
    public short Field10 { get; } = reader.ReadInt16();
    public short Field11 { get; } = reader.ReadInt16();
    public short Field12 { get; } = reader.ReadInt16();
    public short Field13 { get; } = reader.ReadInt16();
    public short Field14 { get; } = reader.ReadInt16();
    public short Field15 { get; } = reader.ReadInt16();
    public short Field16 { get; } = reader.ReadInt16();
}
