// <auto-generated>

using OpenWorker.Extensions;
using OpenWorker.Res.Attributes;

namespace OpenWorker.UpdateContent.Res.Rows;

[BinaryResourceTable("tb_VFX_GroundMaterial")]
public readonly struct VFXGroundMaterialRow(BinaryReader reader)
{
    public byte Id { get; } = reader.ReadByte();
    public string Field1 { get; } = reader.ReadUtf16UnicodeStringWithoutTerminator();
    public string Field2 { get; } = reader.ReadUtf16UnicodeStringWithoutTerminator();
    public string Field3 { get; } = reader.ReadUtf16UnicodeStringWithoutTerminator();
    public string Field4 { get; } = reader.ReadUtf16UnicodeStringWithoutTerminator();
    public string Field5 { get; } = reader.ReadUtf16UnicodeStringWithoutTerminator();
    public string Field6 { get; } = reader.ReadUtf16UnicodeStringWithoutTerminator();
    public string Field7 { get; } = reader.ReadUtf16UnicodeStringWithoutTerminator();
    public string Field8 { get; } = reader.ReadUtf16UnicodeStringWithoutTerminator();
    public string Field9 { get; } = reader.ReadUtf16UnicodeStringWithoutTerminator();
}
