namespace OpenWorker.Hotspot.Modules.Items.Enums;

internal enum E_BROACH_CLASSIFY_INDEX
{
    E_BROACH_CLASSIFY_INDEX_1 = 0x271C9,
    E_BROACH_CLASSIFY_INDEX_2 = 0x271CA,
    E_BROACH_CLASSIFY_INDEX_3 = 0x271CB,
    E_BROACH_CLASSIFY_INDEX_4 = 0x271CC,
    E_BROACH_CLASSIFY_INDEX_5 = 0x271CD,
    E_BROACH_CLASSIFY_INDEX_6 = 0x271CE
}