namespace SoulCore.IO.Network.Sync.Commands
{
    public enum SCCategory : byte
    {
        System = 0x1,
        Login = 0x2,
        Character = 0x3,
        World = 0x4,
        Move = 0x5,
        Skill = 0x6,
        Chat = 0x7,
        Item = 0x8,
        Shop = 0x9,
        Trade = 0xA,
        Maze = 0x11,
        Party = 0x12,
        ItemUpgrade = 0x13,
        Drop = 0x14,
        Quest = 0x15,
        Option = 0x16,
        Monster = 0x17,
        ItemSetup = 0x18,
        Friend = 0x19,
        Post = 0x20,
        SoulMetry = 0x21,
        League = 0x22,
        Gesture = 0x23,
        DailyMission = 0x24,
        Vaccum = 0x25,
        MyRoom = 0x26,
        Helper = 0x27,
        InfiniteTower = 0x28,
        Booster = 0x29,
        Event = 0x2A,
        Exchange = 0x2B,
        Ranking = 0x2C,
        SocialItem = 0x2D,
        Force = 0x2E,
        WorldMode = 0x30,
        WeeklyMission = 0x32,
        ModeMaze = 0x33,
        Restart = 0x34,
        Tool = 0x40,
        Channel = 0xF1,
        Server = 0xF2,
        ServerUser = 0xF3,
        ServerParty = 0xF4,
        ServerFriend = 0xF5,
        ServerLeague = 0xF6,
        Monitor = 0xF7,
        GmAgent = 0xF8,
        ServerForce = 0xFA,
        ServerWorldMode = 0xFB,
        ServerModeMaze = 0xFD,
    };
}
