namespace SoulCore.IO.Network.Sync.Commands
{
    public enum SCItem : byte
    {
        InventoryInfo = 0x1,
        Move = 0x2,
        Combine = 0x3,
        Divide = 0x4,
        Break = 0x5,
        Create = 0x6,
        MoveBt = 0xD,
        OpenSlotInfo = 0xE,
        AddSlot = 0xF,
        BankInfo = 0x10,
        Use = 0x11,
        Reduce = 0x12,
        UseBt = 0x13,
        EquipSlotOpen = 0x14,
        Update = 0x15,
        UpdateInvenMoney = 0x20,
        UpdateBankMoney = 0x21,
        MoveMoneyToBankReq = 0x22,
        MoveMoneyToInvenReq = 0x23,
        MoveMoney = 0x24,
        LineUp = 0x25,
        LoadQuickslot = 0x26,
        UpdateQuickslotCard = 0x27,
        UpdateQuickslotItem = 0x28,
        UpdateBp = 0x31,
        UpdateEther = 0x32,
        UpdateCash = 0x33,
        UpdateFriendPoint = 0x34,
        MazeRewardItem = 0x47,
        UseInfoList = 0x48,
        UseInfoUpdate = 0x49,
        CubeReq = 0x4A,
        AppearanceLoad = 0x50,
        AppearanceEnd = 0x51,
        AppearanceEquip = 0x52,
        NameChange = 0x53,
        SocketLoad = 0x55,
        BroachLoad = 0x56,
        AkashicRecordLoad = 0x57,
        AkashicRecordAdd = 0x58,
        SocketUpdate = 0x61,
        BroachUpdate = 0x62,
        UpdateRecycle = 0x63,
        OptioneffectBt = 0x64,
        UseAppearance = 0x65,
        CooltimeInfo = 0x66,
        UseSelect = 0x67,
        MakeLimitList = 0x68,
        MakeLimitUpdate = 0x69,
        UseWarpRes = 0x70,
        ResealPackage = 0x71,
        ResealPackageInfo = 0x72,
        DeckPageOpen = 0x73,
    }
}
