namespace SoulCore.IO.Network.Sync.Commands
{
    public enum SCLeague : byte
    {
        Create = 0x1,
        Delete = 0x2,
        List = 0x3,
        Applicant = 0x5,
        Info = 0x7,
        Board = 0x8,
        Withdraw = 0x9,
        Delegate = 0xA,
        Kick = 0xF,
        Invite = 0x13,
        InviteAccept = 0x14,
        InviteReject = 0x15,
        JoinUser = 0x17,
        ApplicantAccept = 0x18,
        ApplicantReject = 0x19,
        Search = 0x20,
        OverlapName = 0x21,
        MemberUpdate = 0x22,
        ApplicantRes = 0x23,
        ApplicantAdd = 0x24,
        ApplicantRejectRes = 0x25,
        ApplicantDelete = 0x26,
        WithdrawRes = 0x27,
        KickRes = 0x28,
        NoticeChange = 0x29,
        NameChange = 0x30,
        CardChange = 0x31,
        AuthChange = 0x32,
        PositionNameChange = 0x33,
        PositionNameChangeRes = 0x34,
        AuthChangeRes = 0x35,
        NoticeChangeRes = 0x36,
        InviteRes = 0x37,
        BoardRes = 0x38,
        MemberPositionChange = 0x39,
        MemberLeave = 0x41,
        MemberPositionChangeRes = 0x42,
        InfoUpdate = 0x43,
        InfoAlert = 0x44,
        CreateRes = 0x45,
        OpenOrNot = 0x46,
        RecruitNotice = 0x47,
        RecordUpdate = 0x48,
        DelegateRes = 0x49,
        CardChangeRes = 0x50,
        Exp = 0x51,
        Levleup = 0x52,
        SkillLearn = 0x53,
        InventoryMove = 0x54,
        InventoryInfo = 0x56,
        InventoryMoveCast = 0x57,
        NameChangeRes = 0x58,
    }
}
