namespace SoulCore.IO.Network.Sync.Commands
{
    public enum SCWorld : byte
    {
        EnterReq = 0x1,
        EnterRes = 0x2,
        CurDate = 0x3,
        Version = 0x4,
        ObjectReq = 0x6,
        WarpReq = 0x7,
        WarpRes = 0x8,
        WarpEnableRes = 0x9,
        GateEnableRes = 0xA,
        ChecksectorReq = 0xb,
        ChecksectorRes = 0xC,
        WarpOutReq = 0xD,
        WarpMazeRes = 0xE,
        WarpMazeTimeRes = 0xF,
        InInfoPc = 0x11,
        OutInfoPc = 0x12,
        InInfoNpc = 0x13,
        OutInfoNpc = 0x14,
        InInfoMonster = 0x15,
        OutInfoMonster = 0x16,
        InInfoSpawnbox = 0x18,
        GameOut = 0x19,
        OtherInfosPc = 0x21,
        OtherInfosNpc = 0x22,
        OtherInfosMonster = 0x23,
        OutOtherInfosPc = 0x24,
        MoverInfoReq = 0x31,
        EnterBattlecry = 0x32,
        Escape = 0x33,
        DistrictTransportReq = 0x40,
        MazeCreateReq = 0x41,
        MazeCreateRes = 0x42,
        EnterMazeLimitCountLoad = 0x43,
        EnterMazeLimitCountReset = 0x44,
        EnterMazeLimitCountUpdate = 0x45,
        EnterMazeLimitCountGroupLoad = 0x46,
        EnterMazeLimitCountGroupReset = 0x47,
        EnterMazeLimitCountGroupUpdate = 0x48,
        EnterMapPc = 0x51,
        ExitMapPc = 0x52,
        ChangePacketOptimization = 0x60,
        SkipInTutorial02Req = 0x61,
    }
}
