namespace ow.Framework.Game.Enums
{
    // E_INVEN_TYPE_SHAPE_EQUIP = 0x0,
    // E_INVEN_TYPE_ABILITY_EQUIP = 0x1,
    // E_INVEN_TYPE_COMMON = 0x2,
    // E_INVEN_TYPE_LOOK_EQUIP = 0x3,
    // E_INVEN_TYPE_COSTUME = 0x4,
    // E_INVEN_TYPE_COMMON_STORAGE = 0x5,
    // E_INVEN_TYPE_COSTUME_STORAGE = 0x6,
    // E_INVEN_TYPE_REPURCHASE_LIST = 0xA,
    // E_INVEN_TYPE_CUBE = 0xB,
    // E_INVEN_TYPE_APPEARANCE = 0xC,
    // E_INVEN_TYPE_CASH = 0xD,
    // E_INVEN_TYPE_CASH_STORAGE = 0xE,
    // E_INVEN_TYPE_LEAGUE = 0xF,
    // E_INVEN_TYPE_ACCOUNT_COMMON_STORAGE = 0x10,
    // E_INVEN_TYPE_ACCOUNT_FASHION_STORAGE = 0x11,
    // E_INVEN_TYPE_ACCOUNT_CASH_STORAGE = 0x12,
    // E_INVEN_TYPE_MAX = 0x13,
    // E_INVE_TYPE_POST = 0x64,
    // E_INVE_TYPE_EXCHANGE_SELL = 0x66,
    // E_INVE_TYPE_HELPER_EQUIP = 0x69,
    public enum StorageType
    {
        E_INVEN_TYPE_SHAPE_EQUIP = 0x0,
        E_INVEN_TYPE_ABILITY_EQUIP = 0x1,
        InventoryCommon = 0x2,
        InventoryViewCostume = 0x3,
        InventoryCostume = 0x4,
        E_INVEN_TYPE_COMMON_STORAGE = 0x5,
        E_INVEN_TYPE_COSTUME_STORAGE = 0x6,
        E_INVEN_TYPE_REPURCHASE_LIST = 0xA,
        E_INVEN_TYPE_CUBE = 0xB,
        E_INVEN_TYPE_APPEARANCE = 0xC,
        E_INVEN_TYPE_CASH = 0xD,
        E_INVEN_TYPE_CASH_STORAGE = 0xE,
        E_INVEN_TYPE_LEAGUE = 0xF,
        BankCommon = 0x10,
        BankFashion = 0x11,
        BankCash = 0x12,
        E_INVEN_TYPE_MAX = 0x13,
        E_INVE_TYPE_POST = 0x64,
        E_INVE_TYPE_EXCHANGE_SELL = 0x66,
        E_INVE_TYPE_HELPER_EQUIP = 0x69,

        EquippedBattleFashion = 0x00,
        EquippedGear = 0x01,
        InventoryItems = 0x02,
        EquippedViewFashion = 0x03,
        InventoryFashion = 0x04,

        Cube = 0x0B,

        InventoryExtra = 0x0D,
    }
}