namespace ow.Framework.IO.Network.Sync.Commands
{
    public enum SCServerLeague : byte
    {
        Create = 0x1,
        Delete = 0x2,
        Login = 0x3,
        Applicant = 0x4,
        Info = 0x6,
        Delegate = 0x7,
        Withdraw = 0x8,
        Kick = 0x9,
        InfoChange = 0xA,
        Invite = 0xC,
        InviteAccept = 0xD,
        InviteReject = 0x10,
        ApplicantList = 0x11,
        MemberList = 0x12,
        Board = 0x14,
        Error = 0x15,
        ApplicantAccept = 0x16,
        ApplicantReject = 0x17,
        Search = 0x18,
        ApplicantRes = 0x19,
        ApplicantAdd = 0x20,
        ApplicantRejectRes = 0x21,
        ApplicantDelete = 0x22,
        NoticeChange = 0x23,
        List = 0x24,
        NameChange = 0x25,
        CardChange = 0x26,
        PositionNameChange = 0x27,
        AuthChange = 0x28,
        PositionNameChangeRes = 0x34,
        AuthChangeRes = 0x35,
        Message = 0x36,
        MemberPositionChange = 0x37,
        ApplicantUpdate = 0x38,
        MemberLogout = 0x39,
        ApplicantJoinUser = 0x40,
        InviteJoinUser = 0x41,
        MemberUpdate = 0x42,
        DeletePenalty = 0x43,
        WithdrawPenalty = 0x44,
        OpenOrNot = 0x45,
        RecruitNotice = 0x46,
        RecordUpdate = 0x47,
        CardChangeRes = 0x48,
        Levelup = 0x51,
        SkillLearn = 0x53,
        Gold = 0x54,
        Wealth = 0x55,
        MbmberInitExp = 0x56,
        Skillpoint = 0x57,
        Sync = 0x58,
        SyncLoad = 0x59,
        InventoryInfo = 0x60,
        InventoryMove = 0x61,
    }
}
