using ow.Framework.Game.Enums;
using System;
using System.Collections.Generic;

namespace ow.Framework.Game.Entities
{
    public interface IStatsEntity : IReadOnlyList<float>
    {
        float this[Stat index] => throw new NotImplementedException();

        float Unknown0 => throw new NotImplementedException();
        float CurrentHp => throw new NotImplementedException();
        float CurrentSg => throw new NotImplementedException();
        float Unknown3 => throw new NotImplementedException();
        float Unknown4 => throw new NotImplementedException();
        float Unknown5 => throw new NotImplementedException();
        float Unknown6 => throw new NotImplementedException();
        float Unknown7 => throw new NotImplementedException();
        float Unknown8 => throw new NotImplementedException();
        float Unknown9 => throw new NotImplementedException();
        float MaxHp => throw new NotImplementedException();
        float Unknown11 => throw new NotImplementedException();
        float MaxSg => throw new NotImplementedException();
        float Unknown12 => throw new NotImplementedException();
        float Unknown13 => throw new NotImplementedException();
        float Stamina => throw new NotImplementedException();
        float StaminaRegeneration => throw new NotImplementedException();
        float Unknown16 => throw new NotImplementedException();
        float Unknown17 => throw new NotImplementedException();
        float MoveSpeed => throw new NotImplementedException();
        float AttackSpeed => throw new NotImplementedException();
        float MinAttackDamage => throw new NotImplementedException();
        float MaxAttackDamage => throw new NotImplementedException();
        float Unknown22 => throw new NotImplementedException();
        float Unknown23 => throw new NotImplementedException();
        float Defence => throw new NotImplementedException();
        float Unknown25 => throw new NotImplementedException();
        float Accuracy => throw new NotImplementedException();
        float Unknown27 => throw new NotImplementedException();
        float PartialDamage => throw new NotImplementedException();
        float CritChance => throw new NotImplementedException();
        float Unknown30 => throw new NotImplementedException();
        float CritResistance => throw new NotImplementedException();
        float Unknown32 => throw new NotImplementedException();
        float Unknown33 => throw new NotImplementedException();
        float Unknown34 => throw new NotImplementedException();
        float CritDamage => throw new NotImplementedException();
        float Unknown36 => throw new NotImplementedException();
        float Unknown37 => throw new NotImplementedException();
        float DamageReduction => throw new NotImplementedException();
        float Unknown39 => throw new NotImplementedException();
        float Unknown40 => throw new NotImplementedException();
        float Unknown41 => throw new NotImplementedException();
        float Unknown42 => throw new NotImplementedException();
        float Evade => throw new NotImplementedException();
        float Unknown44 => throw new NotImplementedException();
        float Unknown45 => throw new NotImplementedException();
        float Unknown46 => throw new NotImplementedException();
        float ArmourBreak => throw new NotImplementedException();
        float Unknown48 => throw new NotImplementedException();
        float FireResistance => throw new NotImplementedException();
        float PoisonResistance => throw new NotImplementedException();
        float ElectricResistance => throw new NotImplementedException();
        float BleedResistance => throw new NotImplementedException();
        float Stun1Resistance => throw new NotImplementedException();
        float ParalysisResistance => throw new NotImplementedException();
        float SleepResistance => throw new NotImplementedException();
        float FrostResistance => throw new NotImplementedException();
        float SilenceResistance => throw new NotImplementedException();
        float VulnResistance => throw new NotImplementedException();
        float Stun2Resistance => throw new NotImplementedException();
        float ConfusedResistance => throw new NotImplementedException();
        float Unknown61 => throw new NotImplementedException();
        float Unknown62 => throw new NotImplementedException();
        float VirtueDamage => throw new NotImplementedException();
        float SinDamage => throw new NotImplementedException();
        float GraceDamage => throw new NotImplementedException();
        float HateDamage => throw new NotImplementedException();
        float SolaceDamage => throw new NotImplementedException();
        float TormentDamage => throw new NotImplementedException();
        float VirtueResistance => throw new NotImplementedException();
        float SinResistance => throw new NotImplementedException();
        float GraceResistance => throw new NotImplementedException();
        float HateResistance => throw new NotImplementedException();
        float SolaceResistance => throw new NotImplementedException();
        float TormentResistance => throw new NotImplementedException();
        float ManicBalanceDamage => throw new NotImplementedException();
        float ManicBalanceResistance => throw new NotImplementedException();
    }
}