namespace OpenWorker.Hotspot.Modules.Persons.Enums;

public enum PersonKickOutReason : byte
{
    SystemError = 0x0,
    AlreadyLogin = 0x1,
    FailedSend = 0x2,
    FailedEnterMaze = 0x3,
    WrongPosition = 0x4,
    Xigncode = 0x5,
    GmTool = 0x6,
    WrongBp = 0x7,
    Buffer = 0x8,
    KeepAlive = 0x9,
    WrongGold = 0xA,
    GmToolServerShutdown = 0xB,
    UserSyncError = 0xC,
    ServerUserFull = 0xD,
    SgCinderella = 0xE,
    DbSyncWorld = 0x14,
    ItemOverlapped = 0x15,
    FailedSgGetRenewToken = 0x16,
    UserWrongWorld = 0x17,
    FailedMacAddress = 0x18,
    FailedEnterArea = 0x19,
    NotExistUser = 0x1A,
    WrongAuthSessionId = 0x1B,
    WrongServerGroupId = 0x1C,
    CheckKeepAliveCheckSum0 = 0x1D,
    CheckKeepAliveCheckSum1 = 0x1E,
    CheckKeepAliveCheckSum2 = 0x1F,
    GameGuardAuth = 0x20,
    GameGuardError = 0x21,
    UseHackTool = 0x22,
    GfTokenRefreshError = 0x23,
    SkillFast = 0x25,
    FailedLoadChar = 0x26,
    CheckLocation = 0x27
}