using System.Text;
using OpenWorker.Extensions;

namespace OpenWorker.SourceGenerator.ResourceStructures;

internal static class ClassHelper
{
    private static Dictionary<int, string> Names { get; } = new()
    {
        { 0, "Id" }
    };

    internal static async ValueTask<string> GetResContent(string tableName,
        string modelName,
        string className,
        string modelNamespace,
        string nameSpace,
        IReadOnlyList<Type> types)
    {
        if (types.Count < 1)
        {
            throw new ApplicationException();
        }

        var builder = new StringBuilder();

        builder.AppendLine("// <auto-generated>");
        builder.AppendLine();

        if (types.Any(e => e == typeof(string)))
        {
            builder.AppendLine($"using {typeof(BinaryReaderExtension).Namespace};");
            builder.AppendLine();
        }

        builder.AppendLine("using OpenWorker.Res.Attributes;");
        builder.AppendLine();

        builder.AppendLine($"namespace {nameSpace};");
        builder.AppendLine();

        builder.AppendLine($"[Res(\"{tableName}\")]");
        builder.AppendLine($"public readonly struct {className}(BinaryReader reader)");
        builder.AppendLine("{");

        foreach (var (v, i) in types.Select((v, i) => (v, i)))
        {
            var field = await TypeHelper.GetTypeName(v);
            var method = typeof(string) == v
                ? nameof(BinaryReaderExtension.ReadUtf16UnicodeStringWithoutTerminator)
                : $"Read{v.Name}";
            var name = Names.TryGetValue(i, out var value) ? value : $"Field{i}";

            builder.AppendLine($"    public {field} {name} {{ get; }} = reader.{method}();");
        }

        builder.AppendLine("}");

        return builder.ToString();
    }

    internal static async ValueTask<string> GetClassContent(string tableName,
        string modelName,
        string className,
        string modelNamespace,
        string nameSpace,
        IReadOnlyList<Type> types)
    {
        if (types.Count < 1)
        {
            throw new ApplicationException();
        }

        var builder = new StringBuilder();

        builder.AppendLine("// <auto-generated>");
        builder.AppendLine();
        // builder.AppendFormat("using {0};", typeof(ResourceAttribute).Namespace);
        // builder.AppendLine();
        builder.AppendLine($"using {modelNamespace};");
        // builder.AppendLine();

        if (types.Any(e => e == typeof(string)))
            // builder.AppendLine();
        {
            builder.AppendLine($"using {typeof(BinaryReaderExtension).Namespace};");
        }

        // builder.AppendLine();
        // builder.AppendLine();

        builder.AppendLine();
        builder.AppendLine($"namespace {nameSpace};");
        // builder.AppendLine();
        builder.AppendLine();

        // builder.AppendLine("[Resource(TableName)]");
        builder.AppendLine($"[SeedAttribute<{modelName}>]");
        builder.AppendLine($"internal readonly struct {className}(BinaryReader reader) : IRow");
        // builder.AppendLine();
        builder.AppendLine("{");
        builder.AppendLine($"    public static string TableName {{ get; }} = \"{tableName}\";");
        // builder.AppendLine();
        builder.AppendLine();

        foreach (var (v, i) in types.Select((v, i) => (v, i)))
        {
            var field = await TypeHelper.GetTypeName(v);
            var method = typeof(string) == v
                ? nameof(BinaryReaderExtension.ReadUtf16UnicodeStringWithoutTerminator)
                : $"Read{v.Name}";
            var name = Names.TryGetValue(i, out var value) ? value : $"Field{i}";

            builder.AppendLine($"    internal {field} {name} {{ get; }} = reader.{method}();");
            // builder.AppendLine();
        }

        builder.AppendLine("}");

        return builder.ToString();
    }

    internal static async ValueTask<string> GetModelContent(string tableName,
        string className,
        string nameSpace,
        IReadOnlyList<Type> types)
    {
        if (types.Count < 1)
        {
            throw new ApplicationException();
        }

        var builder = new StringBuilder();

        builder.AppendLine("// <auto-generated>");
        builder.AppendLine();
        builder.AppendLine("using System.ComponentModel.DataAnnotations.Schema;");
        builder.AppendLine();

        // builder.AppendFormat("using {0};", typeof(ResourceModelAttribute).Namespace);
        // builder.AppendLine();
        // builder.AppendLine();
        builder.AppendLine($"namespace {nameSpace};");
        // builder.AppendLine();
        builder.AppendLine();

        // builder.AppendFormat("[ResourceModel(\"{0}\")]", tablename);
        // builder.AppendLine();
        builder.AppendLine($"public sealed class {className}");
        // builder.AppendLine();
        builder.AppendLine("{");

        foreach (var (v, i) in types.Select((v, i) => (v, i)))
        {
            var field = await TypeHelper.GetTypeName(v);
            var name = Names.TryGetValue(i, out var value) ? value : $"Field{i}";

            if (i == 0)
            {
                builder.AppendLine("    [DatabaseGenerated(DatabaseGeneratedOption.None)]");
            }

            builder.AppendLine($"    public required {field} {name} {{ get; set; }}");
            // builder.AppendLine();
        }

        builder.AppendLine("}");

        return builder.ToString();
    }
}