using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace OpenWorker.Commands.SourceGenerators;

/// <summary>
/// Source generator that creates the Commands dictionary field for CommandManager.
/// </summary>
[Generator]
public class CommandManagerGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Get all classes that implement ICommand and have CommandTriggerAttribute
        var commandProvider = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => IsCandidateClass(node),
                transform: static (ctx, _) => GetCommandInfo(ctx))
            .Where(static info => info is not null)
            .Select(static (info, _) => info!.Value);

        // Collect all commands
        var allCommandsProvider = commandProvider.Collect();

        // Generate the CommandManager partial class
        context.RegisterSourceOutput(allCommandsProvider, static (spc, commands) => Execute(spc, commands));
    }

    private static bool IsCandidateClass(SyntaxNode node)
    {
        // Look for class declarations with attributes
        return node is ClassDeclarationSyntax classDecl && 
               classDecl.AttributeLists.Count > 0;
    }

    private static CommandInfo? GetCommandInfo(GeneratorSyntaxContext context)
    {
        if (context.Node is not ClassDeclarationSyntax classDecl)
        {
            return null;
        }

        var symbol = context.SemanticModel.GetDeclaredSymbol(classDecl);
        if (symbol is not INamedTypeSymbol classSymbol)
        {
            return null;
        }

        // Check if it implements ICommand
        var implementsICommand = classSymbol.AllInterfaces
            .Any(i => i.Name == "ICommand");

        if (!implementsICommand)
        {
            return null;
        }

        // Get CommandTriggerAttribute
        var triggerAttr = classSymbol.GetAttributes()
            .FirstOrDefault(attr => attr.AttributeClass?.Name == "CommandTriggerAttribute");

        if (triggerAttr == null)
        {
            return null;
        }

        // Get trigger parts from constructor arguments
        var triggerParts = triggerAttr.ConstructorArguments
            .Where(arg => arg.Kind == TypedConstantKind.Array)
            .SelectMany(arg => arg.Values)
            .Select(v => v.Value?.ToString() ?? string.Empty)
            .ToList();

        // If no array arguments, try individual string arguments
        if (triggerParts.Count == 0)
        {
            triggerParts = triggerAttr.ConstructorArguments
                .Where(arg => arg.Kind == TypedConstantKind.Primitive && arg.Type?.SpecialType == SpecialType.System_String)
                .Select(arg => arg.Value?.ToString() ?? string.Empty)
                .ToList();
        }

        if (triggerParts.Count == 0)
        {
            return null;
        }

        // Join trigger parts with '-'
        var trigger = string.Join("-", triggerParts);

        return new CommandInfo(
            classSymbol.Name,
            classSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
            trigger,
            classSymbol.ContainingNamespace.ToDisplayString()
        );
    }

    private static void Execute(SourceProductionContext context, ImmutableArray<CommandInfo> commands)
    {
        if (commands.IsEmpty)
        {
            return;
        }

        var source = GenerateCommandManagerClass(commands);
        context.AddSource("CommandManager.g.cs", source);
    }

    private static string GenerateCommandManagerClass(ImmutableArray<CommandInfo> commands)
    {
        var sb = new StringBuilder();
        
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine("using OpenWorker.Commands.Abstractions;");
        
        // Add namespaces for all command types
        var namespaces = commands
            .Select(c => c.Namespace)
            .Distinct()
            .OrderBy(ns => ns);
        
        foreach (var ns in namespaces)
        {
            sb.AppendLine($"using {ns};");
        }
        
        sb.AppendLine();
        sb.AppendLine("namespace OpenWorker.Commands;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Partial class with generated Commands dictionary.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("public sealed partial class CommandManager");
        sb.AppendLine("{");
        
        // Generate private Commands field
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Dictionary of all available commands keyed by their trigger.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    private readonly IReadOnlyDictionary<string, ICommand> Commands;");
        sb.AppendLine();
        
        // Generate constructor
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Initializes a new instance of the CommandManager class.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    /// <param name=\"serviceProvider\">The service provider to resolve commands from.</param>");
        sb.AppendLine("    public CommandManager(IServiceProvider serviceProvider)");
        sb.AppendLine("    {");
        sb.AppendLine("        Commands = new Dictionary<string, ICommand>");
        sb.AppendLine("        {");
        
        // Add each command to the dictionary
        var orderedCommands = commands.OrderBy(c => c.Trigger);
        foreach (var command in orderedCommands)
        {
            var simpleName = GetSimpleTypeName(command.FullyQualifiedTypeName);
            sb.AppendLine($"            [\"/{command.Trigger}\"] = serviceProvider.GetRequiredService<{simpleName}>(),");
        }
        
        sb.AppendLine("        };");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        
        return sb.ToString();
    }

    private static string GetSimpleTypeName(string fullyQualifiedName)
    {
        // Remove "global::" prefix and namespace
        var name = fullyQualifiedName.Replace("global::", "");
        var lastDot = name.LastIndexOf('.');
        if (lastDot >= 0)
        {
            name = name.Substring(lastDot + 1);
        }
        return name;
    }

    private readonly struct CommandInfo(
        string typeName,
        string fullyQualifiedTypeName,
        string trigger,
        string ns)
    {
        public string TypeName { get; } = typeName;
        public string FullyQualifiedTypeName { get; } = fullyQualifiedTypeName;
        public string Trigger { get; } = trigger;
        public string Namespace { get; } = ns;
    }
}

