using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace OpenWorker.Commands.SourceGenerators;

/// <summary>
/// Source generator that creates constructors for classes with ExternalDependency properties.
/// </summary>
[Generator]
public class ExternalDependencyGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Find all classes with ExternalDependency properties
        var classDeclarations = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (s, _) => IsCandidateClass(s),
                transform: static (ctx, _) => GetClassForGeneration(ctx))
            .Where(static m => m.HasValue)
            .Select(static (m, _) => m!.Value);

        // Generate code for each class
        context.RegisterSourceOutput(classDeclarations, static (spc, source) => Execute(spc, source));
    }

    private static bool IsCandidateClass(SyntaxNode node)
    {
        // Look for partial class declarations
        return node is ClassDeclarationSyntax classDecl && 
               classDecl.Modifiers.Any(m => m.ValueText == "partial");
    }

    private static ClassInfo? GetClassForGeneration(GeneratorSyntaxContext context)
    {
        var classDeclaration = (ClassDeclarationSyntax)context.Node;
        var classSymbol = context.SemanticModel.GetDeclaredSymbol(classDeclaration) as INamedTypeSymbol;

        if (classSymbol is null)
        {
            return null;
        }

        // Find all properties with ExternalDependencyAttribute
        var dependencies = new List<DependencyInfo>();

        foreach (var member in classSymbol.GetMembers())
        {
            if (member is not IPropertySymbol property)
            {
                continue;
            }

            var externalDependencyAttr = property.GetAttributes()
                .FirstOrDefault(attr => attr.AttributeClass?.Name == "ExternalDependencyAttribute");

            if (externalDependencyAttr is null)
            {
                continue;
            }

            // Get all necessary namespaces for this type
            var namespaces = GetNamespacesForType(property.Type);
            
            dependencies.Add(new DependencyInfo(
                property.Name,
                property.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
                namespaces
            ));
        }

        if (dependencies.Count == 0)
        {
            return null;
        }

        // Get namespace
        var namespaceName = classSymbol.ContainingNamespace.IsGlobalNamespace
            ? string.Empty
            : classSymbol.ContainingNamespace.ToDisplayString();

        return new ClassInfo(
            classSymbol.Name,
            namespaceName,
            dependencies.ToImmutableArray()
        );
    }

    private static void Execute(SourceProductionContext context, ClassInfo classInfo)
    {
        var source = GenerateConstructor(classInfo);
        context.AddSource($"{classInfo.ClassName}.g.cs", source);
    }

    private static string GenerateConstructor(ClassInfo classInfo)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated>");
        sb.AppendLine();
        
        // Collect all unique namespaces
        var allNamespaces = new HashSet<string>
        {
            "Microsoft.Extensions.DependencyInjection",
            "System"
        };

        foreach (var dependency in classInfo.Dependencies)
        {
            foreach (var ns in dependency.Namespaces)
            {
                if (!string.IsNullOrEmpty(ns))
                {
                    allNamespaces.Add(ns);
                }
            }
        }

        // Add using statements
        foreach (var ns in allNamespaces.OrderBy(n => n))
        {
            sb.AppendLine($"using {ns};");
        }

        sb.AppendLine();

        if (!string.IsNullOrEmpty(classInfo.Namespace))
        {
            sb.AppendLine($"namespace {classInfo.Namespace};");
            sb.AppendLine();
        }

        sb.AppendLine($"internal partial class {classInfo.ClassName}");
        sb.AppendLine("{");

        // Generate constructor
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Constructor with external dependencies injected from IServiceProvider.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    /// <param name=\"serviceProvider\">The service provider to resolve dependencies from.</param>");
        sb.AppendLine("    public " + classInfo.ClassName + "(IServiceProvider serviceProvider)");
        sb.AppendLine("    {");

        // Generate property assignments
        foreach (var dependency in classInfo.Dependencies)
        {
            var simpleName = GetSimpleTypeName(dependency.TypeName);
            sb.AppendLine($"        {dependency.PropertyName} = serviceProvider.GetRequiredService<{simpleName}>();");
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private static ImmutableArray<string> GetNamespacesForType(ITypeSymbol typeSymbol)
    {
        var namespaces = new HashSet<string>();

        // Add the namespace of the type itself
        if (!typeSymbol.ContainingNamespace.IsGlobalNamespace)
        {
            namespaces.Add(typeSymbol.ContainingNamespace.ToDisplayString());
        }

        // If it's a generic type, add namespaces of generic arguments
        if (typeSymbol is INamedTypeSymbol namedType && namedType.IsGenericType)
        {
            foreach (var typeArg in namedType.TypeArguments)
            {
                foreach (var ns in GetNamespacesForType(typeArg))
                {
                    namespaces.Add(ns);
                }
            }
        }

        return namespaces.ToImmutableArray();
    }

    private static string GetSimpleTypeName(string fullyQualifiedName)
    {
        // Remove "global::" prefix
        var name = fullyQualifiedName.Replace("global::", "");
        
        // For simple types without namespaces, just return the name
        if (!name.Contains('.'))
        {
            return name;
        }
        
        // Handle generic types
        var genericStart = name.IndexOf('<');
        if (genericStart >= 0)
        {
            // Split into parts before and after '<'
            var beforeGeneric = name.Substring(0, genericStart);
            var lastDot = beforeGeneric.LastIndexOf('.');
            var typeName = lastDot >= 0 ? beforeGeneric.Substring(lastDot + 1) : beforeGeneric;
            
            // Extract the generic parameter part
            var genericEnd = name.LastIndexOf('>');
            var innerType = name.Substring(genericStart + 1, genericEnd - genericStart - 1);
            innerType = GetSimpleTypeName(innerType);
            
            return $"{typeName}<{innerType}>";
        }
        
        // For non-generic types, just get the last part after the last dot
        var lastDotIndex = name.LastIndexOf('.');
        return lastDotIndex >= 0 ? name.Substring(lastDotIndex + 1) : name;
    }

    private readonly struct ClassInfo(
        string className,
        string ns,
        ImmutableArray<DependencyInfo> dependencies)
    {
        public string ClassName { get; } = className;
        public string Namespace { get; } = ns;
        public ImmutableArray<DependencyInfo> Dependencies { get; } = dependencies;
    }

    private readonly struct DependencyInfo(string propertyName, string typeName, ImmutableArray<string> namespaces)
    {
        public string PropertyName { get; } = propertyName;
        public string TypeName { get; } = typeName;
        public ImmutableArray<string> Namespaces { get; } = namespaces;
    }
}

