using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace OpenWorker.Commands.SourceGenerators;

/// <summary>
/// Source generator that creates the AddCommands method for ServiceCollectionExtension.
/// </summary>
[Generator]
public class ServiceCollectionGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Get all classes that implement ICommand and have CommandTriggerAttribute
        var commandProvider = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => IsCandidateClass(node),
                transform: static (ctx, _) => GetCommandInfo(ctx))
            .Where(static info => info is not null)
            .Select(static (info, _) => info!.Value);

        // Collect all commands
        var allCommandsProvider = commandProvider.Collect();

        // Generate the ServiceCollectionExtension partial class
        context.RegisterSourceOutput(allCommandsProvider, static (spc, commands) => Execute(spc, commands));
    }

    private static bool IsCandidateClass(SyntaxNode node)
    {
        // Look for class declarations with attributes
        return node is ClassDeclarationSyntax { AttributeLists.Count: > 0 };
    }

    private static CommandInfo? GetCommandInfo(GeneratorSyntaxContext context)
    {
        if (context.Node is not ClassDeclarationSyntax classDecl)
        {
            return null;
        }

        var symbol = context.SemanticModel.GetDeclaredSymbol(classDecl);
        if (symbol is not INamedTypeSymbol classSymbol)
        {
            return null;
        }

        // Check if it implements ICommand
        var implementsICommand = classSymbol.AllInterfaces
            .Any(i => i.Name == "ICommand");

        if (!implementsICommand)
        {
            return null;
        }

        // Get CommandTriggerAttribute
        var triggerAttr = classSymbol.GetAttributes()
            .FirstOrDefault(attr => attr.AttributeClass?.Name == "CommandTriggerAttribute");

        if (triggerAttr == null)
        {
            return null;
        }

        return new CommandInfo(
            classSymbol.Name,
            classSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
            classSymbol.ContainingNamespace.ToDisplayString()
        );
    }

    private static void Execute(SourceProductionContext context, ImmutableArray<CommandInfo> commands)
    {
        if (commands.IsEmpty)
        {
            return;
        }

        var source = GenerateServiceCollectionExtensionClass(commands);
        context.AddSource("ServiceCollectionExtension.g.cs", source);
    }

    private static string GenerateServiceCollectionExtensionClass(ImmutableArray<CommandInfo> commands)
    {
        var sb = new StringBuilder();
        
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        
        // Add namespaces for all command types
        var namespaces = commands
            .Select(c => c.Namespace)
            .Distinct()
            .OrderBy(ns => ns);
        
        foreach (var ns in namespaces)
        {
            sb.AppendLine($"using {ns};");
        }
        
        sb.AppendLine();
        sb.AppendLine("namespace OpenWorker.Commands.Extensions;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Partial class with generated AddCommands method.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("public static partial class ServiceCollectionExtension");
        sb.AppendLine("{");
        
        // Generate AddCommands method
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Registers all commands in the dependency injection container.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    /// <param name=\"services\">The service collection to register commands in.</param>");
        sb.AppendLine("    private static void AddCommands(this IServiceCollection services)");
        sb.AppendLine("    {");
        
        // Register each command as singleton
        var orderedCommands = commands.OrderBy(c => c.TypeName);
        foreach (var command in orderedCommands)
        {
            var simpleName = GetSimpleTypeName(command.FullyQualifiedTypeName);
            sb.AppendLine($"        services.AddSingleton<{simpleName}>();");
        }
        
        sb.AppendLine("    }");
        sb.AppendLine("}");
        
        return sb.ToString();
    }

    private static string GetSimpleTypeName(string fullyQualifiedName)
    {
        // Remove "global::" prefix and namespace
        var name = fullyQualifiedName.Replace("global::", "");
        var lastDot = name.LastIndexOf('.');
        if (lastDot >= 0)
        {
            name = name.Substring(lastDot + 1);
        }
        return name;
    }

    private readonly struct CommandInfo(
        string typeName,
        string fullyQualifiedTypeName,
        string ns)
    {
        public string TypeName { get; } = typeName;
        public string FullyQualifiedTypeName { get; } = fullyQualifiedTypeName;
        public string Namespace { get; } = ns;
    }
}

