namespace OpenWorker.Hotspot.Modules.DailyMissions.Enums;

public enum DailyMissionHelperState : byte
{
    Del = 0x0,
    Add = 0x1
}

/* 361 */
internal enum E_DAILY_MISSION_FINISH : byte
{
    eDAILY_MISSION_FINISH_KILL = 0x1,
    eDAILY_MISSION_FINISH_MAZE_CLEAR = 0x2,
    eDAILY_MISSION_FINISH_PARTY_MAZE_CLEAR = 0x3,
    eDAILY_MISSION_FINISH_FRIEND = 0x4,
    eDAILY_MISSION_FINISH_COLLECT = 0x5,
    eDAILY_MISSION_FINISH_MYROOM = 0x6,
    eDAILY_MISSION_FINISH_MAX = 0x7
}

/* 362 */
internal enum E_DAILY_MISSION_TARGET : byte
{
    eDAILY_MISSION_TARGET_MONSTER = 0x1,
    eDAILY_MISSION_TARGET_MONSTER_GROUP = 0x2,
    eDAILY_MISSION_TARGET_MONSTER_FACTION = 0x3,
    eDAILY_MISSION_TARGET_MONSTER_ALL = 0x4,
    eDAILY_MISSION_TARGET_MAZE = 0x5,
    eDAILY_MISSION_TARGET_PC = 0x6,
    eDAILY_MISSION_TARGET_ITEM = 0x7
}

/* 363 */
internal enum E_DAILY_MISSION_CONDITION : byte
{
    eDAILY_MISSION_CONDITION_NONE = 0x0,
    eDAILY_MISSION_CONDITION_NORMAL_ATTACK = 0x1,
    eDAILY_MISSION_CONDITION_RISE_ATTACK = 0x2,
    eDAILY_MISSION_CONDITION_SKILL_ATTACK = 0x3,
    eDAILY_MISSION_CONDITION_SUBWEAPON_ATTACK = 0x4,
    eDAILY_MISSION_CONDITION_CRITICAL = 0x5,
    eDAILY_MISSION_CONDITION_DOWN = 0x6,
    eDAILY_MISSION_CONDITION_KNOCKBACK = 0x7,
    eDAILY_MISSION_CONDITION_DOWN_ATTACK = 0x8,
    eDAILY_MISSION_CONDITION_RANK_SS = 0x9,
    eDAILY_MISSION_CONDITION_TIME = 0xA,
    eDAILY_MISSION_CONDITION_LEVEL_GAP = 0xB,
    eDAILY_MISSION_CONDITION_CLASS = 0xC,
    eDAILY_MISSION_CONDITION_AVATAR = 0xD,
    eDAILY_MISSION_CONDITION_SOULWEAPON = 0xE,
    eDAILY_MISSION_CONDITION_TITLE_PREFIX = 0xF,
    eDAILY_MISSION_CONDITION_TITLE_SUFFIX = 0x10,
    eDAILY_MISSION_CONDITION_TITLE_PREFIX_SUFFIX = 0x11,
    eDAILY_MISSION_CONDITION_MAZE_TYPE = 0x12,
    eDAILY_MISSION_CONDITION_MYROOM_RECOMMEND = 0x13,
    eDAILY_MISSION_CONDITION_MYROOM_POLLEN_HELP = 0x14
}