namespace OpenWorker.Hotspot.Modules.DailyMissions.Enums;

internal enum E_DAILY_MISSION_FINISH : byte
{
    eDAILY_MISSION_FINISH_KILL = 0x1,
    eDAILY_MISSION_FINISH_MAZE_CLEAR = 0x2,
    eDAILY_MISSION_FINISH_PARTY_MAZE_CLEAR = 0x3,
    eDAILY_MISSION_FINISH_FRIEND = 0x4,
    eDAILY_MISSION_FINISH_COLLECT = 0x5,
    eDAILY_MISSION_FINISH_MYROOM = 0x6,
    eDAILY_MISSION_FINISH_MAX = 0x7
}