namespace OpenWorker.Hotspot.Modules.DailyMissions.Enums;

internal enum E_DAILY_MISSION_TARGET : byte
{
    eDAILY_MISSION_TARGET_MONSTER = 0x1,
    eDAILY_MISSION_TARGET_MONSTER_GROUP = 0x2,
    eDAILY_MISSION_TARGET_MONSTER_FACTION = 0x3,
    eDAILY_MISSION_TARGET_MONSTER_ALL = 0x4,
    eDAILY_MISSION_TARGET_MAZE = 0x5,
    eDAILY_MISSION_TARGET_PC = 0x6,
    eDAILY_MISSION_TARGET_ITEM = 0x7
}