// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OpenWorker.Persistence;

#nullable disable

namespace OpenWorker.Persistence.Migrations
{
    [DbContext(typeof(PersistenceContext))]
    [Migration("20250816102000_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OpenWorker.Domain.Persistent.AccountPersistent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Discord")
                        .HasColumnType("numeric(20,0)");

                    b.Property<DateTime>("LastLogin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("bytea");

                    b.Property<byte[]>("SaltHash")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("bytea");

                    b.Property<string>("SecondPassword")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TradePassword")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(12)
                        .IsUnicode(true)
                        .HasColumnType("character varying(12)");

                    b.HasKey("Id");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("OpenWorker.Domain.Persistent.GatePersistent", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(true)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Gates");
                });

            modelBuilder.Entity("OpenWorker.Domain.Persistent.LeaguePersistent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CardBorder")
                        .HasColumnType("integer");

                    b.Property<int>("CardEmblem")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MasterId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(12)
                        .IsUnicode(true)
                        .HasColumnType("character varying(12)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MasterId");

                    b.ToTable("Leagues");
                });

            modelBuilder.Entity("OpenWorker.Domain.Persistent.PersonPersistent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone");

                    b.Property<short>("DefaultEyeColor")
                        .HasColumnType("smallint");

                    b.Property<short>("DefaultHairColor")
                        .HasColumnType("smallint");

                    b.Property<short>("DefaultHairStyle")
                        .HasColumnType("smallint");

                    b.Property<short>("DefaultSkinColor")
                        .HasColumnType("smallint");

                    b.Property<short>("EquippedEyeColor")
                        .HasColumnType("smallint");

                    b.Property<short>("EquippedHairColor")
                        .HasColumnType("smallint");

                    b.Property<short>("EquippedHairStyle")
                        .HasColumnType("smallint");

                    b.Property<short>("EquippedSkinColor")
                        .HasColumnType("smallint");

                    b.Property<int>("FatiguePointBonus")
                        .HasColumnType("integer");

                    b.Property<int>("FatiguePointCommon")
                        .HasColumnType("integer");

                    b.Property<short>("GateId")
                        .HasColumnType("smallint");

                    b.Property<int>("Hero")
                        .HasColumnType("integer");

                    b.Property<int?>("LeagueId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(12)
                        .IsUnicode(true)
                        .HasColumnType("character varying(12)");

                    b.Property<long>("TitlePrimary")
                        .HasColumnType("bigint");

                    b.Property<long>("TitleSecondary")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("GateId");

                    b.HasIndex("LeagueId");

                    b.ToTable("Persons");
                });

            modelBuilder.Entity("OpenWorker.Domain.Persistent.LeaguePersistent", b =>
                {
                    b.HasOne("OpenWorker.Domain.Persistent.PersonPersistent", "Master")
                        .WithMany()
                        .HasForeignKey("MasterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Master");
                });

            modelBuilder.Entity("OpenWorker.Domain.Persistent.PersonPersistent", b =>
                {
                    b.HasOne("OpenWorker.Domain.Persistent.AccountPersistent", "Account")
                        .WithMany("Persons")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OpenWorker.Domain.Persistent.GatePersistent", "Gate")
                        .WithMany("Persons")
                        .HasForeignKey("GateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OpenWorker.Domain.Persistent.LeaguePersistent", "League")
                        .WithMany("MemberList")
                        .HasForeignKey("LeagueId");

                    b.Navigation("Account");

                    b.Navigation("Gate");

                    b.Navigation("League");
                });

            modelBuilder.Entity("OpenWorker.Domain.Persistent.AccountPersistent", b =>
                {
                    b.Navigation("Persons");
                });

            modelBuilder.Entity("OpenWorker.Domain.Persistent.GatePersistent", b =>
                {
                    b.Navigation("Persons");
                });

            modelBuilder.Entity("OpenWorker.Domain.Persistent.LeaguePersistent", b =>
                {
                    b.Navigation("MemberList");
                });
#pragma warning restore 612, 618
        }
    }
}
