namespace ow.Framework.Game.Datas.World.Table.Types
{
    public enum LayerBitmask : byte
    {
        Common,
        Normal,
        VeryHard,
        Expert,
        Stage01,
        Stage02,
        Stage03,
        Stage04,
        Stage05,
        Stage06,
        Stage07,
        Stage08,
        Stage09,
        Stage10,
        Stage11,
        Stage12,
        Stage13,
        Stage14,
        Stage15,
        Stage16,
        Stage17,
        Stage18,
        Stage19,
        Stage20,
        Stage21,
        Stage22,
        Stage23,
        Stage24,
        Stage25,
        Racon,
        Clash,
        Warfare
    }
}